// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Node-side acknowledgment pushed back up the relay.
 */
export type ConfigApplyAck = { applied_version: bigint, manifest_id: string, };

/**
 * The `Config.Apply` downlink payload: the manifest + its version for
 * idempotent push (replayed old versions are refused by the node).
 */
export type ConfigApplyParams = { manifest: GatewayManifest, 
/**
 * Monotonically increasing version (refuse <= applied).
 */
config_version: bigint, };

/**
 * Route action, discriminated by the `type` field (serde internally-tagged).
 */
export type GatewayAction = { "type": "proxy", 
/**
 * Upstream URL(s); multiple = load-balanced (P1 feature).
 */
upstream: Array<string>, 
/**
 * Load-balancing strategy (default round_robin).
 */
lb: string, 
/**
 * **Critical for SigV4**: preserve the original Host header.
 * rustfs presigned URLs verify the Host; changing it = 403.
 */
preserve_host: boolean, } | { "type": "static", status: number, body: string, } | { "type": "redirect", to: string, status: number, } | { "type": "reject", status: number, };

/**
 * Top-level manifest: identifies the document, pins the executing node,
 * and carries the server blocks.
 */
export type GatewayManifest = { 
/**
 * Schema version (for forward-compatible evolution).
 */
version: number, 
/**
 * Unique manifest id (for idempotent push/pull and audit).
 */
id: string, 
/**
 * Who produced this manifest ("chest-admin" or "hand-written").
 */
generated_by: string, 
/**
 * The tier-3 node that must execute this manifest (I2 invariant).
 */
exit_node: string, 
/**
 * Server blocks: one per public hostname.
 */
servers: Array<GatewayServer>, };

/**
 * Structured route matcher. Fields AND across, arrays OR within.
 * Rejects string-DSL patterns (traefik-style) — everything is
 * structurally validated at parse time.
 */
export type GatewayMatch = { 
/**
 * Path prefixes to match (any of).
 */
path_prefix: Array<string>, 
/**
 * Exact paths (any of).
 */
path: Array<string>, 
/**
 * HTTP methods (any of).
 */
methods: Array<string>, 
/**
 * Header presence/value match.
 */
headers: { [key in string]: string }, };

/**
 * Per-route rate limit.
 */
export type GatewayRateLimit = { requests: number, per: string, key: string, };

/**
 * One route: a structured matcher + a discriminated action.
 */
export type GatewayRoute = { 
/**
 * Route id (for logs and mutation targeting).
 */
id: string, 
/**
 * Structured match table (fields are AND'd; arrays within a field are OR'd).
 */
match: GatewayMatch, 
/**
 * What to do when the route matches (discriminated by `type`).
 */
action: GatewayAction, 
/**
 * Named middleware to apply (references or inline).
 */
use_: Array<string>, 
/**
 * Rate limit for this route.
 */
ratelimit: GatewayRateLimit | null, 
/**
 * Request body size ceiling.
 */
body_max: string | null, 
/**
 * Request timeout.
 */
timeout: string | null, };

/**
 * One public hostname's routing tree.
 */
export type GatewayServer = { 
/**
 * Public hostname(s) this server block answers (SNI + Host match).
 */
host: Array<string>, 
/**
 * Listen address (default `0.0.0.0:443`).
 */
listen: string, 
/**
 * TLS termination config.
 */
tls: GatewayTls | null, 
/**
 * Redirect plain HTTP to HTTPS (adds a :80 listener).
 */
redirect_http: boolean, 
/**
 * Ordered routes (first match wins).
 */
routes: Array<GatewayRoute>, };

/**
 * TLS material reference: the cert/key live on the tier-3 node's local
 * secure storage; the manifest only carries a **reference** (the door's
 * host), never the private key bytes.
 */
export type GatewayTls = { 
/**
 * `static` (file-based, managed by acme.sh + install-cert) — ACME
 * in-process is a future variant.
 */
type: string, 
/**
 * Reference to the door's certificate (e.g. "door:s3.celestia.world").
 */
cert: string, 
/**
 * Reference to the door's private key (same node-local storage).
 */
key: string, };
