// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * `device.bootstrap` result: the one-shot payload a freshly flashed
 * device fetches with its enrollment token (parity with the host agent's
 * `BootstrapResponse`).
 */
export type DeviceBootstrap = { node_id: string, 
/**
 * Candidate evernight-server endpoints (`ws(s)://…/api/ws`).
 */
server_urls: Array<string>, device_secret?: string | null, status?: string | null, };

/**
 * `enrollment.mint` params (parity with the gateway's `EnrollRequest`).
 */
export type EnrollmentMintParams = { 
/**
 * Free-form device label stored as the enrollment note.
 */
name?: string | null, 
/**
 * Explicit target server override (`ws(s)://…/api/ws`).
 */
target_server?: string | null, 
/**
 * Parent signing-certificate flow: when present the gateway prepares
 * the claims and the flasher signs locally with the key bound in the
 * certificate.
 */
signing?: SigningRequest | null, };

/**
 * `enrollment.mint` result, parent-chained path (parity with the
 * flasher's `MintParentChained`): the gateway only assigns identifiers
 * and returns the unsigned JOSE signing input; the flasher signs it with
 * the key bound in its parent certificate before burning to media.
 */
export type EnrollmentMintParentChained = { serial: string, node_id: string, 
/**
 * Unsigned JOSE signing input (base64url `header.payload`).
 */
signing_input: string, parent_jti: string, 
/**
 * Epoch seconds; clamped inside the parent certificate window.
 */
expires_at: bigint, 
/**
 * Epoch seconds.
 */
created_at: bigint, target_server?: string | null, name?: string | null, };

/**
 * `enrollment.mint` result, legacy gateway-signed path (parity with the
 * flasher's `EnrollmentMint`).
 */
export type EnrollmentMinted = { serial: string, node_id: string, enrollment_token: string, 
/**
 * Epoch seconds.
 */
expires_at: bigint, 
/**
 * Epoch seconds.
 */
created_at: bigint, target_server?: string | null, name?: string | null, };

/**
 * `enrollment.status` result (parity with the flasher's
 * `EnrollmentStatus`; `status` stays a free string — `"pending"`,
 * `"activated"`, `"revoked"`, `"expired"` — until every deployment
 * agrees on the enum).
 */
export type EnrollmentStatus = { serial: string, node_id: string, status: string, 
/**
 * Epoch seconds.
 */
created_at: bigint, activated_at?: bigint | null, activated_ip?: string | null, revoked_at?: bigint | null, 
/**
 * Epoch seconds.
 */
expires_at: bigint, name?: string | null, };

/**
 * `gateway.info` result: capability descriptor served before
 * authentication (replaces the old `rescue_channel_not_configured` +
 * `missing` map dance).
 */
export type GatewayServiceInfo = { 
/**
 * Human-readable service identifier, e.g. `"gateway"`.
 */
service: string, 
/**
 * Server version.
 */
version: string, 
/**
 * Whether the rescue channel is configured and usable.
 */
rescue_ready: boolean, 
/**
 * Unset configuration keys that keep `rescue_ready` false.
 */
missing?: Array<string>, 
/**
 * Deployment region descriptor (`"XX"` when unknown).
 */
region: string, };

/**
 * `enrollment.signing_cert.mint` result (parity with the flasher's
 * `ParentCertIssued`).
 */
export type ParentCertIssued = { 
/**
 * The signed certificate JWT.
 */
certificate: string, jti: string, 
/**
 * Not-before, epoch seconds (anchored at the operator's last login).
 */
nbf: bigint, 
/**
 * Expiry, epoch seconds.
 */
exp: bigint, };

/**
 * Quota outlook as adjudicated by the ERP quota service.
 */
export type QuotaState = { remaining: bigint, limit: bigint, allowed: boolean, };

/**
 * `rescue.diagnose` params. The diagnostics bundle is opaque to the
 * protocol (the model defines its shape).
 */
export type RescueDiagnoseParams = { bundle: JsonValue, 
/**
 * Ask for deferred mode (default false = the blocking behaviour that
 * every current deployment serves).
 *
 * The diagnostic LLM call has a budget of minutes, which far exceeds
 * the service profile's dispatch stall limit (a liveness guard measured
 * in seconds — see `plana-rpc-server`'s crate docs). A server that
 * implements deferred mode answers `deferred: true` immediately with
 * [`RescueDiagnoseStarted`] instead of holding the dispatch, and the
 * caller collects the [`RescueDiagnoseResult`] through the built-in
 * deferred-op methods (`ops.result {op_id}` / the advisory
 * `ops.settled` notification).
 *
 * **Adoption is a follow-up**: the reference gateway still drops this
 * flag and blocks until the model returns, so a client must not send
 * `deferred: true` until its target deployment has adopted it (it will
 * otherwise block, and answer the stall error past the limit). The flag
 * is defined here so the adoption is mechanical, and it is additive: a
 * server that ignores it keeps behaving exactly as before.
 */
deferred?: boolean, };

/**
 * `rescue.diagnose.progress` notification params.
 */
export type RescueDiagnoseProgressParams = { 
/**
 * Monotonic 1-based step counter.
 */
step: number, };

/**
 * `rescue.diagnose` result. Exactly one of the two shapes is returned,
 * selected by [`RescueDiagnoseParams::deferred`]:
 *
 * - `deferred: false` (default) → a completed diagnosis.
 * - `deferred: true` → [`RescueDiagnoseStarted`]: the op reference and its
 *   validity window.
 *
 * A client tells them apart by the presence of `op_id` (the deferred start)
 * versus `diagnosis` (the completed result); the two shapes share no field
 * name, so the discrimination is unambiguous.
 */
export type RescueDiagnoseResult = { 
/**
 * Structured diagnosis as produced by the model (opaque JSON).
 */
diagnosis: JsonValue, 
/**
 * Model identifier that produced the diagnosis.
 */
model: string, 
/**
 * RFC 3339 timestamp.
 */
generated_at: string, };

/**
 * `rescue.diagnose` result when [`RescueDiagnoseParams::deferred`] is set:
 * the work was handed off, this is what to collect it with.
 *
 * The shape is the generic deferred-op answer
 * (`plana::jsonrpc::deferred::DeferredOpCreated`) — declared here as well so
 * the gateway's published TypeScript bindings carry it without depending on
 * a generated file outside this package. [`DeferredOpCreated`] remains the
 * canonical definition; a parity test pins the two to the same wire shape.
 */
export type RescueDiagnoseStarted = { 
/**
 * Opaque, unguessable deferred-operation reference.
 */
op_id: string, 
/**
 * Remaining validity of `op_id` in seconds, measured from creation
 * (the 10–30 minute band; the collect call still works after a
 * reconnect inside the window).
 */
expires_in: bigint, };

/**
 * `rescue.open_session` params. The ticket is the one-shot opaque
 * credential issued by the OAuth callback redirect; it is consumed
 * exactly once at session mint.
 */
export type RescueOpenSessionParams = { ticket: string, };

/**
 * `rescue.open_session` result. The session handle itself is
 * connection-bound server state and never crosses the wire; the caller
 * learns only how long the bound session lives and the quota outlook.
 */
export type RescueSessionOpened = { 
/**
 * Seconds until the bound session expires.
 */
expires_in: bigint, quota: QuotaState, };

/**
 * `enrollment.signing_cert.mint` params (parity with `SigningCertRequest`).
 *
 * The protocol caps `ttl_days` at 3 years (1095 days): a stolen keystore
 * must die on its own within a bounded horizon.
 */
export type SigningCertParams = { 
/**
 * Client-generated Ed25519 public key, base64url raw (the JWK `x`).
 * The private half never leaves the flasher's keystore.
 */
public_key: string, 
/**
 * Requested validity in days, window anchored at the operator's last
 * login.
 */
ttl_days: bigint, };

/**
 * Parent-certificate mint selection inside [`EnrollmentMintParams`].
 */
export type SigningRequest = { parent_jti: string, };
