// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Runtime limits and prompt defaults of one agent.
 */
export type AgentConfig = { 
/**
 * How many tasks the agent runs at the same time.
 */
max_concurrent_tasks: number, 
/**
 * Per-task timeout in seconds.
 */
timeout_secs: number, 
/**
 * Whether a failed task is retried automatically before it is reported.
 */
retry_on_failure: boolean, 
/**
 * Model id the agent runs on.
 */
model: string, 
/**
 * System prompt prepended to the agent's conversations.
 */
system_prompt: string, };

/**
 * Container instance backing a running agent.
 */
export type AgentContainer = { 
/**
 * Container id as the container runtime reports it.
 */
id: string, 
/**
 * Image reference the container was created from.
 */
image: string, 
/**
 * Container lifecycle status; platform container operations use `Created`, `Running`,
 * `Stopped`, `Removed` and `Forked`.
 */
status: string, 
/**
 * Seconds the container has been up; the TS mirror renders it as `bigint`.
 */
uptime_secs: bigint, };

/**
 * Roster row of one platform agent as the retired panel served it: identity, lifecycle
 * status, its tool list and container, plus the per-user marketplace flags. No handler in
 * the workspace produces this shape any more — the live fleet DTO is `TuiAgentInfo` in the
 * ws bindings (`ws/agentLifecycle.ts`).
 */
export type AgentItem = { 
/**
 * Agent identity string; the row's tool list, skills and container hang off it.
 */
id: string, 
/**
 * Agent name shown in the roster.
 */
name: string, 
/**
 * What the agent does; non-optional on the wire, so the producer sends an empty string
 * rather than null when it has no description.
 */
description: string, 
/**
 * Agent family key — the `Agent` enum's wire value (e.g. `HubRis`) in the live fleet DTOs;
 * a plain string here because this shape predates the enum.
 */
agent_type: string, 
/**
 * Platform layer the agent sits on (0 = foundation primitives … 3 = service layer).
 */
layer: number, 
/**
 * Lifecycle status string; the live fleet types this as `AgentStatus`, whose wire values
 * are `Initializing`, `Online`, `Busy`, `Offline` and `Error`.
 */
status: string, 
/**
 * Whether the agent may be started at all; a disabled agent stays in the roster.
 */
enabled: boolean, 
/**
 * Tools the agent exposes, each with its own enable flag.
 */
tools: Array<AgentTool>, 
/**
 * Size of `tools`, serialized as `toolsCount`; carried alongside the array so a roster
 * can render the count without walking it.
 */
toolsCount: number, 
/**
 * Semantics TBC — see packages/celestia-types/tests/surface.rs:29 (the only site that
 * still names this DTO).
 */
subscribed: boolean, 
/**
 * Semantics TBC — see packages/celestia-types/tests/surface.rs:29 (the only site that
 * still names this DTO).
 */
installed: boolean, 
/**
 * Version string of the agent package this row describes.
 */
version: string, 
/**
 * Runtime configuration of the agent: concurrency, timeout, retry, model and prompt.
 */
config: AgentConfig, 
/**
 * Container backing the agent, or `null` when it has none running.
 */
container: AgentContainer | null, 
/**
 * Semantics TBC — see packages/celestia-types/tests/surface.rs:29 (the only remaining
 * site; the producer is gone, so the skill-id format is unfixed).
 */
skills: Array<string>, 
/**
 * Registration timestamp, serialized as `createdAt`.
 */
createdAt: string, 
/**
 * Last-modified timestamp, serialized as `updatedAt`.
 */
updatedAt: string, };

/**
 * One tool exposed by an agent in the roster.
 */
export type AgentTool = { 
/**
 * Tool identity string that the agent's configuration references.
 */
id: string, 
/**
 * Tool name shown in the roster's tool list.
 */
name: string, 
/**
 * What the tool does, shown next to the name.
 */
description: string, 
/**
 * Whether the agent may call this tool; disabled tools stay listed.
 */
enabled: boolean, };

/**
 * One entry of the per-user workspace alias registry (`workspace.registry`): the address a
 * user reaches a workspace by.
 */
export type AliasRegistryEntry = { 
/**
 * Workspace id (UUID string) the alias resolves to.
 */
workspace_uuid: string, 
/**
 * Human alias of the workspace, unique within its identity scope (one user, or one group
 * when the entry is group-scoped); a colliding group alias supersedes the user's.
 */
alias: string, 
/**
 * Short display id — the last 6 hex characters of the workspace UUID; globally unique and
 * resolvable on its own.
 */
short_id: string, };

/**
 * One avatar source the picker offers: a label plus a URL template the server fills in
 * (`auth.avatarPlatforms.list`).
 */
export type AvatarPlatformResponse = { 
/**
 * Row id (UUID string).
 */
id: string, 
/**
 * Stable slug derived from the label (lowercase, dashes); the admin UI keys rows by it.
 */
slug: string, 
/**
 * Display name shown in the picker.
 */
label: string, 
/**
 * Tera template carrying the domain and its placeholders (`{{ username }}`,
 * `{{ md5_email }}`, …); rendered per user server-side whenever an avatar URL is needed.
 */
url_template: string, 
/**
 * Short usage hint for the picker; `null` when the source has none.
 */
hint: string | null, 
/**
 * Whether users may pick the source; the user-facing list filters disabled rows out.
 */
enabled: boolean, 
/**
 * Ascending display order — the picker sorts by it.
 */
sort_order: number, };

/**
 * Reply of `auth.setAvatar` / `auth.removeAvatar`: the account's avatar URL after the change.
 */
export type AvatarUpdateResponse = { 
/**
 * New avatar URL; `null` after a successful removal.
 */
avatar_url: string | null, };

/**
 * Stored configuration of one channel adapter as the admin console reads it back — secrets
 * masked, ready to be edited in place.
 */
export type ChannelConfigDetail = { 
/**
 * Config row id (UUID string).
 */
id: string, 
/**
 * Platform key the config belongs to (same value set as `ChannelListItem.platform`).
 */
platform: string, 
/**
 * Whether the adapter may start for this config.
 */
enabled: boolean, 
/**
 * Operator-assigned name of the config.
 */
name: string, 
/**
 * Free-text description; omitted (not null) when unset.
 */
description?: string, 
/**
 * Bot token, masked server-side before serialization (`****` plus the last 4 characters,
 * or `****` alone for short secrets); omitted when no token is stored.
 */
bot_token?: string, 
/**
 * Application/client id of the bot — not a secret, so it travels unmasked; omitted when
 * unset.
 */
app_id?: string, 
/**
 * Application secret, masked exactly like `bot_token`; omitted when unset.
 */
app_secret?: string, 
/**
 * Webhook verification token, masked like `bot_token`; omitted when unset.
 */
verify_token?: string, 
/**
 * Endpoint base override for platforms that have a sandbox and a production host (e.g. QQ
 * bot); omitted when the adapter uses its built-in default.
 */
api_base?: string, 
/**
 * Platform-specific extras; omitted (not null) when unset. Typed as a plain object in TS
 * because each platform defines its own keys.
 */
extra_config?: Record<string, unknown>, 
/**
 * Inbound webhook path this config answers on.
 */
webhook_path: string, 
/**
 * Text of the last failed connect or health check; omitted when the last attempt succeeded.
 */
last_error?: string, 
/**
 * RFC 3339 time of the last successful test connection; omitted when the config has never
 * been tested.
 */
last_tested_at?: string, 
/**
 * RFC 3339 creation timestamp.
 */
created_at: string, 
/**
 * RFC 3339 last-update timestamp.
 */
updated_at: string, };

/**
 * One channel config plus whether a live adapter is currently registered for it.
 */
export type ChannelConfigResponse = { 
/**
 * The stored config, with secret fields masked.
 */
config: ChannelConfigDetail, 
/**
 * True when the registry holds a running adapter for this platform (or platform:instance)
 * key; a disabled config is never active.
 */
active: boolean, };

/**
 * Reply that wraps the channel config list.
 */
export type ChannelConfigsResponse = { 
/**
 * Config envelopes, one per stored row.
 */
configs: Array<ChannelConfigResponse>, };

/**
 * One channel adapter in the runtime list: its platform key, state and inbound webhook
 * path. This is adapter state, not the stored config (`ChannelConfigDetail`).
 */
export type ChannelListItem = { 
/**
 * Platform key: `telegram`, `discord`, `qqbot`, `lark`, `slack`, `wecom`, `teams`,
 * `matrix`, `google_chat`, `line`, `irc` or `mattermost`.
 */
platform: string, 
/**
 * Whether an adapter is running for this platform.
 */
enabled: boolean, 
/**
 * Bot display name the adapter reports; every built-in adapter currently reports none.
 */
bot_name: string, 
/**
 * Path of the platform's inbound webhook on this instance, e.g. `/api/webhook/telegram`.
 */
webhook_path: string, };

/**
 * Reply of the channel list: one entry per running adapter.
 */
export type ChannelListResponse = { 
/**
 * Running adapters, in registry order.
 */
channels: Array<ChannelListItem>, };

/**
 * One logged channel message (inbound intake or outbound send) in the admin message log.
 */
export type ChannelMessageItem = { 
/**
 * Log row id (UUID string).
 */
id: string, 
/**
 * Platform the message travelled over; same value set as `ChannelListItem.platform`, plus
 * `webhook` for ingress rows.
 */
platform: string, 
/**
 * Flow direction. Every row the current logging paths write is `inbound`; outbound sends
 * are not recorded in this log.
 */
direction: string, 
/**
 * Platform-side message id, used to correlate replies.
 */
message_id: string, 
/**
 * Platform-side conversation id the message belongs to.
 */
chat_id: string, 
/**
 * Platform-side sender id; `null` for messages with no identifiable sender.
 */
sender_id: string | null, 
/**
 * Message body as received or sent.
 */
text: string, 
/**
 * Whether the conversation is a group chat rather than a direct message.
 */
is_group: boolean, 
/**
 * Group or conversation id when `is_group` is true, `null` otherwise; ingress rows reuse
 * it to carry the webhook id.
 */
group_id: string | null, 
/**
 * Error text when the message failed to deliver; `null` on success.
 */
error: string | null, 
/**
 * RFC 3339 timestamp the row was written.
 */
created_at: string, };

/**
 * Reply of the channel message log (`admin.channels.messages`): newest first, capped.
 */
export type ChannelMessageListResponse = { 
/**
 * Log rows, newest first, capped by the caller's limit (100 default, 500 max).
 */
messages: Array<ChannelMessageItem>, 
/**
 * Number of rows returned after that cap — not the total number of logged messages.
 */
count: number, };

/**
 * Editor cursor snapshot: the IDE extensions POST one to `/api/workspace/cursor` on a
 * debounce, and the console replays the last one as the live-cursor indicator.
 */
export type CursorState = { 
/**
 * Workspace the cursor belongs to (the id handed out at session create); omitted, not
 * null, when unset.
 */
workspace_id?: string, 
/**
 * Edited file, workspace-relative; omitted when no file is active.
 */
file?: string, 
/**
 * Caret line, 1-based.
 */
line: number, 
/**
 * Caret column, 1-based.
 */
column: number, 
/**
 * Line count of the file, for the minimap; omitted when unknown.
 */
total_lines?: number, 
/**
 * Editor language id (`typescript`, `rust`, or a vim filetype); omitted when unknown.
 */
language?: string, 
/**
 * Viewport range, drawn as the peer's visible band; omitted when the editor reports none.
 */
visible_range?: CursorVisibleRange, };

/**
 * First visible line range of an editor viewport, as the IDE extension reports it.
 */
export type CursorVisibleRange = { 
/**
 * First visible line, 1-based inclusive.
 */
start: number, 
/**
 * Last visible line, 1-based inclusive.
 */
end: number, };

/**
 * Reply of the webhook delivery log (`GET /api/webhook/deliveries?limit=`); rows are
 * free-form because the log is generic over ingress sources.
 */
export type DeliveryListResponse = { 
/**
 * Delivery records as stored — the live log writes `{id, source, event_type,
 * payload_hash, success, error, created_at}` — but the field stays opaque JSON so new
 * sources can add keys without a type change.
 */
deliveries: Array<Record<string, unknown>>, 
/**
 * Number of rows actually returned after the limit clamp (100 default, 500 max) — not the
 * log's total size.
 */
count: number, };

/**
 * One device registered to an account, plus the last-known presence state of its row.
 */
export type DeviceResponse = { 
/**
 * Row id (UUID string); device sessions point at it through their own `device_id` column.
 */
id: string, 
/**
 * Device-supplied identifier of the machine or browser, unique per account: re-registering
 * the same device resolves to the same row rather than adding one.
 */
device_id: string, 
/**
 * Operator-visible device name.
 */
name: string, 
/**
 * Device class stored on the row; the schema default is `both`.
 */
device_type: string, 
/**
 * Presence status stored on the row; the schema default is `unknown`.
 */
status: string, 
/**
 * Time of the last contact; `null` when the device has never connected.
 */
last_seen_at: string | null, 
/**
 * Free-form device metadata (arch, GPUs, …); omitted (not null) when the row has none.
 */
metadata?: Record<string, unknown>, 
/**
 * Registration timestamp.
 */
created_at: string, };

/**
 * One directory entry of the legacy listing. No producer in the workspace emits it.
 */
export type FileEntry = { 
/**
 * Entry name only — the parent directory lives on `FileListingResponse.path`.
 */
name: string, 
/**
 * Entry kind, serialized as `type` (renamed because `type` is a Rust keyword).
 */
type: string, 
/**
 * Size in bytes, `null` for entries that have no size; the TS mirror renders it
 * as `bigint | null`.
 */
size: bigint | null, };

/**
 * Legacy directory-listing payload: a directory path plus the entries found in it.
 * No handler in the workspace serves this shape any more — the unified file picker
 * resolves directories through `Sync.RequestFileTree` — so it is kept for wire
 * compatibility only.
 */
export type FileListingResponse = { 
/**
 * Directory the listing was taken from, spelled the way the producer reported it.
 */
path: string, 
/**
 * One row per directory entry; order is whatever the producer walked.
 */
entries: Array<FileEntry>, };

/**
 * State of the webhook IP allowlist: the enforcement toggle plus the per-source CIDR sets
 * it evaluates.
 */
export type IpWhitelistResponse = { 
/**
 * Whether the allowlist is enforced; when false every caller passes the check.
 */
enabled: boolean, 
/**
 * Per-source entries — `{source, cidrs}` from the built-in github/gitlab/gitee sets — left
 * as opaque JSON so operators can extend them.
 */
whitelist: Array<Record<string, unknown>>, };

/**
 * One (provider, model) pair flattened for the model picker — a model id is only unique
 * together with the provider that serves it.
 */
export type ModelInfo = { 
/**
 * Model id exactly as the endpoint spells it (e.g. `deepseek-v4-flash`).
 */
id: string, 
/**
 * Display name of the serving provider — the `ProviderPublic.name` the router keys on.
 */
provider_name: string, 
/**
 * Id of the serving provider as a string, so the picker can deep-link to its row.
 */
provider_id: string, 
/**
 * Capability class copied from the provider; `chat` for conversational endpoints.
 */
category: string, };

/**
 * One project row in the project picker: display metadata plus the manual ordering key.
 */
export type ProjectItem = { 
/**
 * Project id (UUID string); scene configs and device models hang off it.
 */
id: string, 
/**
 * Project name shown in the picker.
 */
name: string, 
/**
 * Free-text description; `null` when unset.
 */
description: string | null, 
/**
 * Ascending manual order the project list is sorted by; new projects default to 0.
 */
sort_order: number, 
/**
 * RFC 3339 creation timestamp.
 */
created_at: string, 
/**
 * RFC 3339 last-update timestamp.
 */
updated_at: string, };

/**
 * One configured LLM provider as the console's Providers page reads it: the stored row with
 * its API key reduced to a masked hint — the raw key never crosses the wire.
 */
export type ProviderPublic = { 
/**
 * Provider row id (UUID rendered as a string); every `ModelInfo` row of this provider
 * repeats it as `provider_id`.
 */
id: string, 
/**
 * Operator-assigned display name. The router keys the model→provider map by this name, so
 * two providers sharing a name collapse into one entry.
 */
name: string, 
/**
 * OpenAI-compatible base URL requests are sent to; loopback and cloud-metadata hosts are
 * rejected when a provider is saved.
 */
endpoint: string, 
/**
 * Stored API key masked server-side — never the raw secret. The JSON-RPC path keeps
 * `****` plus the last 4 characters (`****` alone for keys of 8 characters or fewer), the
 * REST path serves a fixed `••••••••`; an empty string means no key is stored.
 */
api_key_masked: string, 
/**
 * Model ids this provider serves; each one becomes a `ModelInfo` row in the model picker.
 */
models: Array<string>, 
/**
 * Capability class of the provider, `chat` for conversational endpoints; copied to every
 * model row of this provider.
 */
category: string, 
/**
 * Whether the provider takes part in routing; disabled rows stay in the list but are
 * skipped when the registry is loaded.
 */
enabled: boolean, 
/**
 * Ascending sort key: lower sorts first. The console numbers providers in this order for
 * the `#N` suffix on model tags.
 */
priority: number, };

/**
 * Host snapshot behind the console's System info tab (`admin.system.getInfo`), computed on
 * demand from the `sysinfo` crate; every usage field is a percentage, not an absolute.
 */
export type ProxySystemInfo = { 
/**
 * Version of the serving backend build.
 */
version: string, 
/**
 * Runtime identifier string, e.g. `rust 1.8x.y`; the field name survives from the
 * Node-based panel and does not mean a Node runtime. Serialized as `nodeVersion`.
 */
nodeVersion: string, 
/**
 * Composite host description: long OS version, CPU architecture and kernel version
 * (e.g. `Ubuntu 24.04.1 LTS x86_64 (6.8.0-45-generic)`) — not a bare OS name.
 */
platform: string, 
/**
 * Aggregate CPU load as a percentage, 0–100, rounded to one decimal; serialized as
 * `cpuUsage`.
 */
cpuUsage: number, 
/**
 * Used physical memory as a percentage of the total, 0–100, rounded to one decimal;
 * serialized as `memoryUsage`.
 */
memoryUsage: number, 
/**
 * Used space of the root mount as a percentage of its size, 0–100, rounded to one
 * decimal; serialized as `diskUsage`. Reads 0 when no size is available.
 */
diskUsage: number, };

export type RbacGroup = { id: string, name: string, description: string | null, 
/**
 * Members attached to this listing (the list response computes it from
 * the membership table; single-group reads may not). Carried since the
 * first DTO revision — the doc comment is what 2026-10-06 added.
 */
member_count: number, 
/**
 * Personal-visibility enforcement: members see only their own
 * resources while the flag is on (and must acknowledge it once).
 */
enforce_personal_visibility: boolean, 
/**
 * Builtin groups ship with the deployment and cannot be deleted.
 */
is_builtin: boolean, 
/**
 * Stable key for a builtin group (e.g. "administrators"); null for
 * admin-authored groups.
 */
builtin_key: string | null, 
/**
 * Admin-authored per-locale display names (locale tag → name); null
 * when none are authored.
 */
display_names: { [key in string]: string } | null, created_at: string, updated_at: string, };

/**
 * One resource quota row: a ceiling plus the usage booked against it for a single
 * resource dimension.
 */
export type ResourceQuota = { 
/**
 * Stable row id (e.g. `quota-cpu`).
 */
id: string, 
/**
 * Display name of the quota row.
 */
name: string, 
/**
 * Metered dimension; the served defaults are `cpu`, `memory`, `disk` and `agents`.
 */
resource_type: string, 
/**
 * Ceiling expressed in `limit_unit`. A non-positive value yields 0% utilization rather
 * than an infinite or NaN percentage.
 */
limit_value: number, 
/**
 * Unit both the ceiling and the usage are expressed in (`cores`, `MB`, `count`); free-form.
 */
limit_unit: string, 
/**
 * Usage booked against the ceiling, in `limit_unit`.
 */
used_value: number, 
/**
 * Reset window label; the served quota defaults use `monthly`, the live token view `30d`.
 */
period: string, 
/**
 * Tier the quota belongs to (`standard`); a quota-only field that the usage summary drops.
 */
tier: string, 
/**
 * Whether the row is enforced.
 */
enabled: boolean, };

/**
 * Reply of `usage.quotas.list`: the quota rows the console renders as cards.
 */
export type ResourceQuotaListResponse = { 
/**
 * Quota rows; the served default set is cpu, memory, disk and agents.
 */
quotas: Array<ResourceQuota>, };

/**
 * Reply of the resource-usage gauge endpoint.
 */
export type ResourceUsageResponse = { 
/**
 * Gauge rows — one per quota row, or one per metered subject in the live 30-day token view.
 */
summary: Array<ResourceUsageSummary>, };

/**
 * One quota-gauge card. Derived from a quota row: id, name and tier are deliberately
 * dropped, so this is the shape the dashboard renders rather than the stored row.
 */
export type ResourceUsageSummary = { 
/**
 * Metered dimension, falling back to `unknown` for partial rows.
 */
resource_type: string, 
/**
 * Usage booked against the quota, in `unit`.
 */
current_usage: number, 
/**
 * Unit of both `current_usage` and `limit`.
 */
unit: string, 
/**
 * Ceiling in `unit`; 0 for partial rows.
 */
limit: number, 
/**
 * Reset window label, defaulting to `monthly`.
 */
period: string, 
/**
 * `current_usage / limit` as a percentage rounded to two decimals; 0 when the limit is not
 * positive, so it is never infinite or NaN.
 */
utilization_pct: number, };

/**
 * Bloom (glow) post-processing parameters.
 */
export type SceneBloom = { 
/**
 * Bloom intensity (built-in scene: 0.5).
 */
strength: number, 
/**
 * Bloom spread radius (built-in scene: 0.4).
 */
radius: number, 
/**
 * Luminance above which pixels bloom (built-in scene: 0.85).
 */
threshold: number, };

/**
 * Camera placement of the scene: where it looks from, what it looks at, and optional named
 * bookmarks.
 */
export type SceneCamera = { 
/**
 * Camera position in scene units.
 */
position: SceneVec3, 
/**
 * Point the camera looks at, in scene units.
 */
target: SceneVec3, 
/**
 * Named camera presets keyed by bookmark name; omitted (not null) when the scene has none.
 */
bookmarks?: { [key in string]: SceneCameraBookmark } | null, };

/**
 * One named camera preset: the position and target restored when the bookmark is picked.
 */
export type SceneCameraBookmark = { 
/**
 * Saved camera position, in scene units.
 */
position: SceneVec3, 
/**
 * Saved look-at point, in scene units.
 */
target: SceneVec3, };

/**
 * Scene configuration of one project: background, optional ground and lighting, grid,
 * camera, bloom and the ambient level — the descriptor the preview renderer applies.
 */
export type SceneConfigItem = { 
/**
 * Project this scene belongs to (UUID string); the scene config is keyed by it.
 */
project_id: string, 
/**
 * Background colour as a hex string (e.g. `#0a0a1a`).
 */
background_color: string, 
/**
 * Ground plane settings; serialized as `null` (not omitted) when the scene has none.
 */
ground: SceneGround | null, 
/**
 * Ambient and directional light settings; serialized as `null` when the scene has none.
 */
lighting: SceneLighting | null, 
/**
 * Grid helper settings; always present.
 */
grid: SceneGrid, 
/**
 * Initial camera placement and its named bookmarks.
 */
camera: SceneCamera, 
/**
 * Bloom post-processing parameters; always present.
 */
bloom: SceneBloom, 
/**
 * Linear ambient-light multiplier the renderer applies (built-in scene: 0.6). Distinct
 * from `lighting.ambient_intensity`, which the live renderer ignores.
 */
ambient_light_intensity: number, };

/**
 * The scene's standalone grid helper; `SceneGround` carries a second, independent grid.
 */
export type SceneGrid = { 
/**
 * Whether the grid is drawn.
 */
visible: boolean, 
/**
 * Grid extent in scene units.
 */
size: number, 
/**
 * Number of cells the grid is divided into (built-in scene: 80 units over 40 cells).
 */
divisions: number, };

/**
 * Ground plane of the scene, along with the grid overlay drawn on it.
 */
export type SceneGround = { 
/**
 * Whether the ground plane is drawn at all; the grid overlay follows `grid_visible`.
 */
enabled: boolean, 
/**
 * Ground extent along X, in scene units.
 */
size_x: number, 
/**
 * Ground extent along Z, in scene units.
 */
size_z: number, 
/**
 * Ground colour as a hex string.
 */
color: string, 
/**
 * Height of the ground plane on the Y axis, in scene units; negative sinks it below the
 * scene origin.
 */
y: number, 
/**
 * Whether the ground's own grid overlay is drawn (independent of `SceneGrid.visible`).
 */
grid_visible: boolean, 
/**
 * Extent of that grid overlay, in scene units.
 */
grid_size: number, 
/**
 * Number of cells the overlay is divided into.
 */
grid_divisions: number, 
/**
 * Grid line colour as a hex string.
 */
grid_color: string, 
/**
 * Grid line opacity, 0–1 (built-in scene: 0.25).
 */
grid_opacity: number, };

/**
 * Ambient and directional light settings of the scene.
 */
export type SceneLighting = { 
/**
 * Ambient light colour as an RGB triple; components are linear, 0–1.
 */
ambient_color: [number, number, number], 
/**
 * Ambient intensity as stored (built-in scene: 500). The live preview renderer takes the
 * ambient level from `SceneConfigItem.ambient_light_intensity` and ignores this field.
 */
ambient_intensity: number, 
/**
 * Directional light colour as an RGB triple; components are linear, 0–1.
 */
directional_color: [number, number, number], 
/**
 * Directional light intensity passed to the renderer; the preview falls back to 1 when the
 * producer leaves it at its default.
 */
directional_intensity: number, 
/**
 * Light position as an XYZ triple in scene units (built-in scene: (15, 80, 30)).
 */
directional_position: [number, number, number], };

/**
 * A point or direction in scene space; the same three numbers mean different things
 * depending on which field carries them.
 */
export type SceneVec3 = { 
/**
 * X component, in scene units.
 */
x: number, 
/**
 * Y component, in scene units — up in the renderer's frame.
 */
y: number, 
/**
 * Z component, in scene units.
 */
z: number, };

/**
 * Reply of the WebRTC device-session create: the session handle plus its first signaling
 * payload.
 */
export type SessionCreateResponse = { 
/**
 * Session id (UUID string) that every later offer, answer and ICE call carries.
 */
session_id: string, 
/**
 * Session status: a freshly created session is `pending`, turns `active` on the first
 * offer and `closed` when torn down.
 */
status: string, 
/**
 * WebRTC signaling payload (SDP offer/answer or ICE candidate) to hand to the peer; omitted
 * (not null) when there is nothing to relay yet.
 */
signaling?: Record<string, unknown>, };

/**
 * First-run probe the client boots through: whether the instance still needs its initial
 * administrator, its default locale and whether self-registration is open.
 */
export type SetupCheckResponse = { 
/**
 * True while the instance has no accounts at all; the client then routes to setup.
 */
needs_setup: boolean, 
/**
 * Instance default locale from system settings; omitted (not null) when unset.
 */
locale?: string, 
/**
 * Whether self-registration is open. The server ANDs the stored toggle with "at least one
 * account exists", so a fresh instance always reports false here.
 */
registration_enabled: boolean, };

/**
 * One skill in the catalogue (`skills.list`): who may run it, what it needs and how long
 * it typically takes.
 */
export type SkillItem = { 
/**
 * Stable skill id the agent tooling dispatches on.
 */
skill_id: string, 
/**
 * Skill name shown in the picker.
 */
name: string, 
/**
 * What the skill does, shown beside the name.
 */
description: string, 
/**
 * Catalogue grouping of the skill.
 */
category: string, 
/**
 * Agent family that owns the skill.
 */
agent: string, 
/**
 * Agent families allowed to run the skill; more than one when it is shared.
 */
agent_types: Array<string>, 
/**
 * Declared parameters, in signature order.
 */
parameters: Array<SkillParameterItem>, 
/**
 * Typical wall-clock duration in seconds; the TS mirror renders it as `bigint`.
 */
estimated_duration_secs: bigint, };

/**
 * One parameter of a skill's signature, as the skill catalogue declares it.
 */
export type SkillParameterItem = { 
/**
 * Parameter name as the skill expects it on the call.
 */
name: string, 
/**
 * Declared parameter type, serialized as `type` (renamed because `type` is a Rust keyword).
 */
type: string, 
/**
 * Value applied when the caller omits the parameter; omitted (not null) when there is none.
 * Typed `unknown` in TS because the JSON type follows `param_type`.
 */
default?: unknown, 
/**
 * Free-text description; serialized as `null` when absent (no `skip_serializing_if`).
 */
description: string | null, 
/**
 * Whether the caller must supply the parameter.
 */
required: boolean, };

/**
 * Agent-fleet rollup of the legacy snapshot: one count per lifecycle bucket. No producer
 * fixes whether the buckets partition `total` or count containers rather than sessions.
 */
export type SystemInfoAgents = { 
/**
 * Size of the fleet the snapshot covers; the per-state counts below are its breakdown.
 */
total: number, 
/**
 * Semantics TBC — see packages/celestia-types/bindings/httpTypes.ts:87 (the generated
 * mirror is the only remaining definition of this rollup).
 */
running: number, 
/**
 * Semantics TBC — see packages/celestia-types/bindings/httpTypes.ts:87 (the generated
 * mirror is the only remaining definition of this rollup).
 */
idle: number, 
/**
 * Semantics TBC — see packages/celestia-types/bindings/httpTypes.ts:87 (the generated
 * mirror is the only remaining definition of this rollup).
 */
stopped: number, };

/**
 * Live connection counters of the legacy snapshot, split by transport.
 */
export type SystemInfoConnections = { 
/**
 * WebSocket connections the instance held at snapshot time.
 */
active_ws: number, 
/**
 * HTTP requests in flight at snapshot time (not a cumulative count).
 */
active_http: number, };

/**
 * Database identity and load counters of the legacy snapshot.
 */
export type SystemInfoDatabase = { 
/**
 * Database engine name, e.g. `postgresql`.
 */
engine: string, 
/**
 * Database size in megabytes, as a whole number.
 */
size_mb: number, 
/**
 * Connections open to the database at snapshot time.
 */
connections: number, };

/**
 * Host resource counters of the legacy snapshot; the units are the ones the field names
 * carry, and the CPU figure is the same quantity `ProxySystemInfo.cpuUsage` reports.
 */
export type SystemInfoResources = { 
/**
 * Aggregate CPU load as a percentage, 0–100.
 */
cpu_usage_pct: number, 
/**
 * Physical memory in use, in gigabytes.
 */
memory_used_gb: number, 
/**
 * Physical memory installed, in gigabytes — the denominator for `memory_used_gb`.
 */
memory_total_gb: number, 
/**
 * Disk space in use, in gigabytes.
 */
disk_used_gb: number, 
/**
 * Total disk space, in gigabytes — the denominator for `disk_used_gb`.
 */
disk_total_gb: number, };

/**
 * Legacy rich host snapshot. No handler in the workspace serves this shape — the System
 * info tab reads `ProxySystemInfo` — so it is kept for wire compatibility only.
 */
export type SystemInfoResponse = { 
/**
 * Version string of the serving instance, in the same format as `ProxySystemInfo.version`.
 */
version: string, 
/**
 * Seconds the backend process has been running, counted from process start.
 */
uptime_secs: bigint, 
/**
 * Agent-fleet rollup; see `SystemInfoAgents`.
 */
agents: SystemInfoAgents, 
/**
 * Host CPU, memory and disk counters, in the units the field names carry.
 */
resources: SystemInfoResources, 
/**
 * Live connection counters, split by transport.
 */
connections: SystemInfoConnections, 
/**
 * Database identity and load counters.
 */
database: SystemInfoDatabase, };

/**
 * One entry of the tier catalogue the instance serves; the console renders these as plan
 * cards and `UpdateUserTierPayload` moves accounts between them.
 */
export type TierDefinition = { 
/**
 * Tier slug — `free`, `pro` and `enterprise` in the built-in catalogue.
 */
tier: string, 
/**
 * Requests allowed per day; `-1` means unlimited (the built-in enterprise row).
 */
daily_request_limit: number, 
/**
 * Tokens allowed per month.
 */
monthly_token_limit: number, 
/**
 * Concurrent sessions allowed; `-1` means unlimited.
 */
max_sessions: number, 
/**
 * Display price string (`$0`, `$29/mo`, `Custom`) — presentation text, not a number to
 * compute with.
 */
price: string, };

/**
 * Reply of the tier catalogue endpoint.
 */
export type TierListResponse = { 
/**
 * Served tiers in catalogue order (free, pro, enterprise).
 */
tiers: Array<TierDefinition>, };

/**
 * Reply of the token-usage query (`GET /chat/token-usage?since=&until=`): one bucket per
 * grouping value plus the window total.
 */
export type TokenUsageResponse = { 
/**
 * One bucket per grouping dimension value; empty when nothing was metered in the window.
 */
usage: Array<UsageEntry>, 
/**
 * Sum of tokens over all buckets, as a signed 64-bit count (the aggregation is an SQL SUM,
 * hence i64 rather than the u64 used elsewhere).
 */
total_tokens: bigint, };

/**
 * One tool in the platform tool catalogue: its JSON-Schema contract and the agent that
 * owns it.
 */
export type ToolItem = { 
/**
 * Stable tool id the agent dispatches on.
 */
tool_id: string, 
/**
 * Tool name shown in the picker.
 */
name: string, 
/**
 * What the tool does, shown beside the name.
 */
description: string, 
/**
 * Catalogue grouping of the tool.
 */
category: string, 
/**
 * Agent family that owns the tool.
 */
agent: string, 
/**
 * JSON Schema of the tool's arguments; typed as a plain object in TS and never null.
 */
input_schema: Record<string, unknown>, 
/**
 * JSON Schema of the tool's result; omitted (not null) when the tool declares none.
 */
output_schema?: Record<string, unknown>, };

/**
 * Admin request body that moves one account onto another tier.
 */
export type UpdateUserTierPayload = { 
/**
 * Account to move, as a string UUID.
 */
user_id: string, 
/**
 * Target tier slug; must be one of the catalogue's `TierDefinition.tier` values.
 */
tier: string, };

/**
 * Usage dashboard payload: window totals plus per-model and per-day breakdowns.
 */
export type UsageDataResponse = { 
/**
 * Window label the figures cover, free-form (`30d`, `monthly`) — the client echoes what it
 * asked for and no producer normalises it.
 */
period: string, 
/**
 * Tokens consumed in the window, across all models.
 */
total_tokens: bigint, 
/**
 * Spend attributable to those tokens, in US dollars — not cents.
 */
total_cost_usd: number, 
/**
 * Per-model rows, unordered.
 */
by_model: Array<UsageModelEntry>, 
/**
 * Per-day rows for the trend chart, unordered.
 */
by_day: Array<UsageDayEntry>, };

/**
 * One row of the per-day usage breakdown; rows carry no cost split, only volume.
 */
export type UsageDayEntry = { 
/**
 * Day bucket key as a calendar date string; the producer decides its exact format.
 */
date: string, 
/**
 * Tokens consumed on that day.
 */
tokens: bigint, 
/**
 * Requests served on that day.
 */
requests: number, };

/**
 * One usage bucket. `model` stays the bucket-key carrier whatever the grouping is, so the
 * group-by-user and group-by-workspace replies reuse this exact shape.
 */
export type UsageEntry = { 
/**
 * Bucket key: normally a model id, but the user id or workspace id under those groupings;
 * unattributed rows read `unknown`.
 */
model: string, 
/**
 * Tokens attributed to this bucket; the TS mirror renders it as `bigint`.
 */
token_count: bigint, };

/**
 * One row of the per-model usage breakdown.
 */
export type UsageModelEntry = { 
/**
 * Model id this row aggregates.
 */
model: string, 
/**
 * Tokens consumed by this model in the window.
 */
tokens: bigint, 
/**
 * Spend for this model in US dollars.
 */
cost_usd: number, 
/**
 * Requests charged to this model in the window.
 */
requests: number, };

/**
 * Per-user UI preferences, stored under `auth_users.preferences` with camelCase keys and
 * echoed to the client in that same spelling.
 */
export type UserPreferences = { 
/**
 * Theme id the user picked (e.g. `shittim`); omitted when unset.
 */
theme?: string, 
/**
 * Light/dark mode, serialized as `themeMode`; omitted when unset.
 */
themeMode?: string, 
/**
 * Chat layout mode the user selected (the console's chat-mode tab key), serialized as
 * `chatMode`; omitted when unset.
 */
chatMode?: string, 
/**
 * UI language tag (e.g. `zh-Hans`); omitted when unset, and the client then falls back to
 * the instance default.
 */
locale?: string, };

/**
 * The signed-in account as `auth.getMe` returns it: account fields, the derived role, RBAC
 * groups and stored preferences.
 */
export type UserProfileResponse = { 
/**
 * Account id (UUID string).
 */
id: string, 
/**
 * Login name; unique per instance.
 */
username: string, 
/**
 * Account email, or an empty string when the account has none.
 */
email: string, 
/**
 * Name shown in the UI, or an empty string when unset.
 */
display_name: string, 
/**
 * Resolved avatar URL; `null` when the account has no avatar.
 */
avatar_url: string | null, 
/**
 * Whether the account may sign in; a deactivated account stays visible to admins.
 */
is_active: boolean, 
/**
 * Effective role derived from built-in group membership: `admin`, `operator`, `viewer` or
 * `member`.
 */
role: string, 
/**
 * Explicit RBAC group memberships, each with id, name, description and timestamps.
 */
groups: Array<RbacGroup>, 
/**
 * Stored UI preferences; omitted (not null) when the account has none.
 */
preferences?: UserPreferences, 
/**
 * Account creation timestamp as this handler renders it — the database timestamp's plain
 * string form, not RFC 3339. Every other timestamp on this DTO family is RFC 3339.
 */
created_at: string, };

/**
 * Legacy per-user tier snapshot: the tier, its expiry and the quota consumed so far.
 * No handler in the workspace emits this shape — the quota views read the billing
 * self-overview — so it is kept for wire compatibility only.
 */
export type UserTierInfo = { 
/**
 * Account the snapshot describes, as a string UUID.
 */
user_id: string, 
/**
 * Tier slug the account is on; `TierDefinition.tier` supplies the value set.
 */
tier: string, 
/**
 * RFC 3339 expiry of the tier; omitted (not null) when the tier does not expire.
 */
tier_expires_at?: string, 
/**
 * Quota consumed in the current day, in the tier's own quota unit.
 */
daily_quota_used: number, 
/**
 * Tokens consumed in the current month.
 */
monthly_token_used: number, 
/**
 * RFC 3339 time of the last quota reset; omitted when the account has never been reset.
 */
last_quota_reset_at?: string, };

/**
 * Result of the wizard's live key check: the endpoint is dialled with the candidate key and
 * its model list comes back.
 */
export type ValidateKeyResponse = { 
/**
 * Whether the dial succeeded — HTTP 2xx with a parseable model list.
 */
valid: boolean, 
/**
 * Model ids the endpoint reported; empty when the check failed.
 */
models: Array<string>, 
/**
 * Preselection shortlist drawn from `models` (flagship chat models, newest first); empty
 * when the endpoint's order gives nothing to rank.
 */
recommended_models: Array<string>, 
/**
 * Failure text the wizard shows when `valid` is false; serialized as `null` on success
 * because the field has no `skip_serializing_if`.
 */
error: string | null, };

/**
 * One vendor preset of the create-provider wizard's catalogue (generated from the
 * provider-registry snapshot) — a template for a new provider, not a configured one.
 */
export type VendorInfo = { 
/**
 * Stable vendor slug (`anthropic`, `openai`, …) used as the wizard's preset key.
 */
id: string, 
/**
 * Vendor name shown in the wizard.
 */
name: string, 
/**
 * API base URL prefilled when this vendor is chosen.
 */
endpoint: string, 
/**
 * Catalogue bucket from the registry snapshot (e.g. `cloud`); not the provider's own
 * `category` capability class.
 */
category: string, 
/**
 * Free-text blurb; the served catalogue sends an empty string today and the wizard does
 * not render it.
 */
description: string, 
/**
 * Newest-generation-first shortlist the wizard preselects: flagship chat models of this
 * vendor that the live endpoint actually serves.
 */
recommended_models: Array<string>, 
/**
 * Per-plan model allowlists keyed by plan name; the served catalogue sends an empty object
 * today.
 */
plan_models: { [key in string]: Array<string> }, };

/**
 * Provider-agnostic webhook delivery row; the `Gen` variant is the one that names its
 * units, unlike `WebhookDeliveryItem`.
 */
export type WebhookDeliveryGenItem = { 
/**
 * Delivery record id.
 */
id: string, 
/**
 * Id of the subscription the delivery belongs to.
 */
webhook_id: string, 
/**
 * Event name that triggered the delivery.
 */
event: string, 
/**
 * HTTP status code the receiver returned; named `status` because this shape predates
 * `status_code`.
 */
status: number, 
/**
 * Delivery duration in milliseconds.
 */
duration_ms: bigint, 
/**
 * RFC 3339 time of the delivery attempt.
 */
timestamp: string, 
/**
 * Headers sent with the request.
 */
request_headers: { [key in string]: string }, 
/**
 * Parsed JSON body the receiver answered with; omitted entirely when it is JSON `null`.
 * The request side is not recorded in this shape.
 */
response_body?: Record<string, unknown>, };

/**
 * One row of the webhook delivery log: what was sent, what came back and how long it took.
 * The live ingress log in the chest console carries the same data under slightly
 * different key names.
 */
export type WebhookDeliveryItem = { 
/**
 * Delivery record id.
 */
id: string, 
/**
 * Id of the `WebhookItem` subscription this delivery belongs to; serialized as `webhookId`.
 */
webhookId: string, 
/**
 * Event that triggered the delivery; the live ingress path records the literal `ingress`.
 */
event: string, 
/**
 * HTTP status the receiver returned, serialized as `statusCode`; the live ingress log
 * records 200 on success and 401 when the signature check failed.
 */
statusCode: number, 
/**
 * Headers sent with the request, serialized as `requestHeaders`.
 */
requestHeaders: { [key in string]: string }, 
/**
 * JSON body that was sent, serialized as `requestBody`; omitted entirely when the value
 * is JSON `null`.
 */
requestBody?: Record<string, unknown>, 
/**
 * Headers the receiver answered with, serialized as `responseHeaders`; omitted (not null)
 * when the delivery never got a response.
 */
responseHeaders?: { [key in string]: string }, 
/**
 * Receiver response body as text, serialized as `responseBody` — a string, not parsed JSON.
 */
responseBody: string, 
/**
 * Semantics TBC — see the `durationMs` sibling in
 * shittim-chest packages/core/src/proxy/handlers/channels.rs:1055, the only place the
 * unit is named.
 */
duration: bigint, 
/**
 * Whether the receiver accepted the delivery; the live ingress log derives it from the
 * signature check.
 */
success: boolean, 
/**
 * RFC 3339 timestamp of the attempt, serialized as `deliveredAt`.
 */
deliveredAt: string, };

/**
 * One inbound webhook endpoint this instance exposes (`GET /api/webhook`). An entry
 * exists only for a provider whose signing secret is configured, plus the
 * always-present `custom` catch-all.
 */
export type WebhookInfoItem = { 
/**
 * Provider key: `github`, `gitlab`, `gitee` or `custom`.
 */
name: string, 
/**
 * Absolute ingress URL built from the configured public webhook base (`{base}/{name}`);
 * the `custom` entry keeps a `{name}` placeholder for the caller to fill in.
 */
url: string, 
/**
 * Provider event names the endpoint accepts (`push`, `pull_request`, `issues`, …);
 * the `custom` endpoint advertises `any`.
 */
events: Array<string>, };

/**
 * One outbound webhook subscription (`admin.webhooks.*`) as the admin console reads it
 * back, with its signing secret masked.
 */
export type WebhookItem = { 
/**
 * Subscription id (UUID string) that delivery records reference as `webhookId`.
 */
id: string, 
/**
 * Operator-assigned name of the subscription.
 */
name: string, 
/**
 * Target URL deliveries are posted to.
 */
url: string, 
/**
 * Platform tag the subscription routes for; free-form string.
 */
platform: string, 
/**
 * HMAC-SHA256 signing secret reduced to `****` plus its last 4 characters (`****` alone
 * for short secrets) — the stored secret is never echoed.
 */
secret: string, 
/**
 * Event names the subscription fires on; an empty array is served when the row stores none.
 */
events: Array<string>, 
/**
 * Subscription status string (`active`, `disabled`, …) exactly as stored.
 */
status: string, 
/**
 * RFC 3339 time of the last delivery attempt, serialized as `lastDeliveryAt`; omitted
 * (not null) when none has happened.
 */
lastDeliveryAt?: string, 
/**
 * RFC 3339 creation timestamp, serialized as `createdAt`.
 */
createdAt: string, 
/**
 * RFC 3339 last-update timestamp, serialized as `updatedAt`.
 */
updatedAt: string, };

/**
 * Reply of the inbound-webhook listing: every endpoint the instance currently accepts.
 */
export type WebhookListResponse = { 
/**
 * Available endpoints, in provider order (github, gitlab, gitee, then custom).
 */
webhooks: Array<WebhookInfoItem>, };

/**
 * Roster row of one editor/agent workspace session, as `workspace.createSession` echoes it
 * and as the workspace registry reads it back.
 */
export type WorkspaceSessionResponse = { 
/**
 * Session id (the workspace UUID as a string); every cursor and heartbeat call carries it.
 */
workspace_id: string, 
/**
 * Absolute path of the workspace root on the machine that opened the session.
 */
workspace_path: string, 
/**
 * Editor or agent that owns the session (`vscode`, `neovim`, …).
 */
editor_name: string, 
/**
 * Version string of that editor build, used to spot outdated extensions.
 */
editor_version: string, 
/**
 * Branch checked out in the workspace, as reported when the session connected.
 */
git_branch: string, 
/**
 * Latest cursor snapshot; omitted (not null) until the client has reported one.
 */
cursor?: CursorState, 
/**
 * RFC 3339 time the session was created.
 */
connected_at: string, 
/**
 * RFC 3339 time of the last heartbeat; a stale value is what marks the session offline.
 */
last_heartbeat: string, };
