// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Named parameter schema for one API endpoint.
 */
export type MddApiSchema = { 
/**
 * Endpoint / schema name, e.g. `"submit"`.
 */
name: string, 
/**
 * Accepted parameters.
 */
params: Array<MddParam>, };

/**
 * One node of the model component DAG.
 */
export type MddComponent = { 
/**
 * Unique component id within the descriptor.
 */
id: string, 
/**
 * What role the component plays.
 */
kind: MddComponentKind, 
/**
 * Architecture hint, e.g. `"transformer-encoder"`.
 */
arch?: string, 
/**
 * DAG edges: ids of components this one depends on (upstream).
 */
dependencies: Array<string>, 
/**
 * Input contracts accepted by this component.
 */
inputs: Array<MddIoContract>, 
/**
 * Output contracts produced by this component.
 */
outputs: Array<MddIoContract>, 
/**
 * Runtimes available for this component (best-effort ordering).
 */
runtimes: Array<MddRuntime>, };

/**
 * The role a component plays inside a generative pipeline.
 */
export type MddComponentKind = "encoder" | "dit" | "vae" | "decoder" | "tokenizer" | "other";

/**
 * Deployment plan: pipeline stages plus the exposed inference API.
 */
export type MddDeploy = { 
/**
 * Ordered pipeline stages.
 */
pipeline: Array<MddPipelineStage>, 
/**
 * Inference API wiring.
 */
api: MddDeployApi, };

/**
 * Inference API exposed by the deployment.
 */
export type MddDeployApi = { 
/**
 * Task the API implements.
 */
task: MddTaskKind, 
/**
 * Submit request schema.
 */
submit: MddApiSchema, 
/**
 * Result response schema.
 */
result: MddApiSchema, };

/**
 * One deployment tier — a hardware / placement strategy for the whole model.
 */
export type MddDeployTier = { 
/**
 * Tier id, e.g. `"cloud-api"`, `"48gb-native"`.
 */
id: string, 
/**
 * Engines used by this tier.
 */
engines: Array<MddEngine>, 
/**
 * Quantization ids this tier is known to fit.
 */
quantizations: Array<string>, 
/**
 * Where the tier runs.
 */
placement: MddPlacement, 
/**
 * Minimum total VRAM in GB.
 */
min_vram_gb?: number, 
/**
 * Minimum GPU count.
 */
min_gpus?: number, 
/**
 * Free-form notes.
 */
notes?: string, };

/**
 * Top-level model deployment descriptor — the root of an MDD v1 document.
 */
export type MddDescriptor = { 
/**
 * Schema version of this descriptor (currently `1`).
 */
schema_version: number, 
/**
 * Model identity and architecture summary.
 */
model: MddModel, 
/**
 * Components that make up the model, as a DAG (see `dependencies`).
 */
components: Array<MddComponent>, 
/**
 * Inference pipeline and API wiring.
 */
deploy: MddDeploy, 
/**
 * Scale / sizing estimation for capacity planning.
 */
scale: MddScale, };

/**
 * Data type of an IO contract.
 */
export type MddDtype = "f32" | "f16" | "bf16" | "i8" | "u8" | "token_ids" | "text" | "other";

/**
 * Serving engine for a runtime.
 */
export type MddEngine = "llama_cpp" | "vllm" | "sglang" | "candle" | "ollama" | "cloud" | "external_api" | "native";

/**
 * Entry kind for a runtime.
 */
export type MddEntryKind = "file" | "url" | "registry" | "gguf";

/**
 * Minimum hardware requirement for a local runtime.
 */
export type MddHardwareRequirement = { 
/**
 * Minimum VRAM in MB.
 */
min_vram_mb?: bigint, 
/**
 * Minimum system RAM in MB.
 */
min_ram_mb?: bigint, 
/**
 * Minimum GPU count.
 */
min_gpus?: number, 
/**
 * CUDA compute capability, e.g. `"8.0"`.
 */
compute_capability?: string, };

/**
 * An input or output contract of a component.
 */
export type MddIoContract = { 
/**
 * Contract name, e.g. `"prompt"`, `"latents"`.
 */
name: string, 
/**
 * Data type of the tensor / value.
 */
dtype: MddDtype, 
/**
 * Optional shape description, e.g. `"[1, 4096]"`, `"token_ids"`.
 */
shape?: string, };

/**
 * Model identity block of an MDD descriptor.
 */
export type MddModel = { 
/**
 * Unique model id, e.g. `"demo-h3-mini"`.
 */
id: string, 
/**
 * Human-readable display name.
 */
name: string, 
/**
 * Model family / lineage, e.g. `"demo-dit"`.
 */
family?: string, 
/**
 * Architecture identifier, e.g. `"dit"`, `"llama"`.
 */
architecture: string, 
/**
 * Free-form description.
 */
description?: string, };

/**
 * A single parameter of an API schema.
 */
export type MddParam = { 
/**
 * Parameter name.
 */
name: string, 
/**
 * Type descriptor, e.g. `"string"`, `"integer"`, `"float"`.
 */
dtype: string, 
/**
 * Whether the parameter must be supplied.
 */
required: boolean, 
/**
 * Default value when omitted.
 */
default?: unknown, 
/**
 * Free-form description.
 */
description?: string, };

/**
 * When a pipeline stage runs.
 */
export type MddPipelinePhase = "pre" | "iterative" | "post";

/**
 * One stage of the inference pipeline.
 */
export type MddPipelineStage = { 
/**
 * Unique stage id within the pipeline.
 */
id: string, 
/**
 * When the stage runs.
 */
phase: MddPipelinePhase, 
/**
 * Cache key template (deterministic stages only).
 */
cache_key?: string, 
/**
 * Free-form description.
 */
description?: string, };

/**
 * Where a deploy tier runs.
 */
export type MddPlacement = "single_card" | "multi_card" | "cloud" | "external";

/**
 * A quantization variant of a runtime.
 */
export type MddQuantization = { 
/**
 * Quantization id, e.g. `"q4_k_m"`.
 */
id: string, 
/**
 * Bit width per weight.
 */
bits: number, 
/**
 * Approximate size relative to the FP16 baseline (e.g. `0.25`).
 */
size_multiplier?: number, 
/**
 * Free-form notes.
 */
notes?: string, };

/**
 * One concrete way to serve a component.
 */
export type MddRuntime = { 
/**
 * Serving engine.
 */
engine: MddEngine, 
/**
 * Where the weights / entrypoint live.
 */
entry: MddRuntimeEntry, 
/**
 * Engine features this runtime relies on (e.g. `["cuda", "flash-attn"]`).
 */
features: Array<string>, 
/**
 * Quantization variants this runtime supports.
 */
quantizations: Array<MddQuantization>, 
/**
 * Hardware requirements (local runtimes only).
 */
hardware?: MddHardwareRequirement, 
/**
 * Lifecycle status of this runtime.
 */
status: MddRuntimeStatus, };

/**
 * Where a runtime's entrypoint (weights or endpoint) lives.
 */
export type MddRuntimeEntry = { 
/**
 * Entry kind.
 */
kind: MddEntryKind, 
/**
 * Path / URL / registry reference, depending on `kind`.
 */
path: string, 
/**
 * SHA-256 checksum of the artifact (file downloads only).
 */
sha256?: string, 
/**
 * Artifact size in bytes (file downloads only).
 */
size_bytes?: bigint, };

/**
 * Lifecycle status of a runtime.
 */
export type MddRuntimeStatus = "ready" | "planned" | "unavailable";

/**
 * Scale / sizing estimation for capacity planning.
 */
export type MddScale = { 
/**
 * Total parameter count in billions.
 */
total_parameters_b?: number, 
/**
 * Weight storage estimate.
 */
weights: MddScaleWeights, 
/**
 * Supported quantization variants.
 */
quantization: Array<MddQuantization>, 
/**
 * Activation memory estimate.
 */
activation: MddScaleActivation, 
/**
 * Context / KV-cache estimate.
 */
context: MddScaleContext, 
/**
 * Throughput estimate.
 */
throughput: MddScaleThroughput, 
/**
 * Deployment tiers (cheapest-first ordering is conventional).
 */
tiers: Array<MddDeployTier>, };

/**
 * Activation memory estimate.
 */
export type MddScaleActivation = { 
/**
 * Peak activation memory in GB.
 */
peak_gb?: number, 
/**
 * Activation bytes per token.
 */
bytes_per_token?: number, };

/**
 * Context / KV-cache estimate.
 */
export type MddScaleContext = { 
/**
 * Maximum context length in tokens.
 */
max_tokens?: number, 
/**
 * KV-cache bytes per token.
 */
kv_cache_bytes_per_token?: number, };

/**
 * Throughput estimate.
 */
export type MddScaleThroughput = { 
/**
 * Tokens per second.
 */
tokens_per_second?: number, 
/**
 * Requests per second.
 */
requests_per_second?: number, 
/**
 * End-to-end latency in milliseconds.
 */
latency_ms?: number, };

/**
 * Weight storage estimate.
 */
export type MddScaleWeights = { 
/**
 * Total weight size in GB.
 */
size_gb?: number, 
/**
 * Storage format, e.g. `"safetensors"`, `"gguf"`.
 */
format?: string, };

/**
 * Task kind implemented by the inference API.
 */
export type MddTaskKind = "text_generation" | "embedding" | "image_generation" | "video_generation" | "audio_generation" | "other";
