// Vendored snapshot of packages/plana/bindings/ops.ts (ts-rs generated) so the
// published npm tarball carries the deferred-operation wire shapes: npm `files`
// cannot reach a sibling package's directory, exactly as with
// `protocol-core-httpTypes.ts` above. Re-sync after `cargo test -p plana`
// whenever the deferred types in packages/plana/src/jsonrpc/deferred.rs or the
// JSON-RPC error object change.
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * Immediate answer of a handler that switched to deferred mode.
 *
 * `expires_in` is the **remaining** validity in seconds measured from
 * creation, not from the moment of serialization — a client that reconnects
 * half-way through the window sees the shrunk remainder.
 */
export type DeferredOpCreated = { 
/**
 * The opaque client-facing reference.
 */
op_id: DeferredOpRef, 
/**
 * Remaining validity of `op_id`, in seconds.
 */
expires_in: bigint, };

/**
 * Current state of a deferred operation, as answered by `ops.result`.
 *
 * Exactly one of `result` / `error` is present once the status is terminal;
 * both are absent while the status is `pending`.
 */
export type DeferredOpOutcome = { 
/**
 * The collected reference (echoed so a multiplexed client can route).
 */
op_id: DeferredOpRef, 
/**
 * Current lifecycle status.
 */
status: DeferredOpStatus, 
/**
 * The method whose handler deferred the work — audit and debugging
 * surface; the outcome is meaningless without knowing what it is a
 * result of.
 */
method: string, 
/**
 * Remaining validity of this entry, in seconds. Once it reaches zero the
 * entry is gone and the id answers `-32053`.
 */
expires_in: bigint, 
/**
 * Whether a cancellation was requested through `ops.cancel` while the
 * operation was still pending (advisory — the worker may not honour it).
 */
cancel_requested: boolean, 
/**
 * Present iff `status == completed`.
 */
result?: JsonValue | null, 
/**
 * Present iff `status == failed`.
 */
error?: JsonRpcError | null, };

/**
 * Client-facing reference to a deferred operation.
 *
 * Opaque, unguessable and stable for the whole validity window: a client
 * that reconnects (or that hands the id to a different client, e.g. a
 * browser tab resuming a rescue session) can collect with it. Treat it as a
 * bearer value — whoever holds it can read the outcome.
 */
export type DeferredOpRef = string;

/**
 * `ops.settled` notification params.
 *
 * Advisory only: it says *that* an operation settled, never *what* it
 * produced — the client still calls `ops.result` to collect the payload.
 * That keeps a single authoritative collection path.
 */
export type DeferredOpSettledParams = { 
/**
 * The reference that settled.
 */
op_id: DeferredOpRef, 
/**
 * Its new status.
 */
status: DeferredOpStatus, };

/**
 * Lifecycle of a deferred operation.
 *
 * A cancellation request does **not** add a state: `ops.cancel` only sets a
 * flag the worker may observe, and a cancelled operation settles as
 * [`DeferredOpStatus::Failed`] with `-32055` (`error_codes::OPS_CANCELLED`)
 * when the worker honours it. That keeps the state machine to the three
 * states a client actually has to handle.
 */
export type DeferredOpStatus = "pending" | "completed" | "failed";

/**
 * The JSON-RPC 2.0 error object. Also generated into the TypeScript
 * bindings, because it is the payload a client must parse out of a
 * deferred outcome (`plana::jsonrpc::deferred`).
 */
export type JsonRpcError = { code: bigint, message: string, data?: JsonValue, };

/**
 * `ops.cancel` params.
 */
export type OpsCancelParams = { 
/**
 * The reference to ask cancellation for.
 */
op_id: DeferredOpRef, };

/**
 * `ops.cancel` result.
 */
export type OpsCancelResult = { 
/**
 * The reference the request was recorded for.
 */
op_id: DeferredOpRef, 
/**
 * The status observed at request time.
 */
status: DeferredOpStatus, 
/**
 * True when the request was recorded for a still-pending operation (so
 * the worker can observe it); false when the operation had already
 * settled and there was nothing to cancel.
 */
cancel_requested: boolean, };

/**
 * `ops.result` params.
 */
export type OpsResultParams = { 
/**
 * The reference to collect.
 */
op_id: DeferredOpRef, };
