[workspace]
resolver = "2"
members = ["packages/protocol"]

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.85"
authors = ["langyo <langyo.china@gmail.com>"]
license = "BUSL-1.1"
repository = "https://github.com/celestia-island/arona"

[profile.dev]
debug = 1
incremental = true

[profile.release]
opt-level = 3
lto = "thin"
