// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConsultationStatus } from "../enums";

export type AgentIntegrityParams = { verbose: boolean | null, };

export type AskResult = { consultation_id: string, question: string, context: string, options: Array<string>, recommended: string, status: ConsultationStatus, };

export type AuditAlignmentParams = { target: string, device_data?: { [key in string]: string } | null, };

export type AuditAlignmentResult = { audit_id: string, target: string, total_rules: number, passed: number, failed: number, findings: Array<AuditFinding>, };

export type AuditFinding = { rule_id: string, severity: string, description: string, evidence: string, recommendation: string, };

export type AuditLegalityParams = { target: string, jurisdiction: string | null, device_data?: { [key in string]: string } | null, };

export type AuditLegalityResult = { audit_id: string, target: string, jurisdiction: string, total_requirements: number, compliant: number, non_compliant: number, findings: Array<AuditFinding>, };

export type BlockToolParams = { agent: string, tool: string, reason: string | null, };

export type CheckResultItem = { standard: string, status: string, message: string, details?: string | null, };

export type ComplianceReportParams = { standard_id: string, check_results: Array<CheckResultItem>, device_id: string | null, summary: string | null, mode: string | null, };

export type ComplianceReportToolResult = { report_id: string, standard_id: string, device_id: string | null, overall_status: string, summary: ComplianceSummary, details: Array<ReportDetail>, generated_at: string, };

export type ComplianceRule = { id: string, standard: string, clause: string, description: string, check_type: string, parameters: Record<string, unknown>, severity: string, };

export type ComplianceSummary = { total_rules: number, passed: number, failed: number, critical_failures: number, high_failures: number, medium_failures: number, };

export type InspectToolCallParams = { agent: string, tool: string, session_id: string | null, };

export type ManageSensitivityRulesParams = { action: string, rules: Array<SensitivityRule> | null, };

export type ReplyResult = { consultation_id: string, answer: string, selected_options: Array<string>, status: ConsultationStatus, };

export type ReportDetail = { rule_id: string, clause: string, description: string, status: string, severity: string, deviation: number | null, recommendation: string, };

export type ReportHumanParams = { summary: string, body: string | null, text: string | null, mode: string | null, };

export type ReportHumanResult = { report_id: string, report_type: string, content: Record<string, unknown>, consultation_id: string | null, status: ConsultationStatus, created_at: string, };

export type RuleCheckResult = { rule_id: string, clause: string, description: string, status: string, actual_value: Record<string, unknown> | null, expected: Record<string, unknown> | null, deviation: number | null, severity: string, };

export type SecurityAuditParams = { deep: boolean | null, };

export type SecurityStatusParams = Record<symbol, never>;

export type SecuritySuggestionsParams = Record<symbol, never>;

export type SensitivityRule = { tool: string, agent?: string | null, sensitivity: string, reason?: string | null, };

export type SetNetworkPolicyParams = { allow_hosts: Array<string> | null, allow_cidrs: Array<string> | null, block_private: boolean | null, block_metadata: boolean | null, };

export type SetRiskThresholdParams = { level: string, };

export type SetSecurityPolicyParams = { emergency_lockdown: boolean | null, audit_only: boolean | null, };

export type StandardCheckParams = { standard_id: string, device_data?: { [key in string]: string } | null, };

export type StandardCheckResult = { standard_id: string, total_rules: number, passed: number, failed: number, not_applicable: number, results: Array<RuleCheckResult>, overall_status: string, };

export type StandardRegisterResult = { standard_id: string, rules_registered: number, };

export type UnblockToolParams = { agent: string, tool: string, };
