// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Backend build profile.
 */
export type BackendKind = "dev" | "nightly" | "prod" | "mock";

/**
 * Connection status of a dependency, as reported in health payloads.
 */
export type ConnectionStatus = { connected: boolean, latency: bigint, lastCheck: string, };

export type CreatedResponse = { created: Array<string>, };

export type DeletedResponse = { deleted: bigint, };

export type ErrorResponse = { error: string, message?: string, };

export type GrantItem = { id: string, scope: string, user_id: string | null, group_id: string | null, permission: string, resource_id: string | null, granted: boolean, created_at: string, };

export type GrantListResponse = { grants: Array<GrantItem>, };

/**
 * Standard /api/health response for all plana backends.
 */
export type HealthResponse = { status: ServiceStatus, version: string, kind: BackendKind, uptime: bigint, network: NetworkInfo, build_hash: string | null, engine_version: string | null, };

export type IdResponse = { id: string, };

export type MyPermissions = { role: string, permissions: Array<string>, };

/**
 * Network context from the incoming request.
 */
export type NetworkInfo = { transport: string, region: string, asn: number | null, };

export type OAuthProvider = { provider: string, client_id: string, client_secret_masked: string, public_domain: string, enabled: boolean, };

export type OkIdResponse = { ok: boolean, id: string, };

export type OkMessageResponse = { ok: boolean, message: string, };

export type OkResponse = { ok: boolean, };

export type PermissionsResponse = { role: string, permissions: Array<string>, };

export type RbacGroup = { id: string, name: string, description: string, member_count: number, created_at: string, updated_at: string, };

export type RbacGroupsResponse = { groups: Array<RbacGroup>, };

export type RbacUser = { id: string, username: string, email: string, display_name: string, avatar_url: string | null, is_active: boolean, is_admin: boolean, role: string, tier: string, created_at: string, };

export type RbacUsersResponse = { users: Array<RbacUser>, };

export type ReadinessResponse = { status: string, database: boolean, };

/**
 * Service health status. Serde uses lowercase so JSON returns "ok" etc.
 */
export type ServiceStatus = "ok" | "degraded" | "unhealthy";

export type StatusResponse = { status: string, agent_id?: string, platform?: string, id?: string, plugin_id?: string, };
