// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Result of one dependency check reported by `/readyz`.
 */
export type DependencyCheck = { 
/**
 * Human-readable dependency name, e.g. `database`, `scepter_socket`,
 * `first_station_poll`.
 */
name: string, 
/**
 * Whether the dependency is currently healthy.
 */
ok: boolean, 
/**
 * Optional detail / error message when `ok` is false.
 */
detail?: string, };

/**
 * Body of `Lifecycle.Drain` — ask an instance to enter graceful shutdown.
 */
export type DrainRequest = { 
/**
 * Override the default drain timeout (seconds). `None` = use instance default.
 */
timeout_secs?: number, 
/**
 * Free-form reason (e.g. `rolling_update`, `manual`, `leader_demote`).
 */
reason?: string, };

/**
 * Reply to `Lifecycle.Drain`.
 */
export type DrainResponse = { 
/**
 * Whether the instance accepted the drain request.
 */
accepted: boolean, 
/**
 * Whether it is now draining (true once accepted).
 */
draining: boolean, };

/**
 * High-level lifecycle state of an instance, observable over the wire.
 */
export type DrainState = "active" | "draining" | "reloading";

/**
 * Liveness probe payload — the body of `GET /healthz`.
 *
 * Intentionally minimal: if the process can answer at all, it is alive.
 */
export type HealthStatus = { 
/**
 * Always true when the endpoint answers (else the probe fails).
 */
alive: boolean, 
/**
 * OS process id of the server.
 */
pid: number, 
/**
 * Seconds since the instance started.
 */
uptime_secs: bigint, 
/**
 * Build version string.
 */
version: string, };

/**
 * One entry in the shared instance registry.
 */
export type InstanceInfo = { 
/**
 * Stable unique id of this instance (uuid recommended).
 */
instance_id: string, 
/**
 * Logical group this instance belongs to (e.g. service name).
 */
group: string, 
/**
 * Current role.
 */
role: InstanceRole, 
/**
 * Deployment generation (incremented on each rolling update).
 */
generation: bigint, 
/**
 * ISO-8601 timestamp at which the instance started.
 */
started_at: string, 
/**
 * Optional endpoint (host:port or socket path) clients can reach it at.
 */
endpoint?: string, };

/**
 * Role of an instance within its group.
 *
 * - For Subsystem A (Replica): peers are `Active`; the one being retired is
 *   `Draining`.
 * - For Subsystem B (Leader/Follower): encoded separately via [`LeaderRole`].
 */
export type InstanceRole = "active" | "draining";

/**
 * Announcement of a lease acquisition or transfer (method `LEADER_ANNOUNCE`).
 */
export type LeaderAnnounce = { 
/**
 * Group/device identity this leadership applies to (shared by leader & follower).
 */
node_id: string, 
/**
 * Id of the instance now holding the lease.
 */
leader_instance_id: string, 
/**
 * Monotonic term/generation of this leadership, to reject stale announcements.
 */
term: bigint, 
/**
 * ISO-8601 timestamp at which the lease was acquired.
 */
acquired_at: string, 
/**
 * Lease time-to-live in seconds; followers promote only after it elapses.
 */
lease_ttl_secs: number, };

/**
 * Leader/follower role for Subsystem B (active-passive HA).
 */
export type LeaderRole = "leader" | "follower";

/**
 * Readiness probe payload — the body of `GET /readyz`.
 *
 * The `draining` flag is the central rolling-update signal: a load balancer
 * or orchestrator routes new traffic only to instances whose `ready && !draining`.
 */
export type ReadyStatus = { 
/**
 * Overall readiness: true only when not draining AND every dependency ok.
 */
ready: boolean, 
/**
 * True while the instance is draining (graceful shutdown) or reloading.
 */
draining: boolean, 
/**
 * Per-dependency checks that contributed to `ready`.
 */
dependencies: Array<DependencyCheck>, 
/**
 * Deployment generation this instance belongs to (rolling-update bookkeeping).
 */
generation?: bigint, };

/**
 * When to restart a worker after it exits (OTP vocabulary).
 */
export type RestartPolicy = "permanent" | "transient" | "temporary";

/**
 * Snapshot of one worker, reported over `Worker.Status`.
 */
export type WorkerInfo = { 
/**
 * Worker identifier (unique within its supervisor).
 */
id: string, 
/**
 * Resource kind this worker holds (e.g. `modbus`, `s7comm`, `cosmos`, `pglite_proxy`).
 */
kind: string, 
/**
 * Current lifecycle state.
 */
status: WorkerStatus, 
/**
 * Configured restart policy.
 */
restart_policy: RestartPolicy, 
/**
 * Number of (re)starts observed by the supervisor.
 */
restart_count: number, 
/**
 * Last error detail, if the worker is `Failed`.
 */
last_error?: string, };

/**
 * Lifecycle state of one supervised worker process (the FSM in the design).
 */
export type WorkerStatus = "starting" | "running" | "stopped" | "failed";
