// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type NoaAuthRequestParams = { workspace_id: string, branches: Array<string>, suggested_branch: string, reason: string, };

export type NoaAuthResponseParams = { workspace_id: string, selected_branch: string, branch_base?: string, approved: boolean, };

export type NoaEvent = { event_id: string, event_type: string, timestamp: string, file_path?: string, content_hash?: string, metadata?: unknown, };

export type NoaEventSyncAckParams = { workspace_id: string, last_event_id: string, };

export type NoaEventSyncParams = { workspace_id: string, events: Array<NoaEvent>, direction?: string, };

export type NoaHandshakeResponseParams = { workspace_id: string, repo_id: string, current_branch: string, noa_initialized: boolean, gitignore_updated: boolean, };

export type NoaReadyParams = { workspace_id: string, branch: string, snapshot_id: string, };

export type RequestNoaHandshakeParams = { workspace_id: string, remote_name: string, remote_path: string, };
