// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Dashboard layout — a collection of views arranged in a grid.
 */
export type DashboardLayout = { 
/**
 * Workspace ID this dashboard belongs to.
 */
workspace_id: string, 
/**
 * Dashboard name.
 */
name: string, 
/**
 * All view instances in this dashboard.
 */
views: Array<ViewInstance>, 
/**
 * Grid columns count (0 = auto).
 */
grid_columns: number, };

/**
 * Push a dashboard layout update to connected clients.
 */
export type DashboardLayoutPushParams = { layout: DashboardLayout, };

/**
 * View data update — incremental data push for a specific view.
 */
export type ViewDataPushParams = { 
/**
 * Target view ID.
 */
view_id: string, 
/**
 * Data payload (format depends on ViewKind).
 */
data: Record<string, unknown>, 
/**
 * Whether this is a full replacement or incremental update.
 */
full_replace: boolean, };

/**
 * A view instance — one panel in the dashboard.
 */
export type ViewInstance = { 
/**
 * Unique view ID within the workspace.
 */
view_id: string, 
/**
 * What kind of renderer to use.
 */
kind: ViewKind, 
/**
 * Display title.
 */
title: string, 
/**
 * Data source identifier — what the view is bound to.
 * Examples: "industrial:station:19", "chat:conversation:abc",
 * "kanban:project:xyz", "media:flow:comfyui"
 */
data_source: string, 
/**
 * View-specific configuration (JSON, interpreted by the renderer).
 */
config: Record<string, unknown>, 
/**
 * Layout position (grid area, tab order, etc.).
 */
layout?: ViewLayout, };

/**
 * View type identifier — determines which frontend renderer handles the view.
 */
export type ViewKind = "industrial_scada" | "chat" | "kanban" | "gantt" | "data_table" | "media_flow" | "file_explorer" | "custom";

/**
 * Layout descriptor for a view within the dashboard grid.
 */
export type ViewLayout = { 
/**
 * Grid column start (1-based).
 */
col: number, 
/**
 * Grid row start (1-based).
 */
row: number, 
/**
 * Column span.
 */
col_span: number, 
/**
 * Row span.
 */
row_span: number, 
/**
 * Minimum width in pixels.
 */
min_width?: number, 
/**
 * Minimum height in pixels.
 */
min_height?: number, };
