// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BaseAckParams = { message_id: string, };

export type BaseErrorParams = { code: string, message: string, };

export type BaseHeartbeatParams = { timestamp: bigint, };
