// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ClientCapability = "file_relay" | "terminal" | "screen_capture" | "noa_workspace";

export type ClientNodeInfo = { hostname: string, os: string, workspace_root?: string, user_id?: string, };

export type ConnectHandshakeParams = {
/**
 * Handshake wire-protocol version advertised by the client. Defaults to
 * [`HANDSHAKE_VERSION`] when absent (backward-compatible with old clients).
 */
protocol_version: number, token: string, session_id?: string, capabilities: Array<ClientCapability>, node_info?: ClientNodeInfo,
/**
 * Stringified UUID — kept as a string on the wire so consumers
 * don't need a UUID parser to round-trip the JSON-RPC payload.
 */
workspace_id?: string, };

export type HandshakeAckParams = { ok: boolean, error?: string, };

export type PingParams = { timestamp: bigint, };

export type ScepterIdentityParams = { device_id: string, };
