// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type HandshakeAckParams = { ok: boolean, error?: string, };

export type PingParams = { timestamp: bigint, };
