// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Agent = "HapLotes" | "SkoPeo" | "HubRis" | "KaLos" | "NeiKos" | "SkeMma" | "ApoRia" | "EleOs" | "Epieikeia" | "OreXis" | "PhiLia" | "PoleMos" | "WebAutomation";

export type AgentBadge = string;

export type AgentErrorCode = "model_no_providers" | "model_no_models" | "model_tier_mismatch" | "model_all_excluded" | "model_env_incomplete" | "model_selection_retry_exhausted" | "model_no_capable_model" | "llm_call_failed" | "llm_empty_response" | "llm_rate_limited" | "llm_auth_failed" | "llm_timeout" | "cosmos_no_connection" | "cosmos_tool_failed" | "cosmos_local_unavailable" | "chain_max_depth" | "chain_cycle" | "chain_failed" | "skill_failed" | "skill_empty_output" | "skill_missing_report";

export type AgentStatus = "Initializing" | "Online" | "Busy" | "Offline" | "Error";

export type CompletionOutcome = "None" | "Reported" | "Failed";

export type ContainerStatus = "created" | "running" | "paused" | "restarting" | "removing" | "exited" | "dead" | "unknown";

export type EmbeddingModel = "OpenAiSmall" | "OpenAiLarge" | "OpenAiAda" | "Custom";

export type KnowledgeBaseStatus = "Uninitialized" | "Indexing" | "Ready" | "Error";

export type LlmStream = { segments: Array<StreamSegment>, };

export type ModelTier = "Deep" | "Normal" | "Basic";

export type PeriodType = "Hour5" | "Day7" | "Month1";

/**
 * Selection semantics for an inquiry (`report_type: "query"`) report's
 * `preset_options`. Defaults to `Single` when omitted.
 */
export type ReportSelection = "single" | "multiple";

export type ReportType = "query" | "human" | "reply" | "skill_terminal" | "skill_step" | "next_action_fallback" | "chain_max_depth" | "chain_cycle" | "skill_failed" | "skill_empty_output" | "skill_missing_report" | "error" | "system" | "pending";

export type RequestState = "Idle" | "Waiting" | "Streaming" | "Retrying" | "WaitingTool";

export type RetryReason = "EmptyOutput" | "ReportNotCaptured" | { "LlmError": { message: string, } };

export type RouteInfo = { direction: string, target: string, target_token?: string, };

export type SkillStage = { "Started": string } | { "Done": string } | { "Complete": string } | { "Failed": string } | { "ToolCall": string } | { "Retrying": [string, number, number, RetryReason | null] } | { "TryingModel": [string, string] } | { "ModelFailed": [string, string, string] } | { "Nudging": string };

export type StreamChunkKind = "Text" | "Thinking" | "DeepThinking";

/**
 * The LIVE-STREAM wire mirror of `plana_text::StreamSegment` — the shape
 * the WS event plane serializes (see `ws/core.ts`).
 *
 * ⚠️ Deliberately NOT identical to the runtime enum: the runtime one
 * gained `Input` (plana #420) for run-record capture — the composed
 * prompt side of a skill invocation. It is CALLER-recorded at settle
 * time and never streams live, so this wire enum has no `Input` arm.
 * (One smaller typing difference is intentional too: the runtime types
 * `call_id` as `Uuid` where this wire shape carries `call_id: String`;
 * the optional `ts` stamp is the same on both.) Do
 * NOT use this type to deserialize a stored run-record stream
 * (`task_run_records.stream`): it hard-fails on the `Input` tag. Parse
 * those with `plana_text::StreamSegment` (or the consumer's own adapter,
 * as the chest webui does). The divergence is pinned by
 * `wire_stream_segment_mirrors_live_events_only` below — adding `Input`
 * here must be a deliberate decision that flips that test.
 */
export type StreamSegment = { "Text": { text: string, message_id?: string, 
/**
 * Wall-clock ms epoch at the segment's last activity — mirrors
 * plana_text's segment stamp (plana #407) so the two shapes stay
 * aligned; absent on legacy/hand-built values.
 */
ts?: number, } } | { "Thinking": { text: string, message_id?: string, ts?: number, } } | { "DeepThinking": { text: string, message_id?: string, ts?: number, } } | { "ToolCall": { tool_name: string, call_id: string, params: unknown, agent_type?: string, message_id?: string, ts?: number, } } | { "ToolResult": { tool_name: string, call_id: string, success: boolean, data: unknown, duration_ms?: bigint, agent_type?: string, message_id?: string, ts?: number, } };

export type StructuredAgentError = { code: AgentErrorCode, detail?: string, context: { [key in string]: string }, };

export type TaskStatus = "not_started" | "in_progress" | "paused" | "completed" | "failed" | "warning" | { "waiting": { deadline: string, handle: string, } };

export type WorkStatus = "Thinking" | "StreamingResponse" | { "Executing": { skill_name: string, } } | { "Retrying": { retry_count: number, max_retries: number, } } | "Nudging" | "Completed" | "RequestFailed" | "Failed" | "ToolLoopTerminated" | "CallingTool";

export type YoloTaskTier = "realtime" | "periodic" | "daily" | "strategic";
