// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CustomAgentInfo = { name: string, display_name: string, description: string, skills_count: number, source: string, version?: string, last_updated?: string, };

export type CustomAgentListResponseParams = { agents: Array<CustomAgentInfo>, };

export type Layer2AgentInfo = { name: string, description: string, tool_count: number, skills_count: number, languages: Array<string>, enabled: boolean, };

export type Layer2AgentListResponseParams = { agents: Array<Layer2AgentInfo>, };

export type Layer2AgentSkillsResponseParams = { agent_name: string, skills: Array<Layer2SkillInfo>, };

export type Layer2AgentToolResponseParams = { agent_name: string, tools: Array<Layer2ToolInfo>, };

export type Layer2SkillInfo = { name: string, description: string, languages: Array<string>, references_layer1: Array<string>, references_layer2: Array<string>, related_items: Array<string>, referenced_by_items: Array<string>, };

export type Layer2SkillPromptResponseParams = { agent_name: string, skill: string, lang: string, content: string, name: string, };

export type Layer2ToolInfo = { name: string, description: string, languages: Array<string>, references_layer1: Array<string>, references_layer2: Array<string>, related_items: Array<string>, referenced_by_items: Array<string>, };

export type Layer2ToolPromptResponseParams = { agent_name: string, tool: string, lang: string, content: string, name: string, };

export type SubscribeCustomAgentResponseParams = { success: boolean, error?: string, agent?: CustomAgentInfo, skills: Array<string>, permissions: Array<string>, };

export type UnsubscribeCustomAgentResponseParams = { success: boolean, error?: string, };
