// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PrMetadata = { model?: string, input_tokens?: bigint, output_tokens?: bigint, cost_usd?: number, };

export type PrState = "open" | "closed" | "merged";

export type PullRequestDetail = { 
/**
 * Forge-local identifier (GitHub number / self-hosted id).
 */
id: string, number: bigint, title: string, state: PrState, base: string, head: string, url: string, created_at: bigint, body: string, author: string, metadata: PrMetadata, };

export type PullRequestSummary = { 
/**
 * Forge-local identifier (GitHub number / self-hosted id).
 */
id: string, number: bigint, title: string, state: PrState, 
/**
 * Target branch / workspace.
 */
base: string, 
/**
 * Source branch / workspace.
 */
head: string, 
/**
 * Web URL of the PR (empty for the self-hosted store in v1b).
 */
url: string, 
/**
 * Unix seconds.
 */
created_at: bigint, };
