// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One PCM audio block (base64-encoded in JSON payloads).
 */
export type RealtimeAudioChunk = { 
/**
 * MIME type of the payload (e.g. `"audio/pcm"`).
 */
mime: string, 
/**
 * Sample rate in Hz (16 kHz client→model, 24 kHz model→client).
 */
sample_rate: number, 
/**
 * Base64-encoded PCM16 LE audio bytes.
 */
data_base64: string, };

/**
 * Client → gateway realtime events (client-sent).
 *
 * Canonical vendor-neutral tags (see `docs/en/designs/realtime-media.md`);
 * wired as JSON-RPC notifications on the session channel. Binary audio
 * (16 kHz PCM16) travels base64-encoded in `data_base64` (v1) or as WS
 * binary frames announced via the CEP binary-transfer triple (v2).
 */
export type RealtimeClientEvent = { "type": "session.configure", session: RealtimeSessionConfig, } | { "type": "audio.input.append", audio: RealtimeAudioChunk, } | { "type": "audio.input.commit" } | { "type": "audio.input.clear" } | { "type": "video.input.frame", frame: RealtimeVideoFrame, } | { "type": "response.request" } | { "type": "response.cancel" } | { "type": "session.close" };

/**
 * Gateway → client realtime events (server-sent).
 *
 * Canonical vendor-neutral tags (see `docs/en/designs/realtime-media.md`);
 * wired as JSON-RPC notifications on the session channel. Binary audio
 * (24 kHz PCM16) travels base64-encoded in `delta.data_base64` (v1) or as
 * WS binary frames (v2). Clients stop playback on `turn.speech_started`
 * (barge-in) and treat `response.done` as the terminal billing event for
 * one response.
 */
export type RealtimeServerEvent = { "type": "session.created", session: RealtimeSessionConfig, } | { "type": "session.configured", session: RealtimeSessionConfig, } | { "type": "turn.speech_started", audio_start_ms: bigint, } | { "type": "turn.speech_stopped", audio_end_ms: bigint, } | { "type": "response.started", response_id: string, } | { "type": "response.audio.delta", response_id: string, delta: RealtimeAudioChunk, } | { "type": "response.audio.end", response_id: string, } | { "type": "response.transcript.delta", response_id: string, delta: string, } | { "type": "response.text.delta", response_id: string, delta: string, } | { "type": "response.done", response_id: string, usage: RealtimeUsage, } | { "type": "response.video.frame", response_id: string, frame: RealtimeVideoFrame, } | { "type": "error", code: string, message: string, };

/**
 * `session.update` payload — the full realtime session configuration.
 */
export type RealtimeSessionConfig = { model: string, 
/**
 * Output modalities: `["text", "audio"]` or `["text"]`.
 */
modalities: Array<string>, 
/**
 * Voice id for speech output (vendor-specific).
 */
voice?: string, 
/**
 * `"pcm16"` — input audio encoding (16 kHz).
 */
input_audio_format: string, 
/**
 * `"pcm16"` — output audio encoding (24 kHz).
 */
output_audio_format: string, 
/**
 * System prompt for the session.
 */
instructions?: string, turn_detection?: RealtimeTurnDetection, temperature?: number, };

/**
 * Server-side VAD (voice activity detection) configuration for a realtime
 * session. Mirrors the upstream `turn_detection` payload.
 */
export type RealtimeTurnDetection = { 
/**
 * `"server_vad"` | `"semantic_vad"` | `null` (manual commit).
 */
type?: string, 
/**
 * VAD activation threshold in [-1, 1] (server_vad).
 */
threshold?: number, 
/**
 * Padding to keep before speech onset, ms.
 */
prefix_padding_ms?: number, 
/**
 * Silence duration that ends a user turn, ms (default 800).
 */
silence_duration_ms?: number, 
/**
 * Idle timeout that force-commits the buffer, ms.
 */
idle_timeout_ms?: number, 
/**
 * Semantic VAD: auto-create a response at end of user turn.
 */
create_response?: boolean, 
/**
 * Semantic VAD: interrupt the current response when user speech begins.
 */
interrupt_response?: boolean, };

/**
 * Token usage reported in `response.done` — surface for billing.
 */
export type RealtimeUsage = { input_tokens: bigint, output_tokens: bigint, total_tokens: bigint, };

/**
 * One video frame (image) in a realtime session — e.g. a JPEG frame
 * streamed to the model at ~1 fps, or a generated frame streamed back.
 */
export type RealtimeVideoFrame = { 
/**
 * MIME type (e.g. `"image/jpeg"`).
 */
mime: string, 
/**
 * Monotonic frame sequence number for ordering / dedup.
 */
frame_seq: number, 
/**
 * Base64-encoded image bytes.
 */
data_base64: string, };
