// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One PCM audio block (base64-encoded in JSON payloads).
 */
export type RealtimeAudioChunk = { 
/**
 * MIME type of the payload (e.g. `"audio/pcm"`).
 */
mime: string, 
/**
 * Sample rate in Hz (16 kHz client→model, 24 kHz model→client).
 */
sample_rate: number, 
/**
 * Base64-encoded PCM16 LE audio bytes.
 */
data_base64: string, };

/**
 * Client → gateway realtime events (client-sent).
 *
 * Wired as JSON-RPC notifications on the session channel; binary audio
 * (16 kHz PCM16) travels base64-encoded in `data_base64`.
 */
export type RealtimeClientEvent = { "type": "session_update", session: RealtimeSessionConfig, } | { "type": "input_audio_buffer_append", audio: RealtimeAudioChunk, } | { "type": "input_audio_buffer_commit" } | { "type": "input_audio_buffer_clear" } | { "type": "input_image_buffer_append", frame: RealtimeVideoFrame, } | { "type": "response_create" } | { "type": "response_cancel" } | { "type": "session_stop" };

/**
 * Gateway → client realtime events (server-sent).
 *
 * Wired as JSON-RPC notifications on the session channel; binary audio
 * (24 kHz PCM16) travels base64-encoded in `delta.data_base64`. Clients
 * stop playback on `speech_started` (barge-in) and treat `response_done`
 * as the terminal billing event for one response.
 */
export type RealtimeServerEvent = { "type": "session_created", session: RealtimeSessionConfig, } | { "type": "session_updated", session: RealtimeSessionConfig, } | { "type": "speech_started", audio_start_ms: bigint, } | { "type": "speech_stopped", audio_end_ms: bigint, } | { "type": "response_created", response_id: string, } | { "type": "response_audio_delta", response_id: string, delta: RealtimeAudioChunk, } | { "type": "response_audio_done", response_id: string, } | { "type": "response_audio_transcript_delta", response_id: string, delta: string, } | { "type": "response_text_delta", response_id: string, delta: string, } | { "type": "response_done", response_id: string, usage: RealtimeUsage, } | { "type": "response_video_frame", response_id: string, frame: RealtimeVideoFrame, } | { "type": "error", code: string, message: string, };

/**
 * `session.update` payload — the full realtime session configuration.
 */
export type RealtimeSessionConfig = { model: string, 
/**
 * Output modalities: `["text", "audio"]` or `["text"]`.
 */
modalities: Array<string>, 
/**
 * Voice id for speech output (vendor-specific).
 */
voice?: string, 
/**
 * `"pcm16"` — input audio encoding (16 kHz).
 */
input_audio_format: string, 
/**
 * `"pcm16"` — output audio encoding (24 kHz).
 */
output_audio_format: string, 
/**
 * System prompt for the session.
 */
instructions?: string, turn_detection?: RealtimeTurnDetection, temperature?: number, };

/**
 * Server-side VAD (voice activity detection) configuration for a realtime
 * session. Mirrors the upstream `turn_detection` payload.
 */
export type RealtimeTurnDetection = { 
/**
 * `"server_vad"` | `"semantic_vad"` | `null` (manual commit).
 */
type?: string, 
/**
 * VAD activation threshold in [-1, 1] (server_vad).
 */
threshold?: number, 
/**
 * Padding to keep before speech onset, ms.
 */
prefix_padding_ms?: number, 
/**
 * Silence duration that ends a user turn, ms (default 800).
 */
silence_duration_ms?: number, 
/**
 * Idle timeout that force-commits the buffer, ms.
 */
idle_timeout_ms?: number, 
/**
 * Semantic VAD: auto-create a response at end of user turn.
 */
create_response?: boolean, 
/**
 * Semantic VAD: interrupt the current response when user speech begins.
 */
interrupt_response?: boolean, };

/**
 * Token usage reported in `response.done` — surface for billing.
 */
export type RealtimeUsage = { input_tokens: bigint, output_tokens: bigint, total_tokens: bigint, };

/**
 * One video frame (image) in a realtime session — e.g. a JPEG frame
 * streamed to the model at ~1 fps, or a generated frame streamed back.
 */
export type RealtimeVideoFrame = { 
/**
 * MIME type (e.g. `"image/jpeg"`).
 */
mime: string, 
/**
 * Monotonic frame sequence number for ordering / dedup.
 */
frame_seq: number, 
/**
 * Base64-encoded image bytes.
 */
data_base64: string, };
