// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WebUiControlResponseParams = { command: string, success: boolean, message: string, url?: string, };

export type WebUiStatusParams = { running: boolean, url?: string, container_id?: string, };
