// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The base view a template is built on — the spec arm that must be set.
 */
export type BaseViewKind = "waterfall" | "node-canvas" | "data-grid" | "kanban" | "blank-canvas";

/**
 * The blank-canvas base's spec.
 */
export type BlankCanvasSpec = { 
/**
 * What mounts into the canvas (a renderer id the host resolves).
 */
mount: string, 
/**
 * Optional DOM overlay drawn above the canvas.
 */
overlay?: string, };

/**
 * Camera behaviour of a node canvas.
 */
export type CameraSpec = { 
/**
 * Smallest allowed zoom factor.
 */
min_zoom: number, 
/**
 * Largest allowed zoom factor.
 */
max_zoom: number, 
/**
 * Zoom step as a fraction (0.05 = 5%).
 */
zoom_step?: number, 
/**
 * Whether the camera fits the content on first paint.
 */
fit_on_load: boolean, };

/**
 * How a node canvas draws its layers.
 */
export type CanvasBackend = "svg" | "dom-overlay-svg" | "canvas-edges-dom" | "blank";

/**
 * The chrome a template asks the shell to draw around it.
 */
export type ChromeSpec = { 
/**
 * Docked widgets this view contributes.
 */
docks: Array<DockContribution>, 
/**
 * Whether the shell draws its breadcrumb bar.
 */
breadcrumb: boolean, };

/**
 * The data-grid base's spec.
 */
export type DataGridSpec = { 
/**
 * Field schema ids this grid binds to.
 */
fields: Array<string>, 
/**
 * Whether rows can be edited in place.
 */
editable: boolean, 
/**
 * Optional overlay widget drawn above the grid (trend, alarms).
 */
overlay?: string, };

/**
 * Drag-and-drop behaviour of a kanban.
 */
export type DndSpec = { 
/**
 * Whether cards can move between lanes.
 */
across_lanes: boolean, 
/**
 * Whether cards can be reordered inside a lane.
 */
reorder: boolean, };

/**
 * The plane a dock surface sits on.
 */
export type DockAnchor = "page" | "plane";

/**
 * One dock widget a template hangs.
 */
export type DockContribution = { 
/**
 * Widget id the host resolves.
 */
widget: string, 
/**
 * Where it hangs.
 */
placement: DockPlacement, 
/**
 * Which plane carries it.
 */
anchor: DockAnchor, 
/**
 * Surface finish.
 */
surface: DockSurface, 
/**
 * Stacking order among contributions sharing a placement.
 */
order: number, };

/**
 * Where a dock surface hangs.
 */
export type DockPlacement = "top" | "bottom" | "left" | "right" | "top-left" | "top-right" | "bottom-left" | "bottom-right";

/**
 * The finish of a dock surface.
 */
export type DockSurface = "glass" | "solid";

/**
 * How a waterfall groups its items into buckets (day sections, lanes, …).
 */
export type GroupingSpec = { 
/**
 * Field of the item the bucket key is read from.
 */
field: string, 
/**
 * Whether the buckets are ordered newest-first.
 */
newest_first: boolean, };

/**
 * The kanban base's spec.
 */
export type KanbanSpec = { 
/**
 * Scroll directions the board supports.
 */
axes: ScrollAxes, 
/**
 * Lane definition.
 */
lanes: LaneSpec, 
/**
 * Draggable card kinds, in picker order.
 */
card_kinds: Array<string>, 
/**
 * Drag-and-drop behaviour.
 */
dnd: DndSpec, 
/**
 * Optional windowing for long boards.
 */
windowing?: WindowingSpec, };

/**
 * One lane of a kanban.
 */
export type LaneSpec = { 
/**
 * Field of the item the lane key is read from.
 */
field: string, 
/**
 * Whether the lane header is drawn as a card of its own.
 */
header_is_card: boolean, };

/**
 * The built-in minimap, which is on by default for node canvases.
 */
export type MinimapSpec = { 
/**
 * Whether the minimap is drawn.
 */
enabled: boolean, 
/**
 * Where it is anchored.
 */
placement: DockPlacement, };

/**
 * The node-canvas base's spec.
 */
export type NodeCanvasSpec = { 
/**
 * Which rendering backend draws the layers.
 */
backend: CanvasBackend, 
/**
 * Camera bounds and first-paint behaviour.
 */
camera: CameraSpec, 
/**
 * The minimap, on by default.
 */
minimap?: MinimapSpec, 
/**
 * Node kinds this canvas may render.
 */
node_kinds: Array<string>, 
/**
 * Optional left rail (a node palette).
 */
palette?: string, 
/**
 * Optional right rail (an inspector).
 */
inspector?: string, 
/**
 * Optional auto-layout algorithm id.
 */
auto_layout?: string, };

/**
 * One panel template: identity, presentation and the base view's spec.
 */
export type PanelTemplate = { 
/**
 * Template id — kebab-case, stable across config layers.
 */
id: string, 
/**
 * Display title (the author's language).
 */
title: string, 
/**
 * Optional i18n key; when present the shell translates it instead of
 * using `title`.
 */
title_key?: string, 
/**
 * Optional description.
 */
description?: string, 
/**
 * Optional description i18n key.
 */
description_key?: string, 
/**
 * Render-engine (plugin) id that draws this template.
 */
render_engine: string, 
/**
 * The base view and its configuration.
 */
spec: ViewTemplateSpec, };

/**
 * Which way a kanban scrolls.
 */
export type ScrollAxes = "horizontal" | "vertical" | "both";

/**
 * A template file — the TOML document a workspace or plugin ships.
 */
export type ViewTemplateFile = { 
/**
 * Format version.
 */
version: string, 
/**
 * The templates the file declares.
 */
template: Array<PanelTemplate>, };

/**
 * The spec arm matching a template's base view.
 *
 * Exactly one arm is set — the one named by [`ViewTemplateSpec::base`] —
 * so a reader never has to guess which of the five it is looking at.
 */
export type ViewTemplateSpec = { 
/**
 * The base view this template is drawn on.
 */
base: BaseViewKind, 
/**
 * Set iff `base` is `waterfall`.
 */
waterfall?: WaterfallSpec, 
/**
 * Set iff `base` is `node-canvas`.
 */
node_canvas?: NodeCanvasSpec, 
/**
 * Set iff `base` is `data-grid`.
 */
data_grid?: DataGridSpec, 
/**
 * Set iff `base` is `kanban`.
 */
kanban?: KanbanSpec, 
/**
 * Set iff `base` is `blank-canvas`.
 */
blank_canvas?: BlankCanvasSpec, 
/**
 * Optional chrome (docks, breadcrumb).
 */
chrome?: ChromeSpec, };

/**
 * How a waterfall splits its item stream into columns.
 */
export type WaterfallColumns = { "kind": "single" } | { "kind": "fixed", 
/**
 * Number of columns (>= 1).
 */
count: number, } | { "kind": "adaptive", 
/**
 * Upper bound on the derived column count.
 */
max: number, 
/**
 * Minimum column width in pixels.
 */
min_width: number, };

/**
 * The waterfall base's spec.
 */
export type WaterfallSpec = { 
/**
 * Column layout.
 */
columns: WaterfallColumns, 
/**
 * Optional bucketing.
 */
grouping?: GroupingSpec, 
/**
 * Optional windowing (absent = render the whole list).
 */
windowing?: WindowingSpec, 
/**
 * Card kinds this view may render, in picker order.
 */
card_kinds: Array<string>, 
/**
 * Optional rail widget drawn beside the stream (a timeline).
 */
rail?: string, 
/**
 * Optional search affordance.
 */
search?: string, };

/**
 * Where the windowed rows come from.
 */
export type WindowingSource = "client" | "host";

/**
 * Windowing parameters for a scrolling base view.
 */
export type WindowingSpec = { 
/**
 * Which side owns the window.
 */
source: WindowingSource, 
/**
 * Estimated row height in pixels before measurement.
 */
estimated_item_height?: number, 
/**
 * Screens of overscan kept mounted on either side.
 */
overscan_screens?: number, };
