// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A widget inside a webui dashboard descriptor (P3#A4).
 *
 * Mirrors the shittim-chest `WidgetDescriptor` (dashboard.ts) so the
 * agent-side push tool can construct widgets the webui understands
 * without knowing its internals.
 */
export type DashboardWidget = { 
/**
 * Unique widget id within the layout.
 */
id: string, 
/**
 * Renderer discriminator ("gauge-row", "node-graph", "data-table", …).
 */
type: string, 
/**
 * Optional display title.
 */
title?: string, 
/**
 * Data-source label (free-form).
 */
source: string, 
/**
 * Grid span hint ("full" | "half").
 */
span?: string, 
/**
 * Widget-specific configuration.
 */
config?: Record<string, unknown>, 
/**
 * Initial data payload (shape depends on widget type).
 */
data?: Record<string, unknown>, };

/**
 * Widget create/update/delete on an existing layout (P3#A4).
 */
export type ViewInstancePushParams = { 
/**
 * Target layout (panel instance) id.
 */
layout_id: string, 
/**
 * Mutation: "create" | "update" | "delete".
 */
op: string, 
/**
 * Widget descriptor to create/update (ignored for delete).
 */
widget: DashboardWidget, };
