// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeviceRegisterRangeResult } from "./DeviceRegisterRangeResult";

export type AdaptiveProbeResult = {
  register_range: string;
  function_codes_tested: Array<number>;
  readable_ranges: Array<DeviceRegisterRangeResult>;
  latency_avg_ms: bigint;
  latency_max_ms: bigint;
};
