// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentReference } from "./AgentReference";
import type { ConversationContext } from "./ConversationContext";
import type { ConversationMessage } from "./ConversationMessage";
import type { ConversationStatus } from "./ConversationStatus";
import type { FileAnchor } from "./FileAnchor";

export type AgentConversation = {
  id: string;
  topic: string;
  status: ConversationStatus;
  initiator: AgentReference;
  participants: Array<AgentReference>;
  context: ConversationContext;
  messages: Array<ConversationMessage>;
  file_anchor?: FileAnchor | null;
  created_at: string;
  resolved_at?: string | null;
  human_consultation_id?: string | null;
};
