// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AlignmentCheckResult = {
  goal_id: string;
  alignment_status: string;
  score: number;
  recommendations: string;
};
