// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentReference } from "./AgentReference";
import type { AnnotationType } from "./AnnotationType";

export type Annotation = {
  id: string;
  file_path: string;
  line_start: number | null;
  line_end: number | null;
  content: string;
  annotation_type: AnnotationType;
  author: AgentReference | null;
  created_at: string;
  resolved: boolean;
  resolved_at: string | null;
};
