// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AnomalyInfo = {
  index: number;
  value: number;
  expected: number;
  deviation: number;
  timestamp: bigint | null;
  severity: string;
};
