// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConversationStatus } from "./ConversationStatus";

export type AskAgentResult = {
  conversation_id: string;
  status: ConversationStatus;
  created_at: string;
};
