// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConsultationStatus } from "./ConsultationStatus";

export type AskResult = {
  consultation_id: string;
  question: string;
  context: string;
  options: Array<string>;
  recommended: string;
  status: ConsultationStatus;
};
