// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AuditFinding } from "./AuditFinding";

export type AuditLegalityResult = {
  audit_id: string;
  target: string;
  jurisdiction: string;
  total_requirements: number;
  compliant: number;
  non_compliant: number;
  findings: Array<AuditFinding>;
};
