// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AuditFinding = {
  rule_id: string;
  severity: string;
  description: string;
  evidence: string;
  recommendation: string;
};
