// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AuditFinding } from "./AuditFinding";

export type AuditAlignmentResult = {
  audit_id: string;
  target: string;
  total_rules: number;
  passed: number;
  failed: number;
  findings: Array<AuditFinding>;
};
