// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BrowserMouseMoveResult = {
  browser_id: string;
  x: number;
  y: number;
};
