// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BrowserCreateResult = {
  browser_id: string;
  browser_type: string;
  headless: boolean;
  window_size: string;
};
