// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BrowserRecordResult = {
  browser_id: string;
  action: string;
  status: string;
  file_path: string | null;
};
