// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BrowserConsoleLogEntry } from "./BrowserConsoleLogEntry";

export type BrowserConsoleLogsResult = {
  browser_id: string;
  entries: Array<BrowserConsoleLogEntry>;
};
