// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BrowserScreenshotResult = {
  browser_id: string;
  format: string;
  width: number;
  height: number;
  data_base64: string;
};
