// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BrowserInstanceInfo } from "./BrowserInstanceInfo";

export type BrowserListResult = { instances: Array<BrowserInstanceInfo> };
