// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BrowserNetworkEntry } from "./BrowserNetworkEntry";

export type BrowserNetworkLogsResult = {
  browser_id: string;
  entries: Array<BrowserNetworkEntry>;
};
