// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BrowserNavigateResult = {
  browser_id: string;
  final_url: string;
  title: string;
  http_status: number;
};
