// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BrowserNetworkEntry = {
  method: string;
  url: string;
  status: string;
  content_type: string;
};
