// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CorrelationInfo } from "./CorrelationInfo";
import type { Hypothesis } from "./Hypothesis";

export type CausalReasonResult = {
  correlations: Array<CorrelationInfo>;
  hypotheses: Array<Hypothesis>;
  recommended_actions: Array<string>;
  confidence: number;
};
