// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ComplianceSummary } from "./ComplianceSummary";
import type { ReportDetail } from "./ReportDetail";

export type ComplianceReportToolResult = {
  report_id: string;
  standard_id: string;
  device_id: string | null;
  overall_status: string;
  summary: ComplianceSummary;
  details: Array<ReportDetail>;
  generated_at: string;
};
