// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

export type ComplianceRule = {
  id: string;
  standard: string;
  clause: string;
  description: string;
  check_type: string;
  parameters: JsonValue;
  severity: string;
};
