// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentReference } from "./AgentReference";
import type { FileLineRange } from "./FileLineRange";
import type { FileOperationType } from "./FileOperationType";

export type ConflictInfo = {
  conflict_id: string;
  file_path: string;
  line_range?: FileLineRange | null;
  conflicting_agent: AgentReference;
  operation_type: FileOperationType;
  since: string;
};
