// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ConsultationStatus =
  | "WaitingHuman"
  | "Pending"
  | "Answered"
  | "Delivered"
  | "Scheduled"
  | "Triggered"
  | "Cancelled"
  | "Replied";
