// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InjectedPromptView } from "./InjectedPromptView";

export type ConsumeInjectedPromptsResult = {
  consumed: Array<InjectedPromptView>;
  count: number;
};
