// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ContainerInfoResult = {
  container_id: string;
  name: string;
  image: string;
  status: string;
  running: boolean;
  exit_code: bigint | null;
  ip_address: string;
  started_at: string;
  ports: Array<string>;
  env: Array<string>;
};
