// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContainerListItem } from "./ContainerListItem";

export type ContainerListResult = {
  total_count: number;
  containers: Array<ContainerListItem>;
};
