// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContainerOpStatus } from "./ContainerOpStatus";
import type { VolumeInfo } from "./VolumeInfo";

export type ContainerCreateResult = {
  image: string;
  container_id: string;
  name: string;
  network: string;
  status: ContainerOpStatus;
  volumes: Array<VolumeInfo>;
  seccomp_enabled: boolean;
};
