// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContainerOpStatus } from "./ContainerOpStatus";

export type ContainerForkResult = {
  parent_container_id: string;
  new_container_id: string;
  branch_level: number;
  image: string;
  fallback: boolean;
  status: ContainerOpStatus;
};
