// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ContainerSnapshotResult = {
  container_id: string;
  snapshot_id: string;
  image_id: string;
  image_name: string;
};
