// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ContainerFilterCriteria = {
  label?: { [key in string]: string } | null;
  name?: string | null;
  status?: Array<string> | null;
};
