// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentReasoning } from "./AgentReasoning";
import type { AgentReference } from "./AgentReference";
import type { ConversationMessageType } from "./ConversationMessageType";

export type ConversationMessage = {
  id: string;
  author: AgentReference;
  content: AgentReasoning;
  message_type: ConversationMessageType;
  created_at: string;
};
