// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CorrelationInfo = {
  variable: string;
  correlation: number;
  lag: number;
  direction: string;
};
