// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DeliverMessageResult = {
  todo_id: string;
  title: string;
  target_badge: string;
  status: string;
};
