// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeviceRegisterRangeResult } from "./DeviceRegisterRangeResult";

export type DeviceCapability = {
  protocols: Array<string>;
  register_maps: Array<DeviceRegisterRangeResult>;
  estimated_device_type: string;
  function_codes_supported: Array<number>;
  max_latency_ms: bigint;
};
