// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeviceCapability } from "./DeviceCapability";
import type { Phase1Result } from "./Phase1Result";
import type { Phase2Result } from "./Phase2Result";

export type DeviceSelfTestResponse = {
  device_id: string;
  host: string;
  overall_status: string;
  phase1_self_sensing: Phase1Result;
  phase2_adaptive: Phase2Result;
  capability_profile: DeviceCapability;
  registered_to_node_graph: boolean;
  timestamp: string;
};
