// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DeviceRegisterRangeResult = {
  start: number;
  end: number;
  function_code: number;
  bytes_readable: number;
  success: boolean;
};
