// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type EscalateConversationResult = {
  conversation_id: string;
  human_consultation_id: string;
  escalated_at: string;
};
