// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ExecResult = {
  container_id: string;
  command: string;
  exit_code: bigint | null;
  output: string;
  error: string;
};
