// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConflictInfo } from "./ConflictInfo";

export type FileReadResult = {
  path: string;
  size_bytes: number;
  content: string;
  conflicts: Array<ConflictInfo>;
};
