// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FileAnchor = {
  file_path: string;
  line_start?: number | null;
  line_end?: number | null;
  snapshot_hash?: string | null;
};
