// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConflictInfo } from "./ConflictInfo";
import type { FileOpStatus } from "./FileOpStatus";

export type FileEditResult = {
  path: string;
  status: FileOpStatus;
  occurrences: number;
  conflicts: Array<ConflictInfo>;
};
