// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FileObserverView = {
  agent_type: string;
  instance_badge: string | null;
  observation_type: string;
  registered_at: string;
};
