// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GitPushResult = {
  container_id: string;
  branch: string;
  remote: string;
  commit_hash: string | null;
  pushed: boolean;
  output: string;
};
