// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GoalStatus } from "./GoalStatus";

export type GoalUpdateResult = {
  goal_id: string;
  title: string;
  status: GoalStatus;
};
