// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GoalTaskEntry } from "./GoalTaskEntry";

export type GoalTaskListResult = { count: number; tasks: Array<GoalTaskEntry> };
