// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GoalTaskStatus } from "./GoalTaskStatus";

export type GoalTaskCreateResult = {
  task_id: string;
  track_id: string;
  title: string;
  status: GoalTaskStatus;
  workspace_ids: Array<string>;
};
