// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GoalEntry } from "./GoalEntry";

export type GoalListResult = { count: number; goals: Array<GoalEntry> };
