// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GoalTaskStatus } from "./GoalTaskStatus";

export type GoalTaskCompleteResult = {
  task_id: string;
  status: GoalTaskStatus;
};
