// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GoalStatus } from "./GoalStatus";

export type GoalEntry = {
  id: string;
  title: string;
  description: string | null;
  status: GoalStatus;
  priority: number;
  owner: string;
  parent_goal_id: string | null;
  workspace_ids: Array<string>;
  alignment_score: number | null;
  created_at: string;
  updated_at: string;
};
