// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GoalTaskStatus } from "./GoalTaskStatus";

export type GoalTaskEntry = {
  id: string;
  track_id: string;
  title: string;
  description: string | null;
  status: GoalTaskStatus;
  assignee: string | null;
  effort_estimate: string | null;
  due_at: string | null;
  workspace_ids: Array<string>;
  created_at: string;
  updated_at: string;
};
