// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type InjectUserPromptResult = {
  target_badge: string;
  injected: boolean;
  prompt_count: number;
};
