// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type InjectedPromptView = {
  source_badge: string;
  message: string;
  suggested_skill: string;
  injected_at: string;
};
