// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type KneeJerkTest = {
  test_name: string;
  protocol: string;
  passed: boolean;
  latency_ms: bigint;
  detail: string;
};
