// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ScriptLanguage } from "./ScriptLanguage";

export type Layer2ScriptExecResult = {
  language: ScriptLanguage;
  agent: string;
  tool: string;
  execution_id: string;
  exit_code: number;
  duration_ms: bigint;
  output: string;
};
