// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileObserverView } from "./FileObserverView";

export type ListFileObserversToolResult = {
  file_path: string;
  observers: Array<FileObserverView>;
};
