// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ObserverInfo } from "./ObserverInfo";

export type ListFileObserversResult = {
  file_path: string;
  observers: Array<ObserverInfo>;
};
