// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MediaAssetRegisterResult = {
  asset_id: string;
  asset_type: string;
  source_url: string;
  tags: Array<string>;
};
