// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

export type MediaAssetItem = {
  asset_id: string;
  asset_type: string;
  source_url: string;
  metadata: JsonValue;
  tags: Array<string>;
  created_at: string;
};
