// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MediaAssetItem } from "./MediaAssetItem";

export type MediaAssetRetrieveResult = {
  count: number;
  assets: Array<MediaAssetItem>;
};
