// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

export type MemorySubgraphEdge = {
  source_id: string;
  target_id: string;
  edge_type: string;
  weight: number;
  metadata: { [key in string]: JsonValue } | null;
};
