// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MemoryNodeFull } from "./MemoryNodeFull";
import type { MemorySubgraphEdge } from "./MemorySubgraphEdge";

export type MemorySubgraphResult = {
  query: string;
  total_nodes: number;
  total_edges: number;
  nodes: Array<MemoryNodeFull>;
  edges: Array<MemorySubgraphEdge>;
};
