// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

export type MemoryNodeFull = {
  id: string;
  node_type: string;
  text: string;
  score: number;
  tags: Array<string>;
  created_at: string | null;
  source: string | null;
  metadata: { [key in string]: JsonValue } | null;
};
