// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WriteRangeResult } from "./WriteRangeResult";

export type ModbusWriteResult = {
  station: number;
  transport: string;
  endpoint: string;
  writes: Array<WriteRangeResult>;
  total_written: number;
  all_confirmed: boolean;
};
