// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RegisterRangeResult } from "./RegisterRangeResult";

export type ModbusReadResult = {
  station: number;
  transport: string;
  endpoint: string;
  results: Array<RegisterRangeResult>;
  total_registers: number;
};
