// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModelTier } from "./WsTypes";
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * Where a model physically executes. evernight chooses the backend based on
 * GPU availability — GPU-first, CPU-fallback.
 */
export type ModelBackend = "remote_api" | "gpu" | "cpu";

/**
 * Top-level model category. Determines which subsystem consumes the model.
 */
export type ModelCategory =
  | "llm"
  | "embedding"
  | "speech_to_text"
  | "text_to_speech"
  | "vision";

/**
 * A unified description of an AI model, shared between scepter and chest.
 *
 * Both sides can enumerate available models, check their status, and request
 * inference using this common vocabulary.
 */
export type ModelDescriptor = {
  /**
   * Unique id, e.g. `"bge-m3"`, `"whisper-tiny"`, `"claude-opus-4.8"`.
   */
  id: string;
  /**
   * Human-readable display name.
   */
  display_name: string;
  /**
   * What kind of model this is.
   */
  category: ModelCategory;
  /**
   * Where it runs.
   */
  backend: ModelBackend;
  /**
   * Size tier (LLM coding-plan concept; `None` for non-LLM models).
   */
  tier?: ModelTier;
  /**
   * Output dimension (embedding models only).
   */
  dimension?: number;
  /**
   * Approximate model size in bytes (local models).
   */
  size_bytes?: bigint;
  /**
   * Provider index (`#N` convention; LLM models only).
   */
  provider_index?: number;
};

/**
 * A model inference request, sent from the web UI to the upstream engine
 * over the WS JSON-RPC channel. The engine routes it to the appropriate
 * backend (local CPU / local GPU / remote GPU / remote API).
 */
export type ModelInferenceRequest = {
  /**
   * Which model to use (by id).
   */
  model_id: string;
  /**
   * Input data (format depends on category: text for LLM/embedding,
   * base64 audio for STT, base64 image for vision).
   */
  input: string;
  /**
   * Optional parameters (temperature, max_tokens, language hint …).
   */
  parameters?: JsonValue;
};

/**
 * Inference result returned to the web UI.
 */
export type ModelInferenceResult = {
  /**
   * Model that produced the output.
   */
  model_id: string;
  /**
   * Output data (text for LLM/embedding/TTS, text for STT, JSON for vision).
   */
  output: string;
  /**
   * Time spent (milliseconds).
   */
  elapsed_ms?: bigint;
  /**
   * Token/processing usage (if applicable).
   */
  usage?: JsonValue;
};

/**
 * `Tui.ModelInferenceResult` — inference result push.
 */
export type ModelInferenceResultParams = { result: ModelInferenceResult };

/**
 * `Tui.ModelList` — model catalogue response.
 */
export type ModelListParams = {
  models: Array<ModelDescriptor>;
  servers: Array<ModelServerInfo>;
};

/**
 * What to do with a model server.
 */
export type ModelServerAction = "start" | "stop" | "restart";

/**
 * `Tui.ModelServerActionResult` — action result.
 */
export type ModelServerActionResultParams = {
  kind: ModelServerKind;
  status: ModelServerStatus;
};

/**
 * A managed model server instance, deployed and owned by **evernight**.
 * Neither scepter nor chest starts/stops these directly — they issue
 * `RequestModelServerAction` and evernight performs the lifecycle.
 */
export type ModelServerInfo = {
  /**
   * Server kind (determines the Docker image / launch command).
   */
  kind: ModelServerKind;
  /**
   * HTTP endpoint (e.g. `http://localhost:8178`).
   */
  endpoint: string;
  /**
   * Current lifecycle status.
   */
  status: ModelServerStatus;
  /**
   * Which backend this server is running on (GPU or CPU).
   */
  backend: ModelBackend;
  /**
   * Docker container id (managed by evernight's container runtime).
   */
  container_id?: string;
  /**
   * Which models are loaded in this server.
   */
  loaded_models: Array<string>;
};

/**
 * The type of model server. evernight deploys and manages these; the choice
 * of GPU vs CPU variant is made by evernight at deploy time (GPU-first).
 */
export type ModelServerKind = "ollama" | "whisper_cpp" | "vllm" | "media_pipe";

/**
 * Status of a local model server (ollama, whisper.cpp, …).
 */
export type ModelServerStatus = "running" | "starting" | "stopped" | "failed";

/**
 * `Tui.RequestModelInference` — ask the engine to run a model.
 */
export type RequestModelInferenceParams = { request: ModelInferenceRequest };

/**
 * `Tui.RequestModelList` — enumerate available models.
 */
export type RequestModelListParams = {
  /**
   * Filter by category (omit for all).
   */
  category?: ModelCategory;
};

/**
 * `Tui.RequestModelServerAction` — ask evernight (via scepter) to start /
 * stop / restart a model server. Neither chest nor scepter performs the
 * deployment directly; the action is forwarded to evernight's model lifecycle
 * manager.
 */
export type RequestModelServerActionParams = {
  kind: ModelServerKind;
  action: ModelServerAction;
  /**
   * Preferred backend. evernight will honour this if possible; falls back
   * to CPU if the requested GPU is unavailable.
   */
  preferred_backend?: ModelBackend;
};
