// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MouseOperateResult = {
  remote_id: string;
  action: string;
  x: number;
  y: number;
  button: string;
  success: boolean;
};
