// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type NewContainerVolumeMount = {
  source: string;
  target: string;
  read_only?: boolean | null;
};
