// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type NodeConnectResult = {
  node_id: string;
  node_name: string;
  address: string;
  status: string;
  last_seen: string;
};
