// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type NodeExecuteResult = {
  node_id: string;
  node_name: string;
  host: string;
  command: string;
  exit_code: bigint | null;
  stdout: string;
  stderr: string;
  status: string;
};
