// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NodeInfo } from "./NodeInfo";

export type NodeDiscoverResult = {
  host: string;
  port: number;
  node_id: string | null;
  total_nodes: number;
  status: string;
  nodes: Array<NodeInfo>;
};
