// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConflictInfo } from "./ConflictInfo";

export type NotifyFileOperationResult = {
  file_path: string;
  observers_count: number;
  conflicts: Array<ConflictInfo>;
};
