// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentReference } from "./AgentReference";
import type { ObservationType } from "./ObservationType";

export type ObserverInfo = {
  agent: AgentReference;
  observation_type: ObservationType;
  since: string;
};
