// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type OpcuaBrowseToolResult = {
  endpoint_url: string;
  browsed_node: string;
  status: string;
  message: string;
  note: string;
};
