// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OpcUaNodeInfo } from "./OpcUaNodeInfo";

export type OpcUaBrowseResult = {
  endpoint: string;
  start_node_id: string;
  max_depth: number;
  nodes: Array<OpcUaNodeInfo>;
  total_nodes: number;
  stub: boolean;
};
