// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { KneeJerkTest } from "./KneeJerkTest";

export type Phase1Result = {
  tests_run: number;
  tests_passed: number;
  tests_failed: number;
  results: Array<KneeJerkTest>;
};
