// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdaptiveProbeResult } from "./AdaptiveProbeResult";

export type Phase2Result = {
  register_ranges_scanned: number;
  function_codes_probed: Array<number>;
  readable_registers: number;
  probe_results: Array<AdaptiveProbeResult>;
};
