// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GapInfo } from "./GapInfo";

export type QualityReport = {
  metric: string;
  total_points: number;
  completeness: number;
  expected_points: number;
  missing_points: number;
  duplicate_points: number;
  stale_points: number;
  outlier_count: number;
  outlier_ratio: number;
  gaps: Array<GapInfo>;
  score: number;
};
