// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RemoteRefEntry } from "./RemoteRefEntry";

export type QueryRemoteRefsResult = {
  count: number;
  refs: Array<RemoteRefEntry>;
};
