// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type QueryStats = {
  min: number;
  max: number;
  mean: number;
  std_dev: number;
  p50: number;
  p95: number;
  p99: number;
};
