// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

export type RagDocResult = {
  doc_id: string;
  similarity: number;
  content: string;
  source: string | null;
  metadata: JsonValue | null;
};
