// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RagDbStatsResult = {
  total_documents: number;
  total_media_assets: number;
  embedding_dimensions: number | null;
  storage_backend: string;
};
