// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RagDbWriteResult = {
  doc_id: string;
  embedding_dim: number;
  content: string;
};
