// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RagDocResult } from "./RagDocResult";

export type RagDbReadResult = { count: number; results: Array<RagDocResult> };
