// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RegisterRemoteRefsResult = {
  ref_id: string;
  url: string;
  registered: boolean;
};
