// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RegisterRangeResult = {
  register_type: string;
  start_address: number;
  count: number;
  values: Array<number>;
  raw_bytes: Array<string>;
};
