// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RemoteConnectionInfo = {
  id: string;
  host: string;
  port: number;
  protocol: string;
  connected: boolean;
  connected_at: string | null;
};
