// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RemoteRefEntry = {
  ref_id: string;
  url: string;
  title: string;
  ref_type: string;
  registered_at: string;
};
