// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConversationStatus } from "./ConversationStatus";

export type ReplyAgentResult = {
  conversation_id: string;
  status: ConversationStatus;
};
