// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConsultationStatus } from "./ConsultationStatus";

export type ReplyResult = {
  consultation_id: string;
  answer: string;
  selected_options: Array<string>;
  status: ConsultationStatus;
};
