// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ReportDetail = {
  rule_id: string;
  clause: string;
  description: string;
  status: string;
  severity: string;
  deviation: number | null;
  recommendation: string;
};
