// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConsultationStatus } from "./ConsultationStatus";
import type { JsonValue } from "./serde_json/JsonValue";

export type ReportHumanResult = {
  report_id: string;
  report_type: string;
  content: JsonValue;
  consultation_id: string | null;
  status: ConsultationStatus;
  created_at: string;
};
