// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

export type RuleCheckResult = {
  rule_id: string;
  clause: string;
  description: string;
  status: string;
  actual_value: JsonValue | null;
  expected: JsonValue | null;
  deviation: number | null;
  severity: string;
};
