// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ScriptLanguage } from "./ScriptLanguage";

export type ScriptExecResult = {
  language: ScriptLanguage;
  execution_id: string;
  exit_code: number;
  duration_ms: bigint;
  stdout: string;
  stderr: string;
};
