// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ScriptLanguage =
  | "Bash"
  | "Sh"
  | "Python"
  | "Python3"
  | "Javascript"
  | "Typescript"
  | "Node"
  | "Zsh"
  | "Layer2";
