// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SensitivityRule = {
  tool: string;
  agent?: string | null;
  sensitivity: string;
  reason?: string | null;
};
