// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SignalStats } from "./SignalStats";

export type SignalNormalizeResult = {
  method: string;
  input_count: number;
  output: Array<number>;
  stats: SignalStats;
};
