// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SignalStats = {
  min: number;
  max: number;
  mean: number;
  std_dev: number;
};
