// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type StandardRegisterResult = {
  standard_id: string;
  rules_registered: number;
};
