// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RuleCheckResult } from "./RuleCheckResult";

export type StandardCheckResult = {
  standard_id: string;
  total_rules: number;
  passed: number;
  failed: number;
  not_applicable: number;
  results: Array<RuleCheckResult>;
  overall_status: string;
};
