// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TaskEntry } from "./TaskEntry";

export type TaskListResult = { count: number; tasks: Array<TaskEntry> };
