// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConsultationStatus } from "./ConsultationStatus";

export type TaskCancelResult = { task_id: string; status: ConsultationStatus };
