// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConsultationStatus } from "./ConsultationStatus";
import type { JsonValue } from "./serde_json/JsonValue";

export type TaskScheduleResult = {
  task_id: string;
  schedule: JsonValue;
  status: ConsultationStatus;
  timer_info: string | null;
};
