// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QueryStats } from "./QueryStats";
import type { TimeseriesPointResult } from "./TimeseriesPointResult";

export type TimeseriesQueryResult = {
  metric: string;
  points: Array<TimeseriesPointResult>;
  stats: QueryStats | null;
  count: number;
};
