// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TimeseriesPointResult = {
  timestamp: bigint;
  value: number;
  tags: { [key in string]: string };
};
