// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TodoListItem = {
  id: string;
  title: string;
  status: string;
  parent_id: string | null;
  claimed_by: string;
  created_at: string;
  updated_at: string;
  description: string | null;
  tags: Array<string>;
};
