// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TodoCreateResult = {
  id: string;
  title: string;
  status: string;
  parent_id: string | null;
  created_at: string;
};
