// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TodoTreeNode = {
  id: string;
  title: string;
  status: string;
  children: Array<TodoTreeNode>;
  depth: number;
  description: string | null;
  priority: string | null;
  tags: Array<string>;
};
