// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TodoMoveResult = {
  id: string;
  parent_id: string | null;
  sort_order: number;
  updated_at: string;
};
