// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TodoUpdateResult = {
  id: string;
  title: string;
  status: string;
  updated_at: string;
};
