// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TodoListItem } from "./TodoListItem";

export type TodoListResult = { total: number; items: Array<TodoListItem> };
