// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TodoTreeNode } from "./TodoTreeNode";

export type TodoTreeListResult = { total: number; tree: Array<TodoTreeNode> };
