// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ToolSchemaGetResult = {
  agent_type: string;
  tool_name: string;
  declaration: string;
};
