// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ToolchainVolumeSpec } from "./ToolchainVolumeSpec";

export type ToolchainEnsureResult = {
  profile_id: string;
  source_image: string;
  container_image: string;
  container_env: { [key in string]: string };
  container_volumes: Array<ToolchainVolumeSpec>;
};
