// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TrackStatus } from "./TrackStatus";

export type TrackEntry = {
  id: string;
  goal_id: string;
  title: string;
  description: string | null;
  status: TrackStatus;
  target_value: number | null;
  current_value: number;
  unit: string | null;
  weight: number;
  due_at: string | null;
  workspace_ids: Array<string>;
  created_at: string;
  updated_at: string;
};
