// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TrackStatus } from "./TrackStatus";

export type TrackUpdateResult = {
  track_id: string;
  title: string;
  status: TrackStatus;
  current_value: number;
  target_value: number | null;
};
