// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TrackStatus } from "./TrackStatus";

export type TrackCloseResult = { track_id: string; status: TrackStatus };
