// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TrackStatus } from "./TrackStatus";

export type TrackCreateResult = {
  track_id: string;
  goal_id: string;
  title: string;
  status: TrackStatus;
};
