// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TranslateReportResult = {
  target_language: string;
  original_length: number;
  translated_length: number;
  translation: string;
};
