// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TriggerEntry } from "./TriggerEntry";

export type TriggerListResult = {
  count: number;
  triggers: Array<TriggerEntry>;
};
