// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

export type TriggerAddResult = {
  trigger_id: string;
  trigger_type: string;
  event: JsonValue;
};
