// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WebFetchResult = {
  url: string;
  title: string;
  status_code: number;
  headers: string;
  content: string;
  content_preview: string;
  content_length: number;
};
