// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WebSearchEngine } from "./WebSearchEngine";
import type { WebSearchItem } from "./WebSearchItem";

export type WebSearchResult = {
  query: string;
  engine: WebSearchEngine;
  count: number;
  results: Array<WebSearchItem>;
};
