// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WorkspaceSearchDoc = {
  doc_id: string;
  file_path: string;
  start_line: number;
  end_line: number;
  language: string;
  similarity: number;
  snippet: string;
};
