// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WorkspaceStatusResult = {
  total_files: number;
  total_chunks: number;
  total_bytes: number;
  last_indexed: string | null;
  is_indexing: boolean;
};
