// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkspaceSearchDoc } from "./WorkspaceSearchDoc";

export type WorkspaceSearchResult = {
  count: number;
  results: Array<WorkspaceSearchDoc>;
};
