// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WorkspaceIndexResult = {
  total_files: number;
  total_chunks: number;
  total_bytes: number;
  duration_ms: bigint;
};
