// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Agent, Agent,, SkillStage, StreamChunkKind, } } from "./core";

export type AgentListResponseParams = { agents: Array<TuiAgentInfo> };

export type AgentReportParams = {
  report_type: ReportType;
  agent_type: Agent;
  agent_id: string;
  agent_number?: string;
  title: string;
  content: string;
  summary?: string;
  timestamp: string;
  preset_options: Array<string>;
  /**
   * For `report_type: "query"`: whether `preset_options` are mutually
   * exclusive (single) or pick-any (multiple). Omit ⇒ single.
   */
  selection_mode?: ReportSelection;
  /**
   * For `report_type: "query"`: whether the recipient may type a free-form
   * answer in addition to (or instead of) picking presets. Omit ⇒ true
   * when `report_type == Query`, false otherwise.
   */
  allow_custom_reply?: boolean;
  /**
   * Subset of `preset_options` the agent suggests. Empty when no
   * recommendation is offered.
   */
  recommended_options: Array<string>;
  model_name?: string;
  token_usage?: [number, number];
  skill_count?: number;
  mcp_count?: number;
  next_route?: RouteInfo;
  stream?: LlmStream;
  error?: StructuredAgentError;
};

/**
 * Reply payload for an inquiry (`report_type: "query"`) report.
 *
 * Wire method: `Sync.AgentReportReply` (server-bound). `report_id` mirrors
 * the `agent_id` of the originating `AgentReportParams` so the upstream can
 * correlate without keeping a separate consultation registry.
 */
export type AgentReportReplyParams = {
  report_id: string;
  selected_options: Array<string>;
  custom_answer?: string;
  timestamp: string;
};

export type AgentResponseParams = {
  agent_type: Agent;
  agent_id: string;
  agent_number?: string;
  content: string;
  timestamp: string;
  parent_id?: string;
};

export type AgentStreamingChunkParams = {
  agent_type: Agent;
  agent_id: string;
  agent_number?: string;
  chunk: string;
  is_done: boolean;
  timestamp: string;
  task_id?: string;
  chunk_kind?: StreamChunkKind;
};

export type McpToolResultParams = {
  tool_name: string;
  call_id: string;
  parameters_summary?: string;
  result: string;
  agent_type: Agent;
  agent_id: string;
  agent_number?: string;
  success: boolean;
  duration_ms?: bigint;
};

export type OrchestrationStatusParams = {
  stage: SkillStage;
  agent: string;
  agent_type?: Agent;
  tool_name?: string;
  call_id?: string;
  parent_agent?: string;
  parameters_summary?: string;
};

export type TuiAgentInfo = {
  agent_type: Agent;
  agent_number?: string;
  agent_uuid?: string;
  agent_id: string;
  status: AgentStatus;
  llm_working: boolean;
  cpu_usage: number;
  memory_mb: bigint;
  parent_id?: string;
  work_status?: WorkStatus;
  current_model?: string;
  model_tier?: ModelTier;
  llm_handle?: string;
  token_usage?: [number, number];
  mcp_tool_calls: number;
  request_state: RequestState;
  completion_outcome: CompletionOutcome;
  retry_count: number;
  max_retries: number;
};
