// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AuthChangePasswordResponseParams = { ok: boolean; error?: string };

export type AuthDeleteUserResponseParams = { ok: boolean; error?: string };

export type AuthGetUserResponseParams = {
  ok: boolean;
  user?: UserProfileSummary;
  error?: string;
};

export type AuthListUsersResponseParams = {
  ok: boolean;
  users?: Array<UserProfileSummary>;
  error?: string;
};

export type AuthLoginResponseParams = {
  ok: boolean;
  token?: string;
  session_id?: string;
  user_id?: string;
  username?: string;
  display_name?: string;
  role?: string;
  error?: string;
};

export type AuthRegisterResponseParams = {
  ok: boolean;
  user_id?: string;
  username?: string;
  error?: string;
};

export type UserProfileSummary = {
  id: string;
  username: string;
  email: string;
  display_name: string;
  role: string;
  is_active: boolean;
};
