// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `Sync.BridgeNetwork` — the host/workspace roster response/push.
 */
export type BridgeNetworkParams = { hosts: Array<HostMetrics>, workspaces: Array<WorkspaceNode>, };

/**
 * Live performance snapshot for one host machine.
 */
export type HostMetrics = { 
/**
 * Stable host id ("localhost" for self, or a polemos device id).
 */
host_id: string, hostname: string, os: string, 
/**
 * CPU utilisation, 0..100.
 */
cpu_usage_percent: number, 
/**
 * Logical CPU core count (shown with an i18n "cores" unit).
 */
cpu_cores: number, mem_used_bytes: bigint, mem_total_bytes: bigint, 
/**
 * Outbound network rate (bytes/sec). Omitted when unknown.
 */
net_up_bps?: bigint, 
/**
 * Inbound network rate (bytes/sec). Omitted when unknown.
 */
net_down_bps?: bigint, };

/**
 * `Sync.RequestBridgeNetwork` — request the host/workspace roster.
 */
export type RequestBridgeNetworkParams = Record<symbol, never>;

/**
 * noa-git status for a workspace checkout (branch / dirty / ahead / behind).
 */
export type WorkspaceGitStatus = { branch: string, 
/**
 * Modified/untracked file count.
 */
modified: number, 
/**
 * Commits ahead of upstream.
 */
ahead: number, 
/**
 * Commits behind upstream.
 */
behind: number, 
/**
 * `true` when there are uncommitted changes.
 */
dirty: boolean, };

/**
 * A workspace attached to a host, with its git + token-usage summary.
 */
export type WorkspaceNode = { workspace_id: string, host_id: string, path: string, alias?: string, git?: WorkspaceGitStatus, 
/**
 * Top token consumers in this workspace (max 3).
 */
token_usage: Array<WorkspaceTokenUsage>, };

/**
 * One agent's token usage within a workspace (top-N entries).
 */
export type WorkspaceTokenUsage = { agent: string, input: bigint, output: bigint, };
