// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EmbeddingModel, KnowledgeBaseStatus } from "./core";

export type GetKnowledgeBaseResponseParams = {
  knowledge_base?: KnowledgeBaseInfo;
};

export type KbGenericResponseParams = {
  ok: boolean;
  error?: string;
  id?: string;
};

export type KnowledgeBaseInfo = {
  id: string;
  name: string;
  description?: string;
  status: KnowledgeBaseStatus;
  embedding_model?: EmbeddingModel;
  custom_embedding_endpoint?: string;
  document_count: number;
  subscription_count: number;
  tags: Array<string>;
  created_at: string;
  updated_at: string;
};

export type ListKnowledgeBasesResponseParams = {
  knowledge_bases: Array<KnowledgeBaseInfo>;
};
