// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { } } from "../model";
import type { PeriodType } from "./core";

export type ApiKeyInfoResponseParams = { info: KeyInfo };

export type ConfiguredProviderInfo = {
  provider_name: string;
  display_name: string;
  api_endpoint?: string;
  default_model: string;
  is_enabled: boolean;
};

export type ConfiguredProvidersListParams = {
  providers: Array<ConfiguredProviderInfo>;
};

export type EndpointValidatedParams = {
  provider_name: string;
  is_reachable: boolean;
  latency_ms?: bigint;
  error?: string;
};

export type EntrypointApiConfigInfo = {
  protocol: string;
  base_url: string;
  chat_endpoint: string;
  models_endpoint?: string;
  auth_type: string;
  auth_header?: string;
  env_var: string;
};

export type EntrypointConfigInfo = {
  id: string;
  name: { [key in string]: string };
  type: string;
  billing_type: string;
  plan_tier: string;
  api: EntrypointApiConfigInfo;
  defaults: EntrypointDefaultsInfo;
  quotas: Array<QuotaInfo>;
  models: Array<string>;
};

export type EntrypointDefaultsInfo = {
  deep: Array<string>;
  normal: Array<string>;
  basic: Array<string>;
  max_concurrent: MaxConcurrentInfo;
};

export type KeyInfo = {
  provider: string;
  display_name: string;
  has_key: boolean;
  created_at: string;
  updated_at: string;
  source: string;
};

export type KeysListResponseParams = { keys: Array<KeyInfo> };

export type LlmProviderConfiguredParams = {
  provider_name: string;
  success: boolean;
  error?: string;
};

export type MaxConcurrentInfo = { deep: number; normal: number; basic: number };

export type ModelFsInfo = {
  id: string;
  name: string;
  provider_id: string;
  context_window: bigint;
  max_output_tokens: bigint;
  supports_vision: boolean;
  supports_function_calling: boolean;
  supports_streaming: boolean;
  supports_reasoning: boolean;
  tags: Array<string>;
  /**
   * Fine-grained capability flags. When non-empty, supersedes the boolean
   * flags above for skill→model routing. See [`crate::ModelCapability`].
   */
  capabilities: Array<ModelCapability>;
  /**
   * Generation quality tier (image / 3D generation models only).
   * See [`crate::GenerationTier`].
   */
  generation_tier?: GenerationTier;
  /**
   * Hardware requirements (local generative models only).
   * See [`crate::HardwareRequirements`].
   */
  hardware_requirements?: HardwareRequirements;
  pricing?: ModelFsPricing;
  rate_multiplier?: number;
  rate_rules: Array<RateRuleInfo>;
};

export type ModelFsInfoParams = { models: Array<ModelFsInfo> };

export type ModelFsPricing = {
  input_per_million?: number;
  output_per_million?: number;
  cached_per_million?: number;
};

export type ModelProviderConfigUpdatedParams = {
  provider_name: string;
  success: boolean;
  error?: string;
};

export type ProviderCapabilitiesInfo = {
  streaming: boolean;
  function_calling: boolean;
  vision: boolean;
  reasoning: boolean;
};

export type ProviderDeletedParams = {
  provider_name: string;
  success: boolean;
  error?: string;
};

export type ProviderEditedParams = {
  provider_name: string;
  success: boolean;
  error?: string;
};

export type ProviderFsInfo = {
  id: string;
  name: { [key in string]: string };
  protocol: string;
  category: string;
  base_url?: string;
  entry_points: Array<EntrypointConfigInfo>;
  models: Array<ModelFsInfo>;
  capabilities: ProviderCapabilitiesInfo;
  limits: ProviderLimitsInfo;
  pricing_model: string;
};

export type ProviderFsInfoParams = { providers: Array<ProviderFsInfo> };

export type ProviderLimitsInfo = {
  max_concurrent: number;
  rate_limit_per_minute?: number;
  timeout_seconds: bigint;
};

export type ProviderRenamedParams = {
  provider_name: string;
  new_display_name: string;
  success: boolean;
  error?: string;
};

export type QuotaInfo = {
  data_limit: bigint;
  period_hours?: number;
  period_days?: number;
  billing_metric: string;
};

export type RateRuleInfo = {
  timezone_offset: number;
  peak_start: number;
  peak_end: number;
  peak_multiplier: number;
  off_peak_multiplier: number;
};

export type UsagePeriodData = {
  user_id: string;
  period_type: PeriodType;
  used_tokens: bigint;
  cost: number;
  start_time: string;
  remaining_tokens?: bigint;
  remaining_cost?: number;
};

export type UsagePeriodResponseParams = { data: Array<UsagePeriodData> };

export type UserConfigResponseParams = { config: UserInfoConfig };

export type UserInfoConfig = {
  preferred_language: string;
  default_models: { [key in string]: string };
  enabled_providers: Array<string>;
  enabled_models: Array<string>;
  model_priorities: { [key in string]: number };
  auto_import_from_env: Array<string>;
};
