// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ContainerLogEntryParams = { instance_uuid: string, entry: LogEntryData, };

export type LogEntryData = { source: string, instance_uuid?: string, level: string, target?: string, message: string, fields: Record<string, unknown>, created_at: string, };

export type ServerLogEntryParams = { entry: LogEntryData, };

export type SubscribeLogsResponseParams = { ok: boolean, error?: string, entries: Array<LogEntryData>, };

export type UnsubscribeLogsResponseParams = { ok: boolean, error?: string, };
