// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GateDecision = "allow" | "review" | "block";

export type RestartRisk = "low" | "medium" | "high" | "critical";

export interface RestartGateDecision {
  proposal_id: string;
  decision: GateDecision;
  findings: string[];
  reason: string;
}

export interface RestartProposal {
  proposal_id: string;
  worker_id: string;
  repo_path: string;
  git_diff_summary: string;
  affected_services: string[];
  risk_estimate: RestartRisk;
}
