// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GateDecision = "allow" | "review" | "block";

export type RestartRisk = "low" | "medium" | "high" | "critical";

export interface RestartGateDecision {
  proposal_id: string;
  decision: GateDecision;
  findings: string[];
  reason: string;
}

export interface RestartProposal {
  proposal_id: string;
  worker_id: string;
  repo_path: string;
  git_diff_summary: string;
  affected_services: string[];
  risk_estimate: RestartRisk;
}

// Phase 1 — worker lifecycle wire types

export type ConnectionProtocol = "http" | "ws" | "ipc" | "tcp";

export type WorkerState = "running" | "draining" | "stopped" | "crashed";

export interface ConnectionEndpoint {
  protocol: ConnectionProtocol;
  address: string;
  port: number;
}

export interface DrainRequest {
  worker_id: string;
  proposal_id: string;
  drain_budget_secs: number | null;
}

export interface HealthResponse {
  worker_id: string;
  healthy: boolean;
  ready: boolean;
  not_ready_reason: string | null;
  uptime_secs: number;
  version: string;
}

export interface WorkerRegistration {
  worker_id: string;
  worker_kind: string;
  repo_path: string;
  connections: ConnectionEndpoint[];
  health_check_path: string | null;
  drain_budget_secs: number;
}

export interface WorkerStatus {
  worker_id: string;
  state: WorkerState;
  pid: number | null;
  restart_count: number;
  last_restart_at: string | null;
  connections: ConnectionEndpoint[];
}
