// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Agent, TaskStatus } from "./core";

export type TaskCreatedParams = {
  task_id: string;
  issue_id: string;
  title: string;
  description?: string;
  assigned_agent?: Agent;
  parent_task_id?: string;
  badge?: string;
  tags?: Array<string>;
};

export type TaskStatusUpdateParams = {
  task_id: string;
  status: TaskStatus;
  progress: number;
};
