// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PolemosDeviceInfo = {
  node_id: string;
  name: string;
  address: string;
  status: string;
  workspace_path?: string;
  ide_id?: string;
};

export type PolemosDeviceListParams = { devices: Array<PolemosDeviceInfo> };

export type RegisterPolemosDeviceResponseParams = {
  success: boolean;
  error?: string;
  device?: PolemosDeviceInfo;
};

export type SwitchWorkspaceResponseParams = {
  success: boolean;
  workspace_id: string;
  error?: string;
};

export type WorkspaceStatusParams = {
  workspace_id: string;
  display_name?: string;
  connection_kind: string;
  resolved_path?: string;
  remote_url?: string;
  branch?: string;
  host_id?: string;
};
