// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { YoloTaskTier } from "./core";

export type YoloConfigResponseParams = { tiers: Array<YoloTierConfig>, };

export type YoloCycleCompleteParams = { loop_count: bigint, duration_ms: bigint, };

export type YoloCycleStepParams = { skill: string, loop_count: bigint, status: string, token_usage?: [number, number], model_name?: string, };

export type YoloRunTierNowResponseParams = { ok: boolean, error?: string, };

export type YoloSetTierIntervalResponseParams = { ok: boolean, error?: string, };

export type YoloStartResponseParams = { ok: boolean, error?: string, };

export type YoloStatusResponseParams = { active: boolean, loop_count: bigint, started_at?: string, current_cycle?: string, tiers: Array<YoloTierStatus>, };

export type YoloStopResponseParams = { ok: boolean, error?: string, };

export type YoloTaskResult = { success: boolean, duration_ms: bigint, completed_at: string, error?: string, };

export type YoloTaskStatus = { agent: string, skill: string, enabled: boolean, last_result?: YoloTaskResult, };

export type YoloTerminateResponseParams = { ok: boolean, error?: string, };

export type YoloTierConfig = { tier: YoloTaskTier, enabled: boolean, interval_secs: bigint, tasks: Array<YoloTierTaskConfig>, };

export type YoloTierStatus = { tier: YoloTaskTier, enabled: boolean, interval_secs: bigint, last_run_at?: string, next_run_at?: string, tasks: Array<YoloTaskStatus>, };

export type YoloTierTaskConfig = { agent: string, skill: string, enabled: boolean, };

export type YoloUpdateTaskResponseParams = { ok: boolean, error?: string, };
