// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ReportResult = { summary: string, };

export type TodoClearDryRunResult = { dry_run: boolean, would_delete: number, items: Array<TodoClearItem>, };

export type TodoClearItem = { id: string, title: string, status: string, };

export type TodoClearResult = { deleted_count: bigint, success: boolean, };

export type TodoCreateResult = { id: string, title: string, status: string, parent_id: string | null, created_at: string, };

export type TodoDeleteResult = { deleted_id: string, success: boolean, };

export type TodoListItem = { id: string, title: string, status: string, parent_id: string | null, claimed_by: string, created_at: string, updated_at: string, description: string | null, tags: Array<string>, };

export type TodoListResult = { total: number, items: Array<TodoListItem>, };

export type TodoMoveResult = { id: string, parent_id: string | null, sort_order: number, updated_at: string, };

export type TodoTreeListResult = { total: number, tree: Array<TodoTreeNode>, };

export type TodoTreeNode = { id: string, title: string, status: string, children: Array<TodoTreeNode>, depth: number, description: string | null, priority: string | null, tags: Array<string>, };

export type TodoUpdateResult = { id: string, title: string, status: string, updated_at: string, };
