// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GoalStatus, GoalTaskStatus, TrackStatus } from "../enums";

export type AlignmentCheckParams = { goal_id: string, };

export type AlignmentCheckResult = { goal_id: string, alignment_status: string, score: number, recommendations: string, };

export type GoalCloseParams = { goal_id: string, outcome: string | null, };

export type GoalCloseResult = { goal_id: string, status: GoalStatus, };

export type GoalCreateParams = { title: string, description: string | null, priority: number | null, owner: string | null, parent_goal_id: string | null, workspace_ids: Array<string> | null, };

export type GoalCreateResult = { goal_id: string, title: string, status: GoalStatus, workspace_ids: Array<string>, };

export type GoalEntry = { id: string, title: string, description: string | null, status: GoalStatus, priority: number, owner: string, parent_goal_id: string | null, workspace_ids: Array<string>, alignment_score: number | null, created_at: string, updated_at: string, };

export type GoalListParams = { workspace_id: string | null, status: string | null, parent_goal_id: string | null, limit: number | null, };

export type GoalListResult = { count: number, goals: Array<GoalEntry>, };

export type GoalTaskCompleteParams = { task_id: string, result: Record<string, unknown> | null, };

export type GoalTaskCompleteResult = { task_id: string, status: GoalTaskStatus, };

export type GoalTaskCreateParams = { track_id: string, title: string, description: string | null, assignee: string | null, effort_estimate: string | null, due_at: string | null, workspace_ids: Array<string> | null, parent_task_id: string | null, };

export type GoalTaskCreateResult = { task_id: string, track_id: string, title: string, status: GoalTaskStatus, workspace_ids: Array<string>, };

export type GoalTaskEntry = { id: string, track_id: string, title: string, description: string | null, status: GoalTaskStatus, assignee: string | null, effort_estimate: string | null, due_at: string | null, workspace_ids: Array<string>, created_at: string, updated_at: string, };

export type GoalTaskListParams = { track_id: string | null, goal_id: string | null, workspace_id: string | null, status: string | null, assignee: string | null, limit: number | null, };

export type GoalTaskListResult = { count: number, tasks: Array<GoalTaskEntry>, };

export type GoalTaskUpdateParams = { task_id: string, title: string | null, description: string | null, status: string | null, assignee: string | null, result: Record<string, unknown> | null, };

export type GoalTaskUpdateResult = { task_id: string, title: string, status: GoalTaskStatus, };

export type GoalUpdateParams = { goal_id: string, title: string | null, description: string | null, priority: number | null, status: string | null, };

export type GoalUpdateResult = { goal_id: string, title: string, status: GoalStatus, };

export type TrackCloseParams = { track_id: string, outcome: string | null, };

export type TrackCloseResult = { track_id: string, status: TrackStatus, };

export type TrackCreateParams = { goal_id: string, title: string, description: string | null, target_value: number | null, current_value: number | null, unit: string | null, weight: number | null, due_at: string | null, workspace_ids: Array<string> | null, };

export type TrackCreateResult = { track_id: string, goal_id: string, title: string, status: TrackStatus, };

export type TrackEntry = { id: string, goal_id: string, title: string, description: string | null, status: TrackStatus, target_value: number | null, current_value: number, unit: string | null, weight: number, due_at: string | null, workspace_ids: Array<string>, created_at: string, updated_at: string, };

export type TrackUpdateParams = { track_id: string, title: string | null, target_value: number | null, current_value: number | null, status: string | null, weight: number | null, };

export type TrackUpdateResult = { track_id: string, title: string, status: TrackStatus, current_value: number, target_value: number | null, };
