// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "../serde_json/JsonValue";

export type AnomalyInfo = { index: number, value: number, expected: number, deviation: number, timestamp: bigint | null, severity: string, };

export type CausalReasonResult = { correlations: Array<CorrelationInfo>, hypotheses: Array<Hypothesis>, recommended_actions: Array<string>, confidence: number, };

export type CorrelationInfo = { variable: string, correlation: number, lag: number, direction: string, };

export type Hypothesis = { cause: string, effect: string, strength: number, reasoning: string, };

export type LlmChatResult = { model: string, tokens: string, response: string, };

export type MediaAssetItem = { asset_id: string, asset_type: string, source_url: string, metadata: JsonValue, tags: Array<string>, created_at: string, };

export type MediaAssetRegisterResult = { asset_id: string, asset_type: string, source_url: string, tags: Array<string>, };

export type MediaAssetRetrieveResult = { count: number, assets: Array<MediaAssetItem>, };

export type RagDbDeleteResult = { doc_id: string, };

export type RagDbReadResult = { count: number, results: Array<RagDocResult>, };

export type RagDbStatsResult = { total_documents: number, total_media_assets: number, embedding_dimensions: number | null, storage_backend: string, };

export type RagDbWriteResult = { doc_id: string, embedding_dim: number, content: string, };

export type RagDocResult = { doc_id: string, similarity: number, content: string, source: string | null, metadata: JsonValue | null, };

export type TranslateReportResult = { target_language: string, original_length: number, translated_length: number, translation: string, };

export type WorkspaceIndexResult = { total_files: number, total_chunks: number, total_bytes: number, duration_ms: bigint, };

export type WorkspaceSearchDoc = { doc_id: string, file_path: string, start_line: number, end_line: number, language: string, similarity: number, snippet: string, };

export type WorkspaceSearchResult = { count: number, results: Array<WorkspaceSearchDoc>, };

export type WorkspaceStatusResult = { total_files: number, total_chunks: number, total_bytes: number, last_indexed: string | null, is_indexing: boolean, };
