// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WebSearchEngine } from "./enums";

export type QueryRemoteRefsResult = {
  count: number;
  refs: Array<RemoteRefEntry>;
};

export type RegisterRemoteRefsResult = {
  ref_id: string;
  url: string;
  registered: boolean;
};

export type RemoteRefEntry = {
  ref_id: string;
  url: string;
  title: string;
  ref_type: string;
  registered_at: string;
};

export type WebFetchResult = {
  url: string;
  title: string;
  status_code: number;
  headers: string;
  content: string;
  content_preview: string;
  content_length: number;
};

export type WebSearchItem = { url: string; title: string };

export type WebSearchResult = {
  query: string;
  engine: WebSearchEngine;
  count: number;
  results: Array<WebSearchItem>;
};
