// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConversationMessageType, ConversationStatus, FileOperationType, ObservationType } from "./enums";

export type AgentConversation = {
  id: string;
  topic: string;
  status: ConversationStatus;
  initiator: AgentReference;
  participants: Array<AgentReference>;
  context: ConversationContext;
  messages: Array<ConversationMessage>;
  file_anchor?: FileAnchor | null;
  created_at: string;
  resolved_at?: string | null;
  human_consultation_id?: string | null;
};

export type AgentReasoning = { what: string; why: string; how: string };

export type AgentReference = {
  agent_type: string;
  instance_badge?: string | null;
};

export type AskAgentResult = {
  conversation_id: string;
  status: ConversationStatus;
  created_at: string;
};

export type ChatMessage = { role: string; content: string };

export type ConflictInfo = {
  conflict_id: string;
  file_path: string;
  line_range?: FileLineRange | null;
  conflicting_agent: AgentReference;
  operation_type: FileOperationType;
  since: string;
};

export type ConversationContext = { what: string; why: string; how: string };

export type ConversationMessage = {
  id: string;
  author: AgentReference;
  content: AgentReasoning;
  message_type: ConversationMessageType;
  created_at: string;
};

export type EscalateConversationResult = {
  conversation_id: string;
  human_consultation_id: string;
  escalated_at: string;
};

export type FileAnchor = {
  file_path: string;
  line_start?: number | null;
  line_end?: number | null;
  snapshot_hash?: string | null;
};

export type FileLineRange = { start: number; end: number };

export type GetConversationResult = { conversation: AgentConversation };

export type ListConversationsResult = {
  count: number;
  conversations: Array<AgentConversation>;
};

export type ListFileObserversResult = {
  file_path: string;
  observers: Array<ObserverInfo>;
};

export type LlmProviderCallResult = {
  model: string;
  tokens: string;
  response: string;
};

export type NotifyFileOperationResult = {
  file_path: string;
  observers_count: number;
  conflicts: Array<ConflictInfo>;
};

export type ObserverInfo = {
  agent: AgentReference;
  observation_type: ObservationType;
  since: string;
};

export type ReplyAgentResult = {
  conversation_id: string;
  status: ConversationStatus;
};
