// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConsultationStatus, ContainerOpStatus } from "../enums";

export type ContainerCreateResult = {
  image: string;
  container_id: string;
  name: string;
  network: string;
  status: ContainerOpStatus;
  volumes: Array<VolumeInfo>;
  seccomp_enabled: boolean;
};

export type ContainerFilterCriteria = {
  label?: { [key in string]: string } | null;
  name?: string | null;
  status?: Array<string> | null;
};

export type ContainerForkResult = {
  parent_container_id: string;
  new_container_id: string;
  branch_level: number;
  image: string;
  fallback: boolean;
  status: ContainerOpStatus;
};

export type ContainerInfoResult = {
  container_id: string;
  name: string;
  image: string;
  status: string;
  running: boolean;
  exit_code: bigint | null;
  ip_address: string;
  started_at: string;
  ports: Array<string>;
  env: Array<string>;
};

export type ContainerListItem = {
  name: string;
  image: string;
  status: string;
  id: string;
};

export type ContainerListResult = {
  total_count: number;
  containers: Array<ContainerListItem>;
};

export type ContainerRemoveResult = {
  container_id: string;
  status: ContainerOpStatus;
};

export type ContainerSnapshotResult = {
  container_id: string;
  snapshot_id: string;
  image_id: string;
  image_name: string;
};

export type ContainerStartResult = {
  container_id: string;
  status: ContainerOpStatus;
};

export type ContainerStopResult = {
  container_id: string;
  status: ContainerOpStatus;
};

export type DeliverMessageResult = {
  todo_id: string;
  title: string;
  target_badge: string;
  status: ConsultationStatus;
  metadata: { [key in string]: string };
};

export type ExecResult = {
  container_id: string;
  command: string;
  exit_code: bigint | null;
  output: string;
  error: string;
};

export type GitPushResult = {
  container_id: string;
  branch: string;
  remote: string;
  commit_hash: string | null;
  pushed: boolean;
  output: string;
};

export type NewContainerVolumeMount = {
  source: string;
  target: string;
  read_only?: boolean | null;
};

export type SidecarSendResult = { name: string; sent: boolean };

export type ToolchainEnsureResult = {
  profile_id: string;
  source_image: string;
  container_image: string;
  container_env: { [key in string]: string };
  container_volumes: Array<ToolchainVolumeSpec>;
};

export type ToolchainListResult = { profiles: Array<ToolchainProfileInfo> };

export type ToolchainProfileInfo = {
  id: string;
  display_name: string;
  source_image: string;
  image_pulled: boolean;
  volume_ready: boolean;
  available_tools: Array<string>;
  supported_languages: Array<string>;
};

export type ToolchainVolumeSpec = {
  host_path: string;
  container_path: string;
  read_only: boolean;
};

export type VolumeInfo = {
  host_path: string;
  container_path: string;
  read_only: boolean;
};
