// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "../serde_json/JsonValue";

export type GapInfo = { start_time: bigint, end_time: bigint, estimated_missing: number, };

export type MemoryNodeFull = { id: string, node_type: string, text: string, score: number, tags: Array<string>, created_at: string | null, source: string | null, metadata: { [key in string]: JsonValue } | null, };

export type MemorySubgraphEdge = { source_id: string, target_id: string, edge_type: string, weight: number, metadata: { [key in string]: JsonValue } | null, };

export type MemorySubgraphResult = { query: string, total_nodes: number, total_edges: number, nodes: Array<MemoryNodeFull>, edges: Array<MemorySubgraphEdge>, };

export type QualityReport = { metric: string, total_points: number, completeness: number, expected_points: number, missing_points: number, duplicate_points: number, stale_points: number, outlier_count: number, outlier_ratio: number, gaps: Array<GapInfo>, score: number, };

export type QueryStats = { min: number, max: number, mean: number, std_dev: number, p50: number, p95: number, p99: number, };

export type TimeseriesPointResult = { timestamp: bigint, value: number, tags: { [key in string]: string }, };

export type TimeseriesQueryResult = { metric: string, points: Array<TimeseriesPointResult>, stats: QueryStats | null, count: number, };

export type ToolSchemaGetResult = { agent_type: string, tool_name: string, declaration: string, };
