// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GoalStatus, GoalTaskStatus, TrackStatus } from "../enums";

export type AlignmentCheckResult = {
  goal_id: string;
  alignment_status: string;
  score: number;
  recommendations: string;
};

export type GoalCloseResult = { goal_id: string; status: GoalStatus };

export type GoalCreateResult = {
  goal_id: string;
  title: string;
  status: GoalStatus;
  workspace_ids: Array<string>;
};

export type GoalEntry = {
  id: string;
  title: string;
  description: string | null;
  status: GoalStatus;
  priority: number;
  owner: string;
  parent_goal_id: string | null;
  workspace_ids: Array<string>;
  alignment_score: number | null;
  created_at: string;
  updated_at: string;
};

export type GoalListResult = { count: number; goals: Array<GoalEntry> };

export type GoalTaskCompleteResult = {
  task_id: string;
  status: GoalTaskStatus;
};

export type GoalTaskCreateResult = {
  task_id: string;
  track_id: string;
  title: string;
  status: GoalTaskStatus;
  workspace_ids: Array<string>;
};

export type GoalTaskEntry = {
  id: string;
  track_id: string;
  title: string;
  description: string | null;
  status: GoalTaskStatus;
  assignee: string | null;
  effort_estimate: string | null;
  due_at: string | null;
  workspace_ids: Array<string>;
  created_at: string;
  updated_at: string;
};

export type GoalTaskListResult = { count: number; tasks: Array<GoalTaskEntry> };

export type GoalTaskUpdateResult = {
  task_id: string;
  title: string;
  status: GoalTaskStatus;
};

export type GoalUpdateResult = {
  goal_id: string;
  title: string;
  status: GoalStatus;
};

export type TrackCloseResult = { track_id: string; status: TrackStatus };

export type TrackCreateResult = {
  track_id: string;
  goal_id: string;
  title: string;
  status: TrackStatus;
};

export type TrackEntry = {
  id: string;
  goal_id: string;
  title: string;
  description: string | null;
  status: TrackStatus;
  target_value: number | null;
  current_value: number;
  unit: string | null;
  weight: number;
  due_at: string | null;
  workspace_ids: Array<string>;
  created_at: string;
  updated_at: string;
};

export type TrackUpdateResult = {
  track_id: string;
  title: string;
  status: TrackStatus;
  current_value: number;
  target_value: number | null;
};
