// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "../serde_json/JsonValue";

export type BrowserCloseResult = { browser_id: string; status: string };

export type BrowserConsoleLogEntry = {
  level: string;
  text: string;
  timestamp: string;
};

export type BrowserConsoleLogsResult = {
  browser_id: string;
  entries: Array<BrowserConsoleLogEntry>;
};

export type BrowserCreateResult = {
  browser_id: string;
  browser_type: string;
  headless: boolean;
  window_size: string;
};

export type BrowserInstanceInfo = {
  browser_id: string;
  browser_type: string;
  headless: boolean;
  window_size: string;
};

export type BrowserKeypressResult = { browser_id: string; key: string };

export type BrowserListResult = { instances: Array<BrowserInstanceInfo> };

export type BrowserMouseClickResult = { browser_id: string; selector: string };

export type BrowserMouseMoveResult = {
  browser_id: string;
  x: number;
  y: number;
};

export type BrowserNavigateResult = {
  browser_id: string;
  final_url: string;
  title: string;
  http_status: number;
};

export type BrowserNetworkEntry = {
  method: string;
  url: string;
  status: string;
  content_type: string;
};

export type BrowserNetworkLogsResult = {
  browser_id: string;
  entries: Array<BrowserNetworkEntry>;
};

export type BrowserRecordResult = {
  browser_id: string;
  action: string;
  status: string;
  file_path: string | null;
};

export type BrowserScreenshotResult = {
  browser_id: string;
  format: string;
  width: number;
  height: number;
  data_base64: string;
};

export type BrowserScriptResult = {
  browser_id: string;
  result: JsonValue;
  return_type: string;
};
