//! Anti-drift nails for the npm publishing surface.
//!
//! `bindings/evernightProtocol.ts` is regenerated by ts-rs every time
//! `cargo test` runs (the 13 `#[ts(export)]` types merge into that one
//! file). The npm package is types-only and must not ship raw TypeScript,
//! so the published declarations live in `bindings/evernightProtocol.d.ts`
//! — a byte-identical copy of the generated `.ts`. These tests pin that
//! copy and the `package.json` surface, so regeneration without a re-copy
//! (or a regression to bare-`.ts` publishing) fails the build instead of
//! shipping a stale contract to npm.

use std::collections::BTreeSet;
use std::fs;
use std::path::Path;

use serde_json::Value;

const TS_BINDINGS: &str = "bindings/evernightProtocol.ts";
const DTS_BINDINGS: &str = "bindings/evernightProtocol.d.ts";

/// The `.d.ts` mirror must stay a byte-identical copy of the ts-rs output.
/// After changing a DTO, `cargo test` regenerates the `.ts` and this test
/// goes red until the mirror is refreshed:
/// `cp bindings/evernightProtocol.ts bindings/evernightProtocol.d.ts`.
#[test]
fn dts_mirror_is_byte_identical_to_the_generated_bindings() {
    let ts = read_package_file(TS_BINDINGS);
    let dts = read_package_file(DTS_BINDINGS);
    assert_eq!(
        dts, ts,
        "bindings/evernightProtocol.d.ts drifted from the ts-rs output; refresh it with \
         `cp bindings/evernightProtocol.ts bindings/evernightProtocol.d.ts`"
    );
}

/// Both binding files must export exactly the public DTO surface — the 13
/// ts-rs exported types. Catches a silent export drop (a lost
/// `#[ts(export)]`) just as hard as an un-refreshed mirror.
#[test]
fn exported_type_names_match_the_public_dto_surface() {
    let expected: BTreeSet<String> = [
        "ConnectParamsDto",
        "ConnectResultDto",
        "DataAddressDto",
        "PingParamsDto",
        "PingResultDto",
        "ProbeParamsDto",
        "ProbeResultDto",
        "ReadParamsDto",
        "ReadResultDto",
        "TransportInfoDto",
        "WriteParamsDto",
        "WriteResultDto",
        "WriteVerificationDto",
    ]
    .iter()
    .map(|name| (*name).to_string())
    .collect();

    let ts_names = export_type_names(&read_package_file(TS_BINDINGS));
    assert_eq!(
        ts_names, expected,
        "the generated .ts must export the public DTO surface"
    );

    let dts_names = export_type_names(&read_package_file(DTS_BINDINGS));
    assert_eq!(
        dts_names, expected,
        "the published .d.ts must export the public DTO surface"
    );
}

/// The npm package must stay a types-only package: `types` resolves to the
/// `.d.ts` entry, `main` to the empty runtime placeholder, and the `files`
/// whitelist ships no raw `.ts` (the bare-TypeScript form this package
/// replaced).
#[test]
fn package_json_ships_a_types_only_surface() {
    let manifest: Value =
        serde_json::from_str(&read_package_file("package.json")).expect("valid package.json");
    assert_eq!(
        manifest["types"], "index.d.ts",
        "types must point at the .d.ts entry"
    );
    assert_eq!(
        manifest["main"], "index.js",
        "main must point at the runtime placeholder"
    );

    let files = manifest["files"].as_array().expect("files whitelist");
    let shipped: Vec<&str> = files
        .iter()
        .map(|entry| entry.as_str().expect("files entries are strings"))
        .collect();
    for artifact in ["index.d.ts", "index.js", "bindings/evernightProtocol.d.ts"] {
        assert!(
            shipped.contains(&artifact),
            "files must ship {artifact}, got {shipped:?}"
        );
    }
    assert!(
        !shipped
            .iter()
            .any(|file| file.ends_with(".ts") && !file.ends_with(".d.ts")),
        "raw TypeScript must not ship to npm: {shipped:?}"
    );

    // The published entry must re-export the mirror (extensionless import
    // resolves to the .d.ts inside the published file set), and the
    // runtime placeholder must stay a no-op.
    let index_dts = read_package_file("index.d.ts");
    assert!(
        index_dts.contains("export * from \"./bindings/evernightProtocol\""),
        "index.d.ts must re-export the binding mirror"
    );
    let index_js = read_package_file("index.js");
    assert!(
        index_js.contains("module.exports = {};"),
        "index.js must stay the empty CommonJS placeholder"
    );
}

fn read_package_file(relative: &str) -> String {
    let path = Path::new(env!("CARGO_MANIFEST_DIR")).join(relative);
    fs::read_to_string(&path)
        .unwrap_or_else(|error| panic!("missing {relative} in the package directory: {error}"))
}

/// Extracts the names of all `export type <Name>` declarations.
fn export_type_names(source: &str) -> BTreeSet<String> {
    source
        .lines()
        .filter_map(|line| line.trim().strip_prefix("export type "))
        .map(|rest| rest.split_whitespace().next().unwrap_or(rest).to_string())
        .collect()
}
