// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Params of [`PROTOCOL_CONNECT_METHOD`].
 */
export type ConnectParamsDto = { 
/**
 * How to reach the device.
 */
transport: TransportInfoDto, };

/**
 * Result of [`PROTOCOL_CONNECT_METHOD`].
 */
export type ConnectResultDto = { 
/**
 * Whether the connection was established.
 */
connected: boolean, };

/**
 * Identifies a data location across any industrial protocol: the
 * `address` field of [`protocol.read`](crate::PROTOCOL_READ_METHOD) and
 * [`protocol.write`](crate::PROTOCOL_WRITE_METHOD) params.
 */
export type DataAddressDto = { "kind": "modbus", 
/**
 * Modbus station/slave ID.
 */
station: number, 
/**
 * Modbus function code.
 */
fc: number, 
/**
 * Starting register address.
 */
address: number, 
/**
 * Number of registers to read/write.
 */
count: number, } | { "kind": "s7", 
/**
 * Data block number.
 */
db_number: number, 
/**
 * Byte offset within the DB.
 */
offset: number, 
/**
 * Number of bytes to read/write.
 */
length: number, } | { "kind": "mc", 
/**
 * Device code (e.g. "D", "M", "X", "Y").
 */
device: string, 
/**
 * Starting head address.
 */
head_address: number, 
/**
 * Number of elements.
 */
count: number, } | { "kind": "raw", 
/**
 * Raw address string (protocol-specific).
 */
address: string, 
/**
 * Expected data size in bytes.
 */
size: number, };

/**
 * Params of [`PROTOCOL_PING_METHOD`] — the empty params object `{}`.
 *
 * JSON-RPC 2.0 lets a no-argument method omit `params` entirely, and the
 * sibling TypeScript client does exactly that when called without an
 * argument; plana's router hands such a handler `Value::Null` for the
 * missing field. Deserialization therefore tolerates `null` alongside the
 * canonical `{}` (unknown fields are ignored, mirroring serde's derive
 * default), while serialization always emits `{}`.
 */
export type PingParamsDto = Record<symbol, never>;

/**
 * Result of [`PROTOCOL_PING_METHOD`].
 */
export type PingResultDto = { 
/**
 * Whether the device answered the connectivity check.
 */
reachable: boolean, };

/**
 * Params of [`PROTOCOL_PROBE_METHOD`].
 */
export type ProbeParamsDto = { 
/**
 * The endpoint to probe.
 */
transport: TransportInfoDto, };

/**
 * Result of [`PROTOCOL_PROBE_METHOD`].
 *
 * Not to be confused with `plana_celestia_types::tools::polemos::
 * ProtocolProbeResult` (the LLM terminal tool's probe report) — see the
 * crate docs.
 */
export type ProbeResultDto = { 
/**
 * Human-readable protocol name that was detected (e.g. "modbus_tcp").
 */
protocol: string, 
/**
 * Detection confidence in `[0.0, 1.0]`.
 */
confidence: number, };

/**
 * Params of [`PROTOCOL_READ_METHOD`].
 */
export type ReadParamsDto = { 
/**
 * Where to read.
 */
address: DataAddressDto, };

/**
 * Result of [`PROTOCOL_READ_METHOD`].
 */
export type ReadResultDto = { 
/**
 * Raw bytes read from the device.
 */
raw: Array<number>, 
/**
 * Read latency in microseconds.
 */
latency_us: bigint, };

/**
 * Describes how to reach a device: the `transport` field of
 * [`protocol.connect`](crate::PROTOCOL_CONNECT_METHOD) and
 * [`protocol.probe`](crate::PROTOCOL_PROBE_METHOD) params.
 */
export type TransportInfoDto = { "kind": "tcp", 
/**
 * TCP hostname or IP address.
 */
host: string, 
/**
 * TCP port number.
 */
port: number, } | { "kind": "serial", 
/**
 * Serial device path (e.g. "/dev/ttyUSB0").
 */
port: string, 
/**
 * Optional baud rate hint. Serializes as `null` when absent and
 * defaults to `None` when the field is missing on the wire.
 */
baud: number | null, };

/**
 * Params of [`PROTOCOL_WRITE_METHOD`].
 */
export type WriteParamsDto = { 
/**
 * Where to write.
 */
address: DataAddressDto, 
/**
 * Raw bytes to write.
 */
data: Array<number>, };

/**
 * Result of [`PROTOCOL_WRITE_METHOD`].
 */
export type WriteResultDto = { 
/**
 * Whether a read-back verification confirmed the write. `false` is not
 * proof of failure — see [`verification`](Self::verification) for the
 * precise tri-state.
 */
confirmed: boolean, 
/**
 * Precise verification status. `#[serde(default)]` keeps legacy
 * `{ "confirmed": bool }` payloads deserializable (they map to
 * [`WriteVerificationDto::Unknown`]).
 */
verification: WriteVerificationDto, };

/**
 * Tri-state confirmation of a
 * [`protocol.write`](crate::PROTOCOL_WRITE_METHOD) result.
 */
export type WriteVerificationDto = "confirmed" | "unconfirmed" | "unknown";
