// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AgentConfig = { max_concurrent_tasks: number, timeout_secs: number, retry_on_failure: boolean, model: string, system_prompt: string, };

export type AgentContainer = { id: string, image: string, status: string, uptime_secs: bigint, };

export type AgentItem = { id: string, name: string, description: string, agent_type: string, layer: number, status: string, enabled: boolean, tools: Array<AgentTool>, toolsCount: number, subscribed: boolean, installed: boolean, version: string, config: AgentConfig, container: AgentContainer | null, skills: Array<string>, createdAt: string, updatedAt: string, };

export type AgentTool = { id: string, name: string, description: string, enabled: boolean, };

export type AliasRegistryEntry = { workspace_uuid: string, alias: string, short_id: string, };

export type AvatarPlatformResponse = { id: string, slug: string, label: string, url_template: string, hint: string | null, enabled: boolean, sort_order: number, };

export type AvatarUpdateResponse = { avatar_url: string | null, };

export type ChannelConfigDetail = { id: string, platform: string, enabled: boolean, name: string, description?: string, bot_token?: string, app_id?: string, app_secret?: string, verify_token?: string, api_base?: string, extra_config?: Record<string, unknown>, webhook_path: string, last_error?: string, last_tested_at?: string, created_at: string, updated_at: string, };

export type ChannelConfigResponse = { config: ChannelConfigDetail, active: boolean, };

export type ChannelConfigsResponse = { configs: Array<ChannelConfigResponse>, };

export type ChannelListItem = { platform: string, enabled: boolean, bot_name: string, webhook_path: string, };

export type ChannelListResponse = { channels: Array<ChannelListItem>, };

export type ChannelMessageItem = { id: string, platform: string, direction: string, message_id: string, chat_id: string, sender_id: string | null, text: string, is_group: boolean, group_id: string | null, error: string | null, created_at: string, };

export type ChannelMessageListResponse = { messages: Array<ChannelMessageItem>, count: number, };

export type ConnectionStatus = { connected: boolean, latency: bigint, lastCheck: string, };

export type CreatedResponse = { created: Array<string>, };

export type CursorState = { workspace_id?: string, file?: string, line: number, column: number, total_lines?: number, language?: string, visible_range?: CursorVisibleRange, };

export type CursorVisibleRange = { start: number, end: number, };

export type DeletedResponse = { deleted: bigint, };

export type DeliveryListResponse = { deliveries: Array<Record<string, unknown>>, count: number, };

export type DeviceResponse = { id: string, device_id: string, name: string, device_type: string, status: string, last_seen_at: string | null, metadata?: Record<string, unknown>, created_at: string, };

export type ErrorResponse = { error: string, message?: string, };

export type FileEntry = { name: string, type: string, size: bigint | null, };

export type FileListingResponse = { path: string, entries: Array<FileEntry>, };

export type GrantItem = { id: string, scope: string, user_id: string | null, group_id: string | null, permission: string, resource_id: string | null, granted: boolean, created_at: string, };

export type GrantListResponse = { grants: Array<GrantItem>, };

export type HealthDetailed = { shittimChest: ConnectionStatus, scepter: ConnectionStatus, database: ConnectionStatus, activeSessions: number, uptime: bigint, version: string, };

export type HealthResponse = { status: string, version: string, mock: boolean, };

export type IdResponse = { id: string, };

export type IpWhitelistResponse = { enabled: boolean, whitelist: Array<Record<string, unknown>>, };

export type ModelInfo = { id: string, provider_name: string, provider_id: string, category: string, };

export type MyPermissions = { role: string, permissions: Array<string>, };

export type OAuthProvider = { provider: string, client_id: string, client_secret_masked: string, public_domain: string, enabled: boolean, };

export type OkIdResponse = { ok: boolean, id: string, };

export type OkMessageResponse = { ok: boolean, message: string, };

export type OkResponse = { ok: boolean, };

export type PermissionsResponse = { role: string, permissions: Array<string>, };

export type ProjectItem = { id: string, name: string, description: string | null, sort_order: number, created_at: string, updated_at: string, };

export type ProviderPublic = { id: string, name: string, endpoint: string, api_key_masked: string, models: Array<string>, category: string, is_default: boolean, enabled: boolean, priority: number, };

export type ProxySystemInfo = { version: string, nodeVersion: string, platform: string, cpuUsage: number, memoryUsage: number, diskUsage: number, };

export type RbacGroup = { id: string, name: string, description: string, member_count: number, created_at: string, updated_at: string, };

export type RbacGroupsResponse = { groups: Array<RbacGroup>, };

export type RbacUser = { id: string, username: string, email: string, display_name: string, avatar_url: string | null, is_active: boolean, is_admin: boolean, role: string, tier: string, created_at: string, };

export type RbacUsersResponse = { users: Array<RbacUser>, };

export type ReadinessResponse = { status: string, database: boolean, };

export type ResourceQuota = { id: string, name: string, resource_type: string, limit_value: number, limit_unit: string, used_value: number, period: string, tier: string, enabled: boolean, };

export type ResourceQuotaListResponse = { quotas: Array<ResourceQuota>, };

export type ResourceUsageResponse = { summary: Array<ResourceUsageSummary>, };

export type ResourceUsageSummary = { resource_type: string, current_usage: number, unit: string, limit: number, period: string, utilization_pct: number, };

export type SceneBloom = { strength: number, radius: number, threshold: number, };

export type SceneCamera = { position: SceneVec3, target: SceneVec3, bookmarks?: { [key in string]: SceneCameraBookmark } | null, };

export type SceneCameraBookmark = { position: SceneVec3, target: SceneVec3, };

export type SceneConfigItem = { project_id: string, background_color: string, ground: SceneGround | null, lighting: SceneLighting | null, grid: SceneGrid, camera: SceneCamera, bloom: SceneBloom, ambient_light_intensity: number, };

export type SceneGrid = { visible: boolean, size: number, divisions: number, };

export type SceneGround = { enabled: boolean, size_x: number, size_z: number, color: string, y: number, grid_visible: boolean, grid_size: number, grid_divisions: number, grid_color: string, grid_opacity: number, };

export type SceneLighting = { ambient_color: [number, number, number], ambient_intensity: number, directional_color: [number, number, number], directional_intensity: number, directional_position: [number, number, number], };

export type SceneVec3 = { x: number, y: number, z: number, };

export type SessionCreateResponse = { session_id: string, status: string, signaling?: Record<string, unknown>, };

export type SetupCheckResponse = { needs_setup: boolean, locale?: string, registration_enabled: boolean, };

export type SkillItem = { skill_id: string, name: string, description: string, category: string, agent: string, agent_types: Array<string>, parameters: Array<SkillParameterItem>, estimated_duration_secs: bigint, };

export type SkillParameterItem = { name: string, type: string, default?: unknown, description: string | null, required: boolean, };

export type StatusResponse = { status: string, agent_id?: string, platform?: string, id?: string, plugin_id?: string, };

export type SystemInfoAgents = { total: number, running: number, idle: number, stopped: number, };

export type SystemInfoConnections = { active_ws: number, active_http: number, };

export type SystemInfoDatabase = { engine: string, size_mb: number, connections: number, };

export type SystemInfoResources = { cpu_usage_pct: number, memory_used_gb: number, memory_total_gb: number, disk_used_gb: number, disk_total_gb: number, };

export type SystemInfoResponse = { version: string, uptime_secs: bigint, agents: SystemInfoAgents, resources: SystemInfoResources, connections: SystemInfoConnections, database: SystemInfoDatabase, };

export type TierDefinition = { tier: string, daily_request_limit: number, monthly_token_limit: number, max_sessions: number, price: string, };

export type TierListResponse = { tiers: Array<TierDefinition>, };

export type TokenUsageResponse = { usage: Array<UsageEntry>, total_tokens: bigint, };

export type ToolItem = { tool_id: string, name: string, description: string, category: string, agent: string, input_schema: Record<string, unknown>, output_schema?: Record<string, unknown>, };

export type UpdateUserTierPayload = { user_id: string, tier: string, };

export type UsageDataResponse = { period: string, total_tokens: bigint, total_cost_usd: number, by_model: Array<UsageModelEntry>, by_day: Array<UsageDayEntry>, };

export type UsageDayEntry = { date: string, tokens: bigint, requests: number, };

export type UsageEntry = { model: string, token_count: bigint, };

export type UsageModelEntry = { model: string, tokens: bigint, cost_usd: number, requests: number, };

export type UserPreferences = { theme?: string, themeMode?: string, chatMode?: string, locale?: string, };

export type UserProfileResponse = { id: string, username: string, email: string, display_name: string, avatar_url: string | null, is_active: boolean, is_admin: boolean, role: string, groups: Array<RbacGroup>, preferences?: UserPreferences, created_at: string, };

export type UserTierInfo = { user_id: string, tier: string, tier_expires_at?: string, daily_quota_used: number, monthly_token_used: number, last_quota_reset_at?: string, };

export type ValidateKeyResponse = { valid: boolean, models: Array<string>, recommended_models: Array<string>, error: string | null, };

export type VendorInfo = { id: string, name: string, endpoint: string, category: string, description: string, recommended_models: Array<string>, plan_models: { [key in string]: Array<string> }, };

export type WebhookDeliveryGenItem = { id: string, webhook_id: string, event: string, status: number, duration_ms: bigint, timestamp: string, request_headers: { [key in string]: string }, response_body?: Record<string, unknown>, };

export type WebhookDeliveryItem = { id: string, webhookId: string, event: string, statusCode: number, requestHeaders: { [key in string]: string }, requestBody?: Record<string, unknown>, responseHeaders?: { [key in string]: string }, responseBody: string, duration: bigint, success: boolean, deliveredAt: string, };

export type WebhookInfoItem = { name: string, url: string, events: Array<string>, };

export type WebhookItem = { id: string, name: string, url: string, platform: string, secret: string, events: Array<string>, status: string, lastDeliveryAt?: string, createdAt: string, updatedAt: string, };

export type WebhookListResponse = { webhooks: Array<WebhookInfoItem>, };

export type WorkspaceItem = { id: string, path: string, workspace_path?: string, editor: string, editor_name?: string, git_branch: string, status: string, connected: boolean, short_id: string, alias?: string | null, connection_kind: string, kind?: string, user_id?: string, workspace_path?: string, };

export type WorkspaceResolveResponse = { workspace_uuid: string, short_id: string, alias?: string, path: string, };

export type WorkspaceSessionResponse = { workspace_id: string, workspace_path: string, editor_name: string, editor_version: string, git_branch: string, cursor?: CursorState, connected_at: string, last_heartbeat: string, };
