// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

export type Agent =
  | "HapLotes"
  | "SkoPeo"
  | "HubRis"
  | "KaLos"
  | "NeiKos"
  | "SkeMma"
  | "ApoRia"
  | "EleOs"
  | "EpieiKeia"
  | "OreXis"
  | "PhiLia"
  | "PoleMos"
  | "WebAutomation"
  | "ClassicSoftwareEngineering"
  | "WebUiPanel"
  | "IndustrialIoT";

export type AgentBadge = string;

export type AgentErrorCode =
  | "model_no_providers"
  | "model_no_models"
  | "model_tier_mismatch"
  | "model_all_excluded"
  | "model_env_incomplete"
  | "model_selection_retry_exhausted"
  | "llm_call_failed"
  | "llm_empty_response"
  | "llm_rate_limited"
  | "llm_auth_failed"
  | "llm_timeout"
  | "cosmos_no_connection"
  | "cosmos_tool_failed"
  | "cosmos_local_unavailable"
  | "chain_max_depth"
  | "chain_cycle"
  | "chain_failed"
  | "skill_failed"
  | "skill_empty_output"
  | "skill_missing_report";

export type AgentListResponseParams = { agents: Array<TuiAgentInfo> };

export type AgentReportParams = {
  report_type: ReportType;
  agent_type: Agent;
  agent_id: string;
  agent_number?: string;
  title: string;
  content: string;
  summary?: string;
  timestamp: string;
  preset_options: Array<string>;
  /**
   * For `report_type: "query"`: whether `preset_options` are mutually
   * exclusive (single) or pick-any (multiple). Omit ⇒ single.
   */
  selection_mode?: ReportSelection;
  /**
   * For `report_type: "query"`: whether the recipient may type a free-form
   * answer in addition to (or instead of) picking presets. Omit ⇒ true
   * when `report_type == Query`, false otherwise.
   */
  allow_custom_reply?: boolean;
  /**
   * Subset of `preset_options` the agent suggests. Empty when no
   * recommendation is offered.
   */
  recommended_options: Array<string>;
  model_name?: string;
  token_usage?: [number, number];
  skill_count?: number;
  mcp_count?: number;
  next_route?: RouteInfo;
  stream?: LlmStream;
  error?: StructuredAgentError;
};

/**
 * Reply payload for an inquiry (`report_type: "query"`) report.
 *
 * Wire method: `Tui.AgentReportReply` (server-bound). `report_id` mirrors
 * the `agent_id` of the originating `AgentReportParams` so the upstream can
 * correlate without keeping a separate consultation registry.
 */
export type AgentReportReplyParams = {
  report_id: string;
  selected_options: Array<string>;
  custom_answer?: string;
  timestamp: string;
};

export type AgentResponseParams = {
  agent_type: Agent;
  agent_id: string;
  agent_number?: string;
  content: string;
  timestamp: string;
  parent_id?: string;
};

export type AgentStatus =
  | "Initializing"
  | "Online"
  | "Busy"
  | "Offline"
  | "Error";

export type AgentStreamingChunkParams = {
  agent_type: Agent;
  agent_id: string;
  agent_number?: string;
  chunk: string;
  is_done: boolean;
  timestamp: string;
  task_id?: string;
  chunk_kind?: StreamChunkKind;
};

export type AlarmThresholdInfo = {
  ll?: number;
  l?: number;
  h?: number;
  hh?: number;
};

export type ApiKeyInfoResponseParams = { info: KeyInfo };

export type AuthChangePasswordResponseParams = { ok: boolean; error?: string };

export type AuthDeleteUserResponseParams = { ok: boolean; error?: string };

export type AuthGetUserResponseParams = {
  ok: boolean;
  user?: UserProfileSummary;
  error?: string;
};

export type AuthListUsersResponseParams = {
  ok: boolean;
  users?: Array<UserProfileSummary>;
  error?: string;
};

export type AuthLoginResponseParams = {
  ok: boolean;
  token?: string;
  session_id?: string;
  user_id?: string;
  username?: string;
  display_name?: string;
  role?: string;
  error?: string;
};

export type AuthRegisterResponseParams = {
  ok: boolean;
  user_id?: string;
  username?: string;
  error?: string;
};

export type BaseAckParams = { message_id: string };

export type BaseErrorParams = { code: string; message: string };

export type BaseHeartbeatParams = { timestamp: bigint };

export type ClientCapability =
  | "file_relay"
  | "terminal"
  | "screen_capture"
  | "noa_workspace";

export type ClientNodeInfo = {
  hostname: string;
  os: string;
  workspace_root?: string;
  user_id?: string;
};

export type CompletionOutcome = "None" | "Reported" | "Failed";

export type ConfiguredProviderInfo = {
  provider_name: string;
  display_name: string;
  api_endpoint?: string;
  default_model: string;
  is_enabled: boolean;
};

export type ConfiguredProvidersListParams = {
  providers: Array<ConfiguredProviderInfo>;
};

export type ConnectHandshakeParams = {
  token: string;
  session_id?: string;
  capabilities: Array<ClientCapability>;
  node_info?: ClientNodeInfo;
  /**
   * Stringified UUID — kept as a string on the wire so consumers
   * don't need a UUID parser to round-trip the JSON-RPC payload.
   */
  workspace_id?: string;
};

export type ContainerInfo = {
  id: string;
  name: string;
  status: ContainerStatus;
  cpu_usage: number;
  memory_mb: bigint;
  image: string;
  agent_type?: string;
  parent_id?: string;
  branch_level: number;
  is_cosmos: boolean;
  branch?: string;
  is_read_only: boolean;
  badge?: string;
  current_skill?: string;
  workspace_id?: string;
  workspace_path?: string;
  git_remote_url?: string;
  git_branch?: string;
};

export type ContainerLogEntryParams = {
  instance_uuid: string;
  entry: LogEntryData;
};

export type ContainerSnapshotData = {
  version: bigint;
  timestamp: bigint;
  containers: Array<ContainerInfo>;
};

export type ContainerSnapshotParams = { snapshot: ContainerSnapshotData };

export type ContainerStatus =
  | "created"
  | "running"
  | "paused"
  | "restarting"
  | "removing"
  | "exited"
  | "dead"
  | "unknown";

export type CustomAgentInfo = {
  name: string;
  display_name: string;
  description: string;
  skills_count: number;
  source: string;
  version?: string;
  last_updated?: string;
};

export type CustomAgentListResponseParams = { agents: Array<CustomAgentInfo> };

/**
 * Dashboard layout — a collection of views arranged in a grid.
 */
export type DashboardLayout = {
  /**
   * Workspace ID this dashboard belongs to.
   */
  workspace_id: string;
  /**
   * Dashboard name.
   */
  name: string;
  /**
   * All view instances in this dashboard.
   */
  views: Array<ViewInstance>;
  /**
   * Grid columns count (0 = auto).
   */
  grid_columns: number;
};

/**
 * Push a dashboard layout update to connected clients.
 */
export type DashboardLayoutPushParams = { layout: DashboardLayout };

export type DiscoveryPhase =
  | "TransportScan"
  | "ProtocolIdentify"
  | "DataModelScan"
  | "SemanticInference"
  | "ManifestGeneration"
  | "ManifestValidation"
  | "Complete";

export type DiscoveryProgressEvent = {
  session_id: string;
  phase: DiscoveryPhase;
  message: string;
  found_devices: number;
  progress_percent: number;
  raw_findings?: JsonValue;
};

export type DiscoveryProgressPushParams = { event: DiscoveryProgressEvent };

export type EmbeddingModel =
  | "OpenAiSmall"
  | "OpenAiLarge"
  | "OpenAiAda"
  | "Custom";

export type EndpointValidatedParams = {
  provider_name: string;
  is_reachable: boolean;
  latency_ms?: bigint;
  error?: string;
};

export type EntrypointApiConfigInfo = {
  protocol: string;
  base_url: string;
  chat_endpoint: string;
  models_endpoint?: string;
  auth_type: string;
  auth_header?: string;
  env_var: string;
};

export type EntrypointConfigInfo = {
  id: string;
  name: { [key in string]: string };
  type: string;
  billing_type: string;
  plan_tier: string;
  api: EntrypointApiConfigInfo;
  defaults: EntrypointDefaultsInfo;
  quotas: Array<QuotaInfo>;
  models: Array<string>;
};

export type EntrypointDefaultsInfo = {
  deep: Array<string>;
  normal: Array<string>;
  basic: Array<string>;
  max_concurrent: MaxConcurrentInfo;
};

export type GetKnowledgeBaseResponseParams = {
  knowledge_base: KnowledgeBaseInfo | null;
};

export type GlobalSnapshotData = {
  version: bigint;
  timestamp: bigint;
  agents: Array<TuiAgentInfo>;
  containers: Array<ContainerInfo>;
  active_tasks: Array<TaskInfo>;
};

export type GlobalSnapshotParams = { snapshot: GlobalSnapshotData };

export type HandshakeAckParams = { ok: boolean; error?: string };

export type IndustrialAlarmAckParams = {
  station_id: string;
  address: string;
  acknowledged_by: string;
};

export type IndustrialAlarmEvent = {
  station_id: string;
  protocol: string;
  address: string;
  field_name: string;
  level: IndustrialAlarmLevel;
  value: number;
  threshold: number;
  unit: string;
  breached: boolean;
  timestamp: string;
};

export type IndustrialAlarmLevel =
  | "Log"
  | "LowLow"
  | "Low"
  | "High"
  | "HighHigh"
  | "RateOfChange"
  | "Emergency";

export type IndustrialAlarmPushParams = { alarm: IndustrialAlarmEvent };

export type IndustrialSensorReading = {
  station_id: string;
  protocol: string;
  address: string;
  name: string;
  raw_value: number;
  scaled_value: number;
  unit: string;
  quality: string;
  timestamp: string;
};

export type IndustrialStationInfo = {
  station_id: string;
  protocol: string;
  connection: string;
  device_class: string;
  vendor?: string;
  model?: string;
  firmware?: string;
  status: string;
  fields: Array<StationFieldInfo>;
};

export type IndustrialTelemetryBatch = {
  readings: Array<IndustrialSensorReading>;
  station_id: string;
  timestamp: string;
};

export type IndustrialTelemetryPushParams = { batch: IndustrialTelemetryBatch };

export type IndustrialTopologyParams = {
  stations: Array<IndustrialStationInfo>;
};

export type KbGenericResponseParams = {
  ok: boolean;
  error?: string;
  id?: string;
};

export type KeyInfo = {
  provider: string;
  display_name: string;
  has_key: boolean;
  created_at: string;
  updated_at: string;
  source: string;
};

export type KeysListResponseParams = { keys: Array<KeyInfo> };

export type KnowledgeBaseInfo = {
  id: string;
  name: string;
  description?: string;
  status: KnowledgeBaseStatus;
  embedding_model?: EmbeddingModel;
  custom_embedding_endpoint?: string;
  document_count: number;
  subscription_count: number;
  tags: Array<string>;
  created_at: string;
  updated_at: string;
};

export type KnowledgeBaseStatus =
  | "Uninitialized"
  | "Indexing"
  | "Ready"
  | "Error";

export type Layer2AgentInfo = {
  name: string;
  description: string;
  mcp_count: number;
  skills_count: number;
  languages: Array<string>;
  enabled: boolean;
};

export type Layer2AgentListResponseParams = { agents: Array<Layer2AgentInfo> };

export type Layer2AgentMcpResponseParams = {
  agent_name: string;
  tools: Array<Layer2McpToolInfo>;
};

export type Layer2AgentSkillsResponseParams = {
  agent_name: string;
  skills: Array<Layer2SkillInfo>;
};

export type Layer2McpPromptResponseParams = {
  agent_name: string;
  tool: string;
  lang: string;
  content: string;
  name: string;
};

export type Layer2McpToolInfo = {
  name: string;
  description: string;
  languages: Array<string>;
  references_layer1: Array<string>;
  references_layer2: Array<string>;
  related_items: Array<string>;
  referenced_by_items: Array<string>;
};

export type Layer2SkillInfo = {
  name: string;
  description: string;
  languages: Array<string>;
  references_layer1: Array<string>;
  references_layer2: Array<string>;
  related_items: Array<string>;
  referenced_by_items: Array<string>;
};

export type Layer2SkillPromptResponseParams = {
  agent_name: string;
  skill: string;
  lang: string;
  content: string;
  name: string;
};

export type ListKnowledgeBasesResponseParams = {
  knowledge_bases: Array<KnowledgeBaseInfo>;
};

export type LlmProviderConfiguredParams = {
  provider_name: string;
  success: boolean;
  error?: string;
};

export type LlmStream = { segments: Array<StreamSegment> };

export type LogEntryData = {
  source: string;
  instance_uuid?: string;
  level: string;
  target?: string;
  message: string;
  fields: Record<string, unknown>;
  created_at: string;
};

export type MaxConcurrentInfo = { deep: number; normal: number; basic: number };

export type McpToolResultParams = {
  tool_name: string;
  call_id: string;
  parameters_summary?: string;
  result: string;
  agent_type: Agent;
  agent_id: string;
  agent_number?: string;
  success: boolean;
  duration_ms?: bigint;
};

export type ModelFsInfo = {
  id: string;
  name: string;
  provider_id: string;
  context_window: bigint;
  max_output_tokens: bigint;
  supports_vision: boolean;
  supports_function_calling: boolean;
  supports_streaming: boolean;
  supports_reasoning: boolean;
  tags: Array<string>;
  pricing?: ModelFsPricing;
  rate_multiplier?: number;
  rate_rules: Array<RateRuleInfo>;
};

export type ModelFsInfoParams = { models: Array<ModelFsInfo> };

export type ModelFsPricing = {
  input_per_million?: number;
  output_per_million?: number;
  cached_per_million?: number;
};

export type ModelProviderConfigUpdatedParams = {
  provider_name: string;
  success: boolean;
  error?: string;
};

export type ModelTier = "Deep" | "Normal" | "Basic";

export type NoaAuthRequestParams = {
  workspace_id: string;
  branches: Array<string>;
  suggested_branch: string;
  reason: string;
};

export type NoaAuthResponseParams = {
  workspace_id: string;
  selected_branch: string;
  branch_base?: string;
  approved: boolean;
};

export type NoaEvent = {
  event_id: string;
  event_type: string;
  timestamp: string;
  file_path?: string;
  content_hash?: string;
  metadata?: unknown;
};

export type NoaEventSyncAckParams = {
  workspace_id: string;
  last_event_id: string;
};

export type NoaEventSyncParams = {
  workspace_id: string;
  events: Array<NoaEvent>;
  direction?: string;
};

export type NoaHandshakeResponseParams = {
  workspace_id: string;
  repo_id: string;
  current_branch: string;
  noa_initialized: boolean;
  gitignore_updated: boolean;
};

export type NoaReadyParams = {
  workspace_id: string;
  branch: string;
  snapshot_id: string;
};

export type OrchestrationStatusParams = {
  stage: SkillStage;
  agent: string;
  agent_type?: Agent;
  tool_name?: string;
  call_id?: string;
  parent_agent?: string;
  parameters_summary?: string;
};

export type PeriodType = "Hour5" | "Day7" | "Month1";

export type PingParams = { timestamp: bigint };

export type PolemosDeviceInfo = {
  node_id: string;
  name: string;
  address: string;
  status: string;
  workspace_path?: string;
  ide_id?: string;
};

export type PolemosDeviceListParams = { devices: Array<PolemosDeviceInfo> };

export type ProviderCapabilitiesInfo = {
  streaming: boolean;
  function_calling: boolean;
  vision: boolean;
  reasoning: boolean;
};

export type ProviderDeletedParams = {
  provider_name: string;
  success: boolean;
  error?: string;
};

export type ProviderEditedParams = {
  provider_name: string;
  success: boolean;
  error?: string;
};

export type ProviderFsInfo = {
  id: string;
  name: { [key in string]: string };
  protocol: string;
  category: string;
  base_url?: string;
  entry_points: Array<EntrypointConfigInfo>;
  models: Array<ModelFsInfo>;
  capabilities: ProviderCapabilitiesInfo;
  limits: ProviderLimitsInfo;
  pricing_model: string;
};

export type ProviderFsInfoParams = { providers: Array<ProviderFsInfo> };

export type ProviderLimitsInfo = {
  max_concurrent: number;
  rate_limit_per_minute?: number;
  timeout_seconds: bigint;
};

export type ProviderRenamedParams = {
  provider_name: string;
  new_display_name: string;
  success: boolean;
  error?: string;
};

export type QuotaInfo = {
  data_limit: bigint;
  period_hours?: number;
  period_days?: number;
  billing_metric: string;
};

export type RateRuleInfo = {
  timezone_offset: number;
  peak_start: number;
  peak_end: number;
  peak_multiplier: number;
  off_peak_multiplier: number;
};

export type RegisterPolemosDeviceResponseParams = {
  success: boolean;
  error?: string;
  device?: PolemosDeviceInfo;
};

/**
 * Selection semantics for an inquiry (`report_type: "query"`) report's
 * `preset_options`. Defaults to `Single` when omitted.
 */
export type ReportSelection = "single" | "multiple";

export type ReportType =
  | "query"
  | "human"
  | "reply"
  | "skill_terminal"
  | "skill_step"
  | "next_action_fallback"
  | "chain_max_depth"
  | "chain_cycle"
  | "skill_failed"
  | "skill_empty_output"
  | "skill_missing_report"
  | "error"
  | "system"
  | "pending";

export type RequestNoaHandshakeParams = {
  workspace_id: string;
  remote_name: string;
  remote_path: string;
};

export type RequestState =
  | "Idle"
  | "Waiting"
  | "Streaming"
  | "Retrying"
  | "WaitingTool";

export type RetryReason = "EmptyOutput" | "ReportNotCaptured" | {
  "LlmError": { message: string };
};

export type RouteInfo = {
  direction: string;
  target: string;
  target_token?: string;
};

export type ScepterIdentityParams = { device_id: string };

export type ServerLogEntryParams = { entry: LogEntryData };

export type SkillStage =
  | { "Started": string }
  | { "Done": string }
  | { "Complete": string }
  | { "Failed": string }
  | { "ToolCall": string }
  | { "Retrying": [string, number, number, RetryReason | null] }
  | { "TryingModel": [string, string] }
  | { "ModelFailed": [string, string, string] }
  | { "Nudging": string };

export type StationFieldInfo = {
  address: string;
  name: string;
  data_type: string;
  unit?: string;
  alarm?: AlarmThresholdInfo;
  current_value?: number;
};

export type StreamChunkKind = "Text" | "Thinking" | "DeepThinking";

export type StreamSegment =
  | { "Text": { text: string; message_id?: string } }
  | { "Thinking": { text: string; message_id?: string } }
  | { "DeepThinking": { text: string; message_id?: string } }
  | {
    "McpCall": {
      tool_name: string;
      call_id: string;
      params: unknown;
      agent_type?: string;
      message_id?: string;
    };
  }
  | {
    "McpResult": {
      tool_name: string;
      call_id: string;
      success: boolean;
      data: unknown;
      duration_ms?: bigint;
      agent_type?: string;
      message_id?: string;
    };
  };

export type StructuredAgentError = {
  code: AgentErrorCode;
  detail?: string;
  context: { [key in string]: string };
};

export type SubscribeCustomAgentResponseParams = {
  success: boolean;
  error?: string;
  agent?: CustomAgentInfo;
  skills: Array<string>;
  permissions: Array<string>;
};

export type SubscribeLogsResponseParams = {
  ok: boolean;
  error?: string;
  entries: Array<LogEntryData>;
};

export type SwitchWorkspaceResponseParams = {
  success: boolean;
  workspace_id: string;
  error?: string;
};

export type TaskCreatedParams = {
  task_id: string;
  issue_id: string;
  title: string;
  description?: string;
  assigned_agent?: Agent;
  parent_task_id?: string;
  badge?: string;
  tags?: Array<string>;
};

export type TaskInfo = {
  id: string;
  issue_id: string;
  title: string;
  status: TaskStatus;
  progress: number;
  assigned_agent?: string;
};

export type TaskStatus =
  | "not_started"
  | "in_progress"
  | "paused"
  | "completed"
  | "failed"
  | "warning"
  | { "waiting": { deadline: string; handle: string } };

export type TaskStatusUpdateParams = {
  task_id: string;
  status: TaskStatus;
  progress: number;
};

export type TasksSnapshotData = {
  version: bigint;
  timestamp: bigint;
  tasks: Array<TaskInfo>;
};

export type TasksSnapshotParams = { snapshot: TasksSnapshotData };

export type TuiAgentInfo = {
  agent_type: Agent;
  agent_number?: string;
  agent_uuid?: string;
  agent_id: string;
  status: AgentStatus;
  llm_working: boolean;
  cpu_usage: number;
  memory_mb: bigint;
  parent_id?: string;
  work_status?: WorkStatus;
  current_model?: string;
  model_tier?: ModelTier;
  llm_handle?: string;
  token_usage?: [number, number];
  mcp_tool_calls: number;
  request_state: RequestState;
  completion_outcome: CompletionOutcome;
  retry_count: number;
  max_retries: number;
};

export type UnsubscribeCustomAgentResponseParams = {
  success: boolean;
  error?: string;
};

export type UnsubscribeLogsResponseParams = { ok: boolean; error?: string };

export type UsagePeriodData = {
  user_id: string;
  period_type: PeriodType;
  used_tokens: bigint;
  cost: number;
  start_time: string;
  remaining_tokens?: bigint;
  remaining_cost?: number;
};

export type UsagePeriodResponseParams = { data: Array<UsagePeriodData> };

export type UserConfigResponseParams = { config: UserInfoConfig };

export type UserInfoConfig = {
  preferred_language: string;
  default_models: { [key in string]: string };
  enabled_providers: Array<string>;
  enabled_models: Array<string>;
  model_priorities: { [key in string]: number };
  auto_import_from_env: Array<string>;
};

export type UserProfileSummary = {
  id: string;
  username: string;
  email: string;
  display_name: string;
  role: string;
  is_active: boolean;
};

/**
 * View data update — incremental data push for a specific view.
 */
export type ViewDataPushParams = {
  /**
   * Target view ID.
   */
  view_id: string;
  /**
   * Data payload (format depends on ViewKind).
   */
  data: JsonValue;
  /**
   * Whether this is a full replacement or incremental update.
   */
  full_replace: boolean;
};

/**
 * A view instance — one panel in the dashboard.
 */
export type ViewInstance = {
  /**
   * Unique view ID within the workspace.
   */
  view_id: string;
  /**
   * What kind of renderer to use.
   */
  kind: ViewKind;
  /**
   * Display title.
   */
  title: string;
  /**
   * Data source identifier — what the view is bound to.
   * Examples: "industrial:station:19", "chat:conversation:abc",
   * "kanban:project:xyz", "media:flow:comfyui"
   */
  data_source: string;
  /**
   * View-specific configuration (JSON, interpreted by the renderer).
   */
  config: JsonValue;
  /**
   * Layout position (grid area, tab order, etc.).
   */
  layout?: ViewLayout;
};

/**
 * View type identifier — determines which frontend renderer handles the view.
 */
export type ViewKind =
  | "IndustrialScada"
  | "Chat"
  | "Kanban"
  | "Gantt"
  | "DataTable"
  | "MediaFlow"
  | "FileExplorer"
  | "Custom";

/**
 * Layout descriptor for a view within the dashboard grid.
 */
export type ViewLayout = {
  /**
   * Grid column start (1-based).
   */
  col: number;
  /**
   * Grid row start (1-based).
   */
  row: number;
  /**
   * Column span.
   */
  col_span: number;
  /**
   * Row span.
   */
  row_span: number;
  /**
   * Minimum width in pixels.
   */
  min_width?: number;
  /**
   * Minimum height in pixels.
   */
  min_height?: number;
};

export type WebUiControlResponseParams = {
  command: string;
  success: boolean;
  message: string;
  url?: string;
};

export type WebUiStatusParams = {
  running: boolean;
  url?: string;
  container_id?: string;
};

export type WorkStatus =
  | "Thinking"
  | "StreamingResponse"
  | { "Executing": { skill_name: string } }
  | { "Retrying": { retry_count: number; max_retries: number } }
  | "Nudging"
  | "Completed"
  | "RequestFailed"
  | "Failed"
  | "ToolLoopTerminated"
  | "CallingTool";

export type WorkspaceStatusParams = {
  workspace_id: string;
  display_name?: string;
  connection_kind: string;
  resolved_path?: string;
  remote_url?: string;
  branch?: string;
  host_id?: string;
};

export type WriteApprovalRequest = {
  /**
   * Mirrors `_shared_state_sync::WriteApprovalRequest::request_id`. The
   * operator UI echoes this back in `industrial.approveWrite` so the
   * resolver can match the response to the pending producer oneshot.
   */
  request_id: string;
  station_id: string;
  protocol: string;
  address: string;
  field_name: string;
  current_value: number;
  proposed_value: number;
  unit: string;
  reason: string;
  agent: string;
  risk_level: string;
};

export type WriteApprovalRequestParams = { request: WriteApprovalRequest };

export type WriteApprovalResponseParams = {
  request_id: string;
  approved: boolean;
  approved_by: string;
  modified_value?: number;
};

export type YoloConfigResponseParams = { tiers: Array<YoloTierConfig> };

export type YoloCycleCompleteParams = {
  loop_count: bigint;
  duration_ms: bigint;
};

export type YoloCycleStepParams = {
  skill: string;
  loop_count: bigint;
  status: string;
  token_usage?: [number, number];
  model_name?: string;
};

export type YoloRunTierNowResponseParams = { ok: boolean; error?: string };

export type YoloSetTierIntervalResponseParams = { ok: boolean; error?: string };

export type YoloStartResponseParams = { ok: boolean; error?: string };

export type YoloStatusResponseParams = {
  active: boolean;
  loop_count: bigint;
  started_at?: string;
  current_cycle?: string;
  tiers: Array<YoloTierStatus>;
};

export type YoloStopResponseParams = { ok: boolean; error?: string };

export type YoloTaskResult = {
  success: boolean;
  duration_ms: bigint;
  completed_at: string;
  error?: string;
};

export type YoloTaskStatus = {
  agent: string;
  skill: string;
  enabled: boolean;
  last_result?: YoloTaskResult;
};

export type YoloTaskTier = "realtime" | "periodic" | "daily" | "strategic";

export type YoloTerminateResponseParams = { ok: boolean; error?: string };

export type YoloTierConfig = {
  tier: YoloTaskTier;
  enabled: boolean;
  interval_secs: bigint;
  tasks: Array<YoloTierTaskConfig>;
};

export type YoloTierStatus = {
  tier: YoloTaskTier;
  enabled: boolean;
  interval_secs: bigint;
  last_run_at?: string;
  next_run_at?: string;
  tasks: Array<YoloTaskStatus>;
};

export type YoloTierTaskConfig = {
  agent: string;
  skill: string;
  enabled: boolean;
};

export type YoloUpdateTaskResponseParams = { ok: boolean; error?: string };
