// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "../serde_json/JsonValue";

export type AlarmThresholdInfo = { ll?: number, l?: number, h?: number, hh?: number, };

export type DiscoveryPhase = "TransportScan" | "ProtocolIdentify" | "DataModelScan" | "SemanticInference" | "ManifestGeneration" | "ManifestValidation" | "Complete";

export type DiscoveryProgressEvent = { session_id: string, phase: DiscoveryPhase, message: string, found_devices: number, progress_percent: number, raw_findings?: JsonValue, };

export type DiscoveryProgressPushParams = { event: DiscoveryProgressEvent, };

export type IndustrialAlarmAckParams = { station_id: string, address: string, acknowledged_by: string, };

export type IndustrialAlarmEvent = { station_id: string, protocol: string, address: string, field_name: string, level: IndustrialAlarmLevel, value: number, threshold: number, unit: string, breached: boolean, timestamp: string, };

export type IndustrialAlarmLevel = "Log" | "LowLow" | "Low" | "High" | "HighHigh" | "RateOfChange" | "Emergency";

export type IndustrialAlarmPushParams = { alarm: IndustrialAlarmEvent, };

export type IndustrialSensorReading = { station_id: string, protocol: string, address: string, name: string, raw_value: number, scaled_value: number, unit: string, quality: string, timestamp: string, };

export type IndustrialStationInfo = { station_id: string, protocol: string, connection: string, device_class: string, vendor?: string, model?: string, firmware?: string, status: string, fields: Array<StationFieldInfo>, };

export type IndustrialTelemetryBatch = { readings: Array<IndustrialSensorReading>, station_id: string, timestamp: string, };

export type IndustrialTelemetryPushParams = { batch: IndustrialTelemetryBatch, };

export type IndustrialTopologyParams = { stations: Array<IndustrialStationInfo>, };

export type StationFieldInfo = { address: string, name: string, data_type: string, unit?: string, alarm?: AlarmThresholdInfo, current_value?: number, };

export type WriteApprovalRequest = { 
/**
 * Mirrors `_shared_state_sync::WriteApprovalRequest::request_id`. The
 * operator UI echoes this back in `industrial.approveWrite` so the
 * resolver can match the response to the pending producer oneshot.
 */
request_id: string, station_id: string, protocol: string, address: string, field_name: string, current_value: number, proposed_value: number, unit: string, reason: string, agent: string, risk_level: string, };

export type WriteApprovalRequestParams = { request: WriteApprovalRequest, };

export type WriteApprovalResponseParams = { request_id: string, approved: boolean, approved_by: string, modified_value?: number, };
