// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "../serde_json/JsonValue";

export type IndustrialAlarmAckParams = { station_id: string, address: string, acknowledged_by: string, };

/**
 * Fired on threshold breach (breached=true) or clear (breached=false).
 */
export type IndustrialAlarmEvent = { station_id: string, protocol: string, address: string, field_name: string, level: IndustrialAlarmLevel, value: number, threshold: number, unit: string, breached: boolean, timestamp: string, };

export type IndustrialAlarmHistory = { entries: Array<IndustrialAlarmHistoryEntry>, total: bigint, };

/**
 * One entry in the historical alarm log (last N days).
 */
export type IndustrialAlarmHistoryEntry = { station_id: string, protocol: string, address: string, field_name: string, level: IndustrialAlarmLevel, value: number, threshold: number, unit: string, breached: boolean, timestamp: string, 
/**
 * Whether an operator acknowledged the alarm, and when.
 */
acknowledged: boolean, acknowledged_at: string | null, acknowledged_by: string | null, };

/**
 * Severity ordering matches ISA-18.2 alarm severity.
 */
export type IndustrialAlarmLevel = "Log" | "LowLow" | "Low" | "High" | "HighHigh" | "RateOfChange" | "Emergency";

export type IndustrialAlarmPushParams = { alarm: IndustrialAlarmEvent, };

export type IndustrialAlarmThresholds = { ll: number | null, l: number | null, h: number | null, hh: number | null, };

/**
 * Phases of an evernight discovery scan. Ordered by typical progress.
 */
export type IndustrialDiscoveryPhase = "TransportScan" | "ProtocolIdentify" | "DataModelScan" | "SemanticInference" | "ManifestGeneration" | "ManifestValidation" | "Complete";

export type IndustrialDiscoveryProgress = { session_id: string, phase: IndustrialDiscoveryPhase, message: string, found_devices: bigint, progress_percent: number, raw_findings: JsonValue | null, };

export type IndustrialDiscoveryProgressPushParams = { event: IndustrialDiscoveryProgress, };

/**
 * A single live reading from an industrial field (e.g. pressure cell on a
 * Modbus register, S7 DBX bit). Pushed by scepter at the scan cycle of the
 * underlying transport.
 */
export type IndustrialSensorReading = { station_id: string, protocol: string, address: string, name: string, raw_value: number, scaled_value: number, unit: string, quality: string, timestamp: string, };

export type IndustrialStationField = { address: string, name: string, data_type: string, unit: string | null, alarm: IndustrialAlarmThresholds | null, current_value: number | null, };

export type IndustrialStationInfo = { station_id: string, protocol: string, connection: string, device_class: string, vendor: string | null, model: string | null, firmware: string | null, status: string, fields: Array<IndustrialStationField>, };

export type IndustrialTelemetryBatch = { readings: Array<IndustrialSensorReading>, station_id: string, timestamp: string, };

export type IndustrialTelemetryPushParams = { batch: IndustrialTelemetryBatch, };

export type IndustrialTopologyParams = { stations: Array<IndustrialStationInfo>, };

export type WriteApprovalRequest = { 
/**
 * Unique id assigned by the producer (orexis). The operator UI echoes it
 * back in `industrial.approveWrite` so scepter's resolver can match the
 * response to the pending oneshot. `#[serde(default)]` keeps the wire
 * format backward-compatible with older push events that predate it.
 */
request_id: string, station_id: string, protocol: string, address: string, field_name: string, current_value: number, proposed_value: number, unit: string, reason: string, agent: string, risk_level: WriteApprovalRisk, };

export type WriteApprovalRequestParams = { request: WriteApprovalRequest, };

export type WriteApprovalResponseParams = { request_id: string, approved: boolean, approved_by: string, modified_value: number | null, };

/**
 * Operator confirmation gate for safety-critical PLC writes.
 */
export type WriteApprovalRisk = "safe" | "caution" | "critical";
