// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AnomalyDetectParams = {
  values: Array<number>;
  method: string | null;
  threshold: number | null;
  timestamps: Array<bigint> | null;
  window_size: number | null;
};

export type AnomalyInfo = {
  index: number;
  value: number;
  expected: number;
  deviation: number;
  timestamp: bigint | null;
  severity: string;
};

export type AnomalyResult = {
  anomalies: Array<AnomalyInfo>;
  total_points: number;
  anomaly_count: number;
  anomaly_ratio: number;
  method: string;
  threshold: number;
};

export type CausalReasonParams = {
  target: string;
  target_values: Array<number>;
  candidates: { [key in string]: Array<number> } | null;
  max_lag: number | null;
};

export type CausalReasonResult = {
  correlations: Array<CorrelationInfo>;
  hypotheses: Array<Hypothesis>;
  recommended_actions: Array<string>;
  confidence: number;
};

export type CorrelationInfo = {
  variable: string;
  correlation: number;
  lag: number;
  direction: string;
};

export type Hypothesis = {
  cause: string;
  effect: string;
  strength: number;
  reasoning: string;
};

export type LlmChatParams = {
  prompt: string;
  model: string | null;
  system_prompt: string | null;
};

export type LlmChatResult = { model: string; tokens: string; response: string };

export type MediaAssetItem = {
  asset_id: string;
  asset_type: string;
  source_url: string;
  metadata: Record<string, unknown>;
  tags: Array<string>;
  created_at: string;
};

export type MediaAssetRegisterResult = {
  asset_id: string;
  asset_type: string;
  source_url: string;
  tags: Array<string>;
};

export type MediaAssetRetrieveResult = {
  count: number;
  assets: Array<MediaAssetItem>;
};

export type RagDbDeleteParams = { id: string };

export type RagDbDeleteResult = { doc_id: string };

export type RagDbReadParams = {
  query_embedding: Array<number>;
  limit: number | null;
};

export type RagDbReadResult = { count: number; results: Array<RagDocResult> };

export type RagDbStatsParams = Record<symbol, never>;

export type RagDbStatsResult = {
  total_documents: number;
  total_media_assets: number;
  embedding_dimensions: number | null;
  storage_backend: string;
};

export type RagDbWriteParams = {
  content: string;
  embedding: Array<number> | null;
  metadata: Record<string, unknown> | null;
  source: string | null;
};

export type RagDbWriteResult = {
  doc_id: string;
  embedding_dim: number;
  content: string;
};

export type RagDocResult = {
  doc_id: string;
  similarity: number;
  content: string;
  source: string | null;
  metadata: Record<string, unknown> | null;
};

export type TranslateReportParams = {
  content: string;
  target_language: string | null;
};

export type TranslateReportResult = {
  target_language: string;
  original_length: number;
  translated_length: number;
  translation: string;
};

export type WorkspaceIndexParams = {
  workspace_root: string;
  full_rebuild: boolean | null;
};

export type WorkspaceIndexResult = {
  total_files: number;
  total_chunks: number;
  total_bytes: number;
  duration_ms: bigint;
};

export type WorkspaceSearchDoc = {
  doc_id: string;
  file_path: string;
  start_line: number;
  end_line: number;
  language: string;
  similarity: number;
  snippet: string;
};

export type WorkspaceSearchParams = { query: string; limit: number | null };

export type WorkspaceSearchResult = {
  count: number;
  results: Array<WorkspaceSearchDoc>;
};

export type WorkspaceStatusParams = Record<symbol, never>;

export type WorkspaceStatusResult = {
  total_files: number;
  total_chunks: number;
  total_bytes: number;
  last_indexed: string | null;
  is_indexing: boolean;
};
