// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConsultationStatus } from "../enums";

export type ConsumeInjectedPromptsParams = { target_badge: string, };

export type ConsumeInjectedPromptsResult = { consumed: Array<InjectedPromptView>, count: number, };

export type DeliverMessageParams = { target_badge: string, message_type: string, content: string, suggested_skill: string | null, priority: string | null, source_badge: string | null, };

export type DeliverMessageResult = { todo_id: string, title: string, target_badge: string, status: string, };

export type FileObserverView = { agent_type: string, instance_badge: string | null, observation_type: string, registered_at: string, };

export type ForkContainerOnNextActionParams = { container_id: string, branch_prefix: string | null, reason: string | null, };

export type ForkContainerRegistrationResult = { status: string, message: string, container_id: string, reason: string, };

export type InjectUserPromptParams = { target_badge: string, message: string, source_badge: string | null, suggested_skill: string | null, };

export type InjectUserPromptResult = { target_badge: string, injected: boolean, prompt_count: number, };

export type InjectedPromptView = { source_badge: string, message: string, suggested_skill: string, injected_at: string, };

export type ListFileObserversParams = { file_path: string, };

export type ListFileObserversToolResult = { file_path: string, observers: Array<FileObserverView>, };

export type NotifyFileOperationParams = { file_path: string, agent_type: string, instance_badge: string | null, observation_type: string | null, };

export type NotifyFileOperationToolResult = { file_path: string, observers_count: number, };

export type TaskCancelResult = { task_id: string, status: ConsultationStatus, };

export type TaskEntry = { id: string, schedule: Record<string, unknown>, status: ConsultationStatus, created_at: string, };

export type TaskListResult = { count: number, tasks: Array<TaskEntry>, };

export type TaskScheduleResult = { task_id: string, schedule: Record<string, unknown>, status: ConsultationStatus, timer_info: string | null, };

export type TriggerAddResult = { trigger_id: string, trigger_type: string, event: Record<string, unknown>, };

export type TriggerEntry = { id: string, trigger_type: string, event: Record<string, unknown>, created_at: string, };

export type TriggerListResult = { count: number, triggers: Array<TriggerEntry>, };

export type TriggerRemoveResult = { trigger_id: string, };

export type UnregisterFileOperationResult = { status: string, };
