// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ClearTodoParams = {
  workspace_id: string | null;
  dry_run: boolean | null;
  status: string | null;
};

export type CreateTodoParams = {
  title: string;
  workspace_id: string | null;
  user_id: string | null;
  parent_id: string | null;
  description: string | null;
  metadata: { [key in string]: string } | null;
  claimed_by: string | null;
};

export type DeleteTodoParams = { todo_id: string; workspace_id: string | null };

export type ListTodoParams = {
  workspace_id: string | null;
  parent_id: string | null;
  status: string | null;
  tree: boolean | null;
  view: string | null;
};

export type MoveTodoParams = {
  todo_id: string;
  new_parent_id: string | null;
  sort_order: number | null;
};

export type ReportHumanParams = {
  summary: string;
  body: string | null;
  text: string | null;
  mode: string | null;
  content: string | null;
};

export type ReportParams = {
  text: string | null;
  summary: string | null;
  body: string | null;
  content: string | null;
};

export type ReportResult = { summary: string };

export type TodoClearDryRunResult = {
  dry_run: boolean;
  would_delete: number;
  items: Array<TodoClearItem>;
};

export type TodoClearItem = { id: string; title: string; status: string };

export type TodoClearResult = { deleted_count: bigint; success: boolean };

export type TodoCreateResult = {
  id: string;
  title: string;
  status: string;
  parent_id: string | null;
  created_at: string;
};

export type TodoDeleteResult = { deleted_id: string; success: boolean };

export type TodoListItem = {
  id: string;
  title: string;
  status: string;
  parent_id: string | null;
  claimed_by: string;
  created_at: string;
  updated_at: string;
  description: string | null;
  tags: Array<string>;
};

export type TodoListResult = { total: number; items: Array<TodoListItem> };

export type TodoMoveResult = {
  id: string;
  parent_id: string | null;
  sort_order: number;
  updated_at: string;
};

export type TodoTreeListResult = { total: number; tree: Array<TodoTreeNode> };

export type TodoTreeNode = {
  id: string;
  title: string;
  status: string;
  children: Array<TodoTreeNode>;
  depth: number;
  description: string | null;
  priority: string | null;
  tags: Array<string>;
};

export type TodoUpdateResult = {
  id: string;
  title: string;
  status: string;
  updated_at: string;
};

export type UpdateTodoParams = {
  todo_id: string;
  title: string | null;
  description: string | null;
  status: string | null;
  claimed_by: string | null;
  parent_id: string | null;
  metadata: { [key in string]: string } | null;
};
