// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConsultationStatus, ContainerOpStatus } from "../enums";

export type CheckWaitParams = { handle: string };

export type ContainerCreateResult = {
  image: string;
  container_id: string;
  name: string;
  network: string;
  status: ContainerOpStatus;
  volumes: Array<VolumeInfo>;
  seccomp_enabled: boolean;
};

export type ContainerFilterCriteria = {
  label?: { [key in string]: string } | null;
  name?: string | null;
  status?: Array<string> | null;
};

export type ContainerForkParams = {
  container_id: string;
  name: string | null;
  namespace_volume: string | null;
};

export type ContainerForkResult = {
  parent_container_id: string;
  new_container_id: string;
  branch_level: number;
  image: string;
  fallback: boolean;
  status: ContainerOpStatus;
};

export type ContainerInfoParams = { container_id: string };

export type ContainerInfoResult = {
  container_id: string;
  name: string;
  image: string;
  status: string;
  running: boolean;
  exit_code: bigint | null;
  ip_address: string;
  started_at: string;
  ports: Array<string>;
  env: Array<string>;
};

export type ContainerListItem = {
  name: string;
  image: string;
  status: string;
  id: string;
};

export type ContainerListParams = { filter?: ContainerFilterCriteria | null };

export type ContainerListResult = {
  total_count: number;
  containers: Array<ContainerListItem>;
};

export type ContainerRemoveParams = { container_id: string };

export type ContainerRemoveResult = {
  container_id: string;
  status: ContainerOpStatus;
};

export type ContainerSnapshotParams = { container_id: string };

export type ContainerSnapshotResult = {
  container_id: string;
  snapshot_id: string;
  image_id: string;
  image_name: string;
};

export type ContainerStartParams = { container_id: string };

export type ContainerStartResult = {
  container_id: string;
  status: ContainerOpStatus;
};

export type ContainerStopParams = { container_id: string };

export type ContainerStopResult = {
  container_id: string;
  status: ContainerOpStatus;
};

export type ExecOnContainerParams = {
  command: string;
  container_id: string | null;
  target_badge: string | null;
};

export type ExecResult = {
  container_id: string;
  command: string;
  exit_code: bigint | null;
  output: string;
  error: string;
};

export type GitPushBranchParams = {
  container_id: string;
  commit_message: string | null;
  branch: string | null;
};

export type GitPushResult = {
  container_id: string;
  branch: string;
  remote: string;
  commit_hash: string | null;
  pushed: boolean;
  output: string;
};

export type NewContainerToolParams = {
  image: string;
  name: string | null;
  env: { [key in string]: string } | null;
  volumes: Array<NewContainerVolumeMount> | null;
  network: string | null;
};

export type NewContainerVolumeMount = {
  source: string;
  target: string;
  read_only?: boolean | null;
};

export type SidecarDeliverResult = {
  todo_id: string;
  title: string;
  target_badge: string;
  status: ConsultationStatus;
  metadata: { [key in string]: string };
};

export type SidecarKillParams = { name: string };

export type SidecarSendParams = {
  name: string;
  method: string;
  params: Record<string, unknown> | null;
  timeout_secs: bigint | null;
};

export type SidecarSendResult = { name: string; sent: boolean };

export type SidecarSpawnParams = {
  name: string;
  cmd: Array<string> | null;
  language: string | null;
  framing: string | null;
  working_dir: string | null;
  env: { [key in string]: string } | null;
  idle_timeout_secs: bigint | null;
  ready_pattern: string | null;
  amphoreus_dir: string | null;
  agent_folder: string | null;
};

export type ToolchainEnsureParams = {
  profile_id: string;
  amphoreus_dir: string | null;
};

export type ToolchainEnsureResult = {
  profile_id: string;
  source_image: string;
  container_image: string;
  container_env: { [key in string]: string };
  container_volumes: Array<ToolchainVolumeSpec>;
};

export type ToolchainListParams = { amphoreus_dir: string | null };

export type ToolchainListResult = { profiles: Array<ToolchainProfileInfo> };

export type ToolchainProfileInfo = {
  id: string;
  display_name: string;
  source_image: string;
  image_pulled: boolean;
  volume_ready: boolean;
  available_tools: Array<string>;
  supported_languages: Array<string>;
};

export type ToolchainVolumeSpec = {
  host_path: string;
  container_path: string;
  read_only: boolean;
};

export type VolumeInfo = {
  host_path: string;
  container_path: string;
  read_only: boolean;
};

export type WaitParams = { seconds: bigint | null };
