// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * `Engine.BinaryAbort` notification params — cancels an in-flight
 * transfer; the receiver discards buffered bytes and returns to normal
 * RPC operation.
 */
export type EngineBinaryAbortParams = { transfer_id: string, reason: string, };

/**
 * `Engine.BinaryEnd` notification params — sent after the final binary
 * frame; the receiver validates and returns to normal RPC operation.
 */
export type EngineBinaryEndParams = { transfer_id: string, 
/**
 * Bytes actually received across all frames.
 */
bytes_received: bigint, 
/**
 * Whether the checksum matched (None when no checksum was announced).
 */
checksum_ok?: boolean, };

/**
 * `Engine.BinaryStart` notification params — the announce packet sent
 * BEFORE any binary frame. Every payload is labelled with a MIME type.
 */
export type EngineBinaryStartParams = { 
/**
 * Correlation id shared by announce / frames / finish.
 */
transfer_id: string, 
/**
 * MIME type of the whole payload (e.g. "audio/wav",
 * "application/octet-stream"). Empty means unspecified binary.
 */
mime: string, total_bytes: bigint, 
/**
 * Expected number of binary frames (for early truncation checks).
 */
chunk_count: number, 
/**
 * Optional SHA-256 hex digest of the payload.
 */
checksum?: string, 
/**
 * Optional association with a stream (generic streaming).
 */
stream_id?: string, };

/**
 * Static capability declaration supplied at handshake time.
 */
export type EngineCapabilities = { streaming: boolean, embeddings: boolean, max_context_length: number, hardware: Array<EngineGpuInfo>, 
/**
 * Modalities the engine can consume as input (empty = text only).
 */
input_modalities: Array<EngineModality>, 
/**
 * Modalities the engine can produce as output.
 */
output_modalities: Array<EngineModality>, 
/**
 * MIME content types accepted as input (e.g. "audio/wav",
 * "application/octet-stream", "application/json").
 */
content_types: Array<string>, 
/**
 * Engine-defined `Engine.Invoke` method names beyond the standard
 * convenience methods (e.g. "audio.generate", "signal.filter").
 * Any engine-specific operation is reachable via `Engine.Invoke`
 * even when absent from this list.
 */
methods: Array<string>, };

/**
 * `Engine.ChatChunk` notification — streamed token delta.
 */
export type EngineChatChunk = { stream_id: string, token: string, 
/**
 * Set on the final chunk.
 */
is_complete: boolean, usage?: EngineUsage, };

/**
 * `Engine.Chat` (non-streaming) / `Engine.ChatStart` (streaming) params.
 */
export type EngineChatParams = { model: string, messages: Array<EngineMessage>, temperature?: number, max_tokens?: number, 
/**
 * Present for streaming requests — chunks are tagged with this id.
 */
stream_id?: string, 
/**
 * Free-form passthrough merged into the upstream payload (same
 * semantics as the gateway's `extra` field).
 */
extra?: JsonValue, };

/**
 * `Engine.Chat` result for a non-streaming completion.
 */
export type EngineChatResult = { model: string, content: string, usage?: EngineUsage, };

/**
 * `Engine.ChatStart` acceptance result. `ok: false` rejects the stream
 * before any chunk is sent.
 */
export type EngineChatStartResult = { ok: boolean, error?: string, stream_id: string, };

/**
 * One content unit inside a message. Text is a plain string; everything
 * else is a data block described by mime + encoding so consumers can
 * decode without prior agreement:
 * - `data`: base64 bytes (standard `encoding: "base64"`)
 * - `encoding: "binary-frame"`: bytes arrive in the immediately following
 *   WebSocket binary frame (JSON notification is the announcer/trailer)
 * - `encoding: "json"`: `data` is inline JSON (structured sensor readings,
 *   tensors, feature vectors…)
 */
export type EngineContentPart = { 
/**
 * MIME type — "text/plain" for plain text parts.
 */
mime: string, 
/**
 * Encoding of `data` ("base64" | "binary-frame" | "json" | "utf-8").
 */
encoding: string, 
/**
 * Payload: base64 text, inline JSON, or raw text depending on
 * `encoding`. Empty for binary-frame parts (bytes follow as a WS
 * binary frame).
 */
data?: JsonValue, 
/**
 * Optional shape hint for tensor/sensor parts, e.g. [1, 16000]
 * (channels × samples) or the sensor schema id.
 */
shape?: Array<number>, };

export type EngineEmbeddingsParams = { model: string, input: Array<string>, };

export type EngineEmbeddingsResult = { model: string, embeddings: Array<Array<number>>, };

/**
 * One GPU the engine can drive — used by capacity-aware placement.
 */
export type EngineGpuInfo = { name: string, vram_gb: bigint, };

/**
 * `Engine.Handshake` params — the engine's first message on connect.
 */
export type EngineHandshakeParams = { 
/**
 * Optional shared token; the gateway rejects mismatches.
 */
token?: string, engine: EngineIdentity, capabilities: EngineCapabilities, };

/**
 * `Engine.Handshake` result. `ok: false` closes the connection.
 *
 * Handshake direction: when the gateway connects to an engine (engine is
 * the server), the gateway sends `Engine.Handshake` and the engine answers
 * with this result carrying its **own** declared capabilities, so the
 * gateway learns modalities/content types before any request. When the
 * engine connects to the gateway (engine is the client), the engine sends
 * `Engine.Handshake` with its capabilities in the params and the gateway
 * answers with `ok` only — the `capabilities` field is then ignored.
 */
export type EngineHandshakeResult = { ok: boolean, error?: string, protocol_version: number, 
/**
 * The engine's own capability declaration (server-mode handshake).
 */
capabilities?: EngineCapabilities, };

/**
 * Engine implementation identity (any language is fine — this is the
 * interchange contract).
 */
export type EngineIdentity = { name: string, version: string, 
/**
 * Implementation language, e.g. "rust", "cpp".
 */
language?: string, 
/**
 * Optional vendor URL.
 */
vendor?: string, };

/**
 * `Engine.Invoke` / `Engine.InvokeStart` params — the generic extension
 * channel. `method` is engine-defined (e.g. "audio.generate",
 * "signal.filter", "train.step"); `params` is any JSON the engine
 * understands. `messages` is optional and reuses the multimodal content
 * model for engines that mix free-form payloads with content parts.
 */
export type EngineInvokeParams = { method: string, params: JsonValue, messages?: Array<EngineMessage>, 
/**
 * Present for streaming invocations — chunks are tagged with this id.
 */
stream_id?: string, };

/**
 * `Engine.Invoke` result — any JSON the engine returns.
 */
export type EngineInvokeResult = { method: string, result: JsonValue, };

/**
 * `Engine.InvokeStart` acceptance result (same shape as ChatStart).
 */
export type EngineInvokeStartResult = { ok: boolean, error?: string, stream_id: string, };

/**
 * A message in an `Engine.Chat` / `Engine.ChatStart` / `Engine.Invoke`
 * payload. Content is a list of parts so mixed-modality inputs (text +
 * audio + sensor…) are representable. `role` is advisory; specialised
 * engines may ignore it.
 */
export type EngineMessage = { role: string, content: Array<EngineContentPart>, };

/**
 * Input/output modalities an engine can handle. The gateway does NOT
 * assume text — it routes and passes payloads through based on this
 * declaration.
 */
export type EngineModality = "Text" | "Audio" | "Image" | "Video" | "Sensor" | "Tensor" | "Generic";

export type EngineModelInfo = { id: string, context_length?: number, embedding: boolean, };

/**
 * `Engine.Models` result.
 */
export type EngineModelsResult = { models: Array<EngineModelInfo>, };

/**
 * `Engine.Shutdown` params — graceful stop requested by the gateway.
 */
export type EngineShutdownParams = { reason?: string, };

/**
 * `Engine.Stats` result — live telemetry for capacity-aware placement.
 */
export type EngineStatsResult = { 
/**
 * Per-GPU utilisation percentages (0-100), same shape as the agent
 * control-plane heartbeats.
 */
gpu_utilization: Array<number>, uptime_secs: bigint, 
/**
 * Model id currently loaded, when the engine pins a single model.
 */
model_loaded?: string, };

/**
 * `Engine.StreamChunk` notification — a generic streamed data block for
 * any output modality (audio frame, sensor sample batch, tensor slice…).
 */
export type EngineStreamChunk = { stream_id: string, 
/**
 * MIME type of this block (e.g. "audio/wav", "application/json").
 */
mime: string, 
/**
 * "base64" | "binary-frame" | "json" | "utf-8".
 */
encoding: string, data?: JsonValue, 
/**
 * Optional shape hint for tensor/sensor blocks.
 */
shape?: Array<number>, 
/**
 * Set on the final block.
 */
is_complete: boolean, usage?: EngineUsage, };

export type EngineUsage = { prompt_tokens: number, completion_tokens: number, };
