// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * Static capability declaration supplied at handshake time.
 */
export type EngineCapabilities = { streaming: boolean, embeddings: boolean, max_context_length: number, hardware: Array<EngineGpuInfo>, };

/**
 * `Engine.ChatChunk` notification — streamed token delta.
 */
export type EngineChatChunk = { stream_id: string, token: string, 
/**
 * Set on the final chunk.
 */
is_complete: boolean, usage?: EngineUsage, };

export type EngineChatMessage = { role: string, content: string, };

/**
 * `Engine.Chat` (non-streaming) / `Engine.ChatStart` (streaming) params.
 */
export type EngineChatParams = { model: string, messages: Array<EngineChatMessage>, temperature?: number, max_tokens?: number, 
/**
 * Present for streaming requests — chunks are tagged with this id.
 */
stream_id?: string, 
/**
 * Free-form passthrough merged into the upstream payload (same
 * semantics as the gateway's `extra` field).
 */
extra?: JsonValue, };

/**
 * `Engine.Chat` result for a non-streaming completion.
 */
export type EngineChatResult = { model: string, content: string, usage?: EngineUsage, };

/**
 * `Engine.ChatStart` acceptance result. `ok: false` rejects the stream
 * before any chunk is sent.
 */
export type EngineChatStartResult = { ok: boolean, error?: string, stream_id: string, };

export type EngineEmbeddingsParams = { model: string, input: Array<string>, };

export type EngineEmbeddingsResult = { model: string, embeddings: Array<Array<number>>, };

/**
 * One GPU the engine can drive — used by capacity-aware placement.
 */
export type EngineGpuInfo = { name: string, vram_gb: bigint, };

/**
 * `Engine.Handshake` params — the engine's first message on connect.
 */
export type EngineHandshakeParams = { 
/**
 * Optional shared token; the gateway rejects mismatches.
 */
token?: string, engine: EngineIdentity, capabilities: EngineCapabilities, };

/**
 * `Engine.Handshake` result. `ok: false` closes the connection.
 */
export type EngineHandshakeResult = { ok: boolean, error?: string, protocol_version: number, };

/**
 * Engine implementation identity (any language is fine — this is the
 * interchange contract).
 */
export type EngineIdentity = { name: string, version: string, 
/**
 * Implementation language, e.g. "rust", "cpp".
 */
language?: string, 
/**
 * Optional vendor URL.
 */
vendor?: string, };

export type EngineModelInfo = { id: string, context_length?: number, embedding: boolean, };

/**
 * `Engine.Models` result.
 */
export type EngineModelsResult = { models: Array<EngineModelInfo>, };

/**
 * `Engine.Shutdown` params — graceful stop requested by the gateway.
 */
export type EngineShutdownParams = { reason?: string, };

/**
 * `Engine.Stats` result — live telemetry for capacity-aware placement.
 */
export type EngineStatsResult = { 
/**
 * Per-GPU utilisation percentages (0-100), same shape as the agent
 * control-plane heartbeats.
 */
gpu_utilization: Array<number>, uptime_secs: bigint, 
/**
 * Model id currently loaded, when the engine pins a single model.
 */
model_loaded?: string, };

export type EngineUsage = { prompt_tokens: number, completion_tokens: number, };
