// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AnnotationType = "Note" | "Warning" | "Todo" | "Suggestion" | "Conflict";

export type ConnectionType = "Local" | "RemoteLan" | "RemoteInternet";

export type ConsultationStatus = "WaitingHuman" | "Pending" | "Answered" | "Delivered" | "Scheduled" | "Triggered" | "Cancelled" | "Replied";

export type ContainerOpStatus = "Created" | "Running" | "Stopped" | "Removed" | "Forked";

export type ConversationMessageType = "Question" | "Answer" | "Clarification" | "Objection" | "CounterProposal" | "Resolution";

export type ConversationStatus = "Active" | "Resolved" | "Deadlocked" | "Escalated";

export type FileOpStatus = "Created" | "Deleted" | "Edited" | "Written";

export type FileOperationType = "Reading" | "Editing" | "Deleting";

export type FileType = "File" | "Directory";

export type GoalStatus = "Active" | "Completed" | "Abandoned";

export type GoalTaskStatus = "Pending" | "InProgress" | "Completed" | "Failed" | "Cancelled";

export type ObservationType = "Reading" | "Editing" | "Deleting" | "Watching";

export type ScriptLanguage = "Bash" | "Sh" | "Python" | "Python3" | "Javascript" | "Typescript" | "Node" | "Zsh" | "Layer2";

export type TrackStatus = "Active" | "Completed" | "Abandoned";

export type WebSearchEngine = "Duckduckgo";
