// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RegionPolicy = {
  "china": {
    icp_number: string | null;
    data_residency_required: boolean;
    payment_domestic_only: boolean;
    pipi_consent_required: boolean;
  };
} | {
  "european_union": {
    gdpr_consent_required: boolean;
    right_to_deletion: boolean;
    right_to_export: boolean;
    dpo_contact: string | null;
    cookie_consent_required: boolean;
  };
} | {
  "russia": {
    data_localization_required: boolean;
    payment_mir_supported: boolean;
  };
} | "free_market";
