// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How a peer reached this instance — the topology of the link, not the
 * physical medium (which is platform-specific, e.g. `LinkType` in an
 * industrial gateway).
 *
 * `Local` covers both a native peer and a same-host virtualized peer; the
 * two are distinguished by a shared-secret handshake, not by IP alone.
 * `RemoteLan` is an RFC1918 / link-local peer without that secret;
 * `RemoteInternet` is anything else.
 *
 * This enum is the canonical source of truth. Platform profiles attach it
 * to their sessions as a routing tag — any authorized session is stamped
 * with how it connected — but the protocol itself does not branch on it.
 */
export type ConnectionType = "Local" | "RemoteLan" | "RemoteInternet";
