// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Backend build profile.
 */
export type BackendKind = "dev" | "nightly" | "prod" | "mock";

/**
 * Connection status of a dependency, as reported in health payloads.
 */
export type ConnectionStatus = { connected: boolean, latency: bigint, lastCheck: string, };

export type CreatedResponse = { created: Array<string>, };

export type DeletedResponse = { deleted: bigint, };

export type ErrorResponse = { error: string, message?: string, };

export type GrantItem = { id: string, scope: string, user_id: string | null, group_id: string | null, permission: string, resource_id: string | null, granted: boolean, created_at: string, };

export type GrantListResponse = { grants: Array<GrantItem>, };

/**
 * Standard /api/health response for all plana backends (backend service
 * plane). Not to be confused with the malkuth supervision worker probe
 * `plana_celestia_types::malkuth::WorkerHealthResponse` (`/healthz` on the
 * worker-lifecycle plane) — a different type with a distinct field set.
 */
export type HealthResponse = { status: ServiceStatus, version: string, kind: BackendKind, uptime: bigint, network: NetworkInfo, build_hash: string | null, engine_version: string | null, };

export type IdResponse = { id: string, };

export type MyPermissions = { role: string, permissions: Array<string>, };

/**
 * Network context from the incoming request.
 */
export type NetworkInfo = { transport: string, region: string, asn: number | null, };

export type OAuthProvider = { provider: string, client_id: string, client_secret_masked: string, public_domain: string, enabled: boolean, };

export type OkIdResponse = { ok: boolean, id: string, };

export type OkMessageResponse = { ok: boolean, message: string, };

export type OkResponse = { ok: boolean, };

export type PermissionsResponse = { role: string, permissions: Array<string>, };

export type RbacGroup = { id: string, name: string, description: string | null, 
/**
 * Members attached to this listing (the list response computes it from
 * the membership table; single-group reads may not). Carried since the
 * first DTO revision — the doc comment is what 2026-10-06 added.
 */
member_count: number, 
/**
 * Personal-visibility enforcement: members see only their own
 * resources while the flag is on (and must acknowledge it once).
 */
enforce_personal_visibility: boolean, 
/**
 * Builtin groups ship with the deployment and cannot be deleted.
 */
is_builtin: boolean, 
/**
 * Stable key for a builtin group (e.g. "administrators"); null for
 * admin-authored groups.
 */
builtin_key: string | null, 
/**
 * Admin-authored per-locale display names (locale tag → name); null
 * when none are authored.
 */
display_names: { [key in string]: string } | null, created_at: string, updated_at: string, };

export type RbacGroupsResponse = { groups: Array<RbacGroup>, };

export type RbacUser = { id: string, username: string, 
/**
 * `auth_users.email` is nullable — accounts can exist without one.
 */
email: string | null, display_name: string | null, avatar_url: string | null, is_active: boolean, role: string, tier: string, created_at: string, updated_at: string, };

export type RbacUsersResponse = { users: Array<RbacUser>, };

export type ReadinessResponse = { status: string, database: boolean, };

/**
 * Service health status. Serde uses lowercase so JSON returns "ok" etc.
 */
export type ServiceStatus = "ok" | "degraded" | "unhealthy";

export type StatusResponse = { status: string, agent_id?: string, platform?: string, id?: string, plugin_id?: string, };

/**
 * The version half of a health payload, shared by HTTP and JSON-RPC.
 *
 * Backends answer `Service.Info` with exactly this struct, built from the
 * same [`HealthResponse`] they serve on `/health`, so the two transports can
 * never drift apart.
 */
export type VersionReport = { version: string, build_hash?: string, kind: BackendKind, engine_version?: string, };
